SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_SYSVIEW_Conf._NoOS.c File Reference
SEGGER_SYSVIEW_Conf._NoOS.c File Reference
#include "SEGGER_SYSVIEW.h"
#include "SEGGER_SYSVIEW_Conf.h"
#include <stdio.h>
#include <string.h>
Macros
#define SYSVIEW_APP_NAME "NoOS Sampleproject2"
#define SYSVIEW_DEVICE_NAME "Cortex-M4"
#define SYSVIEW_TIMESTAMP_FREQ (SystemCoreClock)
#define SYSVIEW_CPU_FREQ (SystemCoreClock)
#define SYSVIEW_RAM_BASE (0)
#define USE_CYCCNT_TIMESTAMP 1
#define ENABLE_DWT_CYCCNT (USE_CYCCNT_TIMESTAMP & SEGGER_SYSVIEW_POST_MORTEM_MODE)
#define DEMCR (*(volatile unsigned long*) (0xE000EDFCuL))
#define TRACEENA_BIT (1uL << 24)
#define DWT_CTRL (*(volatile unsigned long*) (0xE0001000uL))
#define NOCYCCNT_BIT (1uL << 25)
#define CYCCNTENA_BIT (1uL << 0)
#define NUM_TASKS 16
Functions
static void _cbSendSystemDesc (void)
static void _cbSendTaskList (void)
void SYSVIEW_AddTask (void *pTask, const char *sName, U32 Prio)
void SEGGER_SYSVIEW_Conf (void)
Variables
unsigned int SystemCoreClock
static SEGGER_SYSVIEW_TASKINFO _aTasks [NUM_TASKS]
static int _NumTasks
static const SEGGER_SYSVIEW_OS_API _NoOSAPI = {NULL, _cbSendTaskList}
Macro Definition Documentation
CYCCNTENA_BIT
#define CYCCNTENA_BIT (1uL << 0)
Definition at line 37 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
DEMCR
#define DEMCR (*(volatile unsigned long*) (0xE000EDFCuL))
Definition at line 33 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
DWT_CTRL
#define DWT_CTRL (*(volatile unsigned long*) (0xE0001000uL))
Definition at line 35 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
ENABLE_DWT_CYCCNT
#define ENABLE_DWT_CYCCNT (USE_CYCCNT_TIMESTAMP & SEGGER_SYSVIEW_POST_MORTEM_MODE)
Definition at line 30 of file SEGGER_SYSVIEW_Conf._NoOS.c.
NOCYCCNT_BIT
#define NOCYCCNT_BIT (1uL << 25)
Definition at line 36 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
NUM_TASKS
#define NUM_TASKS 16
Definition at line 39 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SYSVIEW_AddTask().
SYSVIEW_APP_NAME
#define SYSVIEW_APP_NAME "NoOS Sampleproject2"
Definition at line 9 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by _cbSendSystemDesc().
SYSVIEW_CPU_FREQ
#define SYSVIEW_CPU_FREQ (SystemCoreClock)
Definition at line 18 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
SYSVIEW_DEVICE_NAME
#define SYSVIEW_DEVICE_NAME "Cortex-M4"
Definition at line 12 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by _cbSendSystemDesc().
SYSVIEW_RAM_BASE
#define SYSVIEW_RAM_BASE (0)
Definition at line 21 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
SYSVIEW_TIMESTAMP_FREQ
#define SYSVIEW_TIMESTAMP_FREQ (SystemCoreClock)
Definition at line 15 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
TRACEENA_BIT
#define TRACEENA_BIT (1uL << 24)
Definition at line 34 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
USE_CYCCNT_TIMESTAMP
#define USE_CYCCNT_TIMESTAMP 1
Definition at line 25 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Function Documentation
_cbSendSystemDesc()
static void _cbSendSystemDesc (void) static
Definition at line 50 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References SEGGER_SYSVIEW_SendSysDesc(), SYSVIEW_APP_NAME, and SYSVIEW_DEVICE_NAME.
Referenced by SEGGER_SYSVIEW_Conf().
_cbSendTaskList()
static void _cbSendTaskList (void) static
Definition at line 55 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References _aTasks, _NumTasks, and SEGGER_SYSVIEW_SendTaskInfo().
SEGGER_SYSVIEW_Conf()
void SEGGER_SYSVIEW_Conf (void)
Definition at line 88 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References _cbSendSystemDesc(), _NoOSAPI, CYCCNTENA_BIT, DEMCR, DWT_CTRL, NOCYCCNT_BIT, SEGGER_SYSVIEW_Init(), SEGGER_SYSVIEW_SetRAMBase(), SYSVIEW_CPU_FREQ, SYSVIEW_RAM_BASE, SYSVIEW_TIMESTAMP_FREQ, and TRACEENA_BIT.
Referenced by init_SeggerModules().
SYSVIEW_AddTask()
void SYSVIEW_AddTask (void * pTask, const char * sName, U32 Prio)
Definition at line 70 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References _aTasks, _NumTasks, NUM_TASKS, SEGGER_SYSVIEW_TASKINFO::Prio, SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_TASKINFO::sName, SEGGER_SYSVIEW_TASKINFO::StackBase, SEGGER_SYSVIEW_TASKINFO::StackSize, SEGGER_SYSVIEW_TASKINFO::TaskID, and U32.
Referenced by init_SeggerModules().
Variable Documentation
_aTasks
SEGGER_SYSVIEW_TASKINFO _aTasks[NUM_TASKS] static
Definition at line 40 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by _cbSendTaskList(), and SYSVIEW_AddTask().
_NoOSAPI
const SEGGER_SYSVIEW_OS_API _NoOSAPI = {NULL, _cbSendTaskList} static
Definition at line 61 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by SEGGER_SYSVIEW_Conf().
_NumTasks
int _NumTasks static
Definition at line 41 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by _cbSendTaskList(), and SYSVIEW_AddTask().
SystemCoreClock
unsigned int SystemCoreClock extern