SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_RTT.h File Reference
SEGGER_RTT.h File Reference
#include "SEGGER_RTT_Conf.h"
#include <stdlib.h>
#include <stdarg.h>
#include <stdint.h>
Classes
struct SEGGER_RTT_BUFFER_UP
struct SEGGER_RTT_BUFFER_DOWN
struct SEGGER_RTT_CB
Macros
#define _CORE_HAS_RTT_ASM_SUPPORT 0
#define RTT_USE_ASM (0)
#define _CORE_NEEDS_DMB 0
#define RTT__DMB()
#define SEGGER_RTT_CPU_CACHE_LINE_SIZE (0)
#define SEGGER_RTT_UNCACHED_OFF (0)
#define SEGGER_RTT__ROUND_UP_2_CACHE_LINE_SIZE(NumBytes)
#define SEGGER_RTT__CB_SIZE (16 + 4 + 4 + (SEGGER_RTT_MAX_NUM_UP_BUFFERS * 24) + (SEGGER_RTT_MAX_NUM_DOWN_BUFFERS * 24))
#define SEGGER_RTT__CB_PADDING (SEGGER_RTT__ROUND_UP_2_CACHE_LINE_SIZE(SEGGER_RTT__CB_SIZE) - SEGGER_RTT__CB_SIZE)
#define SEGGER_RTT_HASDATA(n)
#define SEGGER_RTT_HASDATA_UP(n)
#define NULL ((void*)0)
#define SEGGER_RTT_MODE_NO_BLOCK_SKIP (0)
#define SEGGER_RTT_MODE_NO_BLOCK_TRIM (1)
#define SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL (2)
#define SEGGER_RTT_MODE_MASK (3)
#define RTT_CTRL_RESET "\x1B[0m"
#define RTT_CTRL_CLEAR "\x1B[2J"
#define RTT_CTRL_TEXT_BLACK "\x1B[2;30m"
#define RTT_CTRL_TEXT_RED "\x1B[2;31m"
#define RTT_CTRL_TEXT_GREEN "\x1B[2;32m"
#define RTT_CTRL_TEXT_YELLOW "\x1B[2;33m"
#define RTT_CTRL_TEXT_BLUE "\x1B[2;34m"
#define RTT_CTRL_TEXT_MAGENTA "\x1B[2;35m"
#define RTT_CTRL_TEXT_CYAN "\x1B[2;36m"
#define RTT_CTRL_TEXT_WHITE "\x1B[2;37m"
#define RTT_CTRL_TEXT_BRIGHT_BLACK "\x1B[1;30m"
#define RTT_CTRL_TEXT_BRIGHT_RED "\x1B[1;31m"
#define RTT_CTRL_TEXT_BRIGHT_GREEN "\x1B[1;32m"
#define RTT_CTRL_TEXT_BRIGHT_YELLOW "\x1B[1;33m"
#define RTT_CTRL_TEXT_BRIGHT_BLUE "\x1B[1;34m"
#define RTT_CTRL_TEXT_BRIGHT_MAGENTA "\x1B[1;35m"
#define RTT_CTRL_TEXT_BRIGHT_CYAN "\x1B[1;36m"
#define RTT_CTRL_TEXT_BRIGHT_WHITE "\x1B[1;37m"
#define RTT_CTRL_BG_BLACK "\x1B[24;40m"
#define RTT_CTRL_BG_RED "\x1B[24;41m"
#define RTT_CTRL_BG_GREEN "\x1B[24;42m"
#define RTT_CTRL_BG_YELLOW "\x1B[24;43m"
#define RTT_CTRL_BG_BLUE "\x1B[24;44m"
#define RTT_CTRL_BG_MAGENTA "\x1B[24;45m"
#define RTT_CTRL_BG_CYAN "\x1B[24;46m"
#define RTT_CTRL_BG_WHITE "\x1B[24;47m"
#define RTT_CTRL_BG_BRIGHT_BLACK "\x1B[4;40m"
#define RTT_CTRL_BG_BRIGHT_RED "\x1B[4;41m"
#define RTT_CTRL_BG_BRIGHT_GREEN "\x1B[4;42m"
#define RTT_CTRL_BG_BRIGHT_YELLOW "\x1B[4;43m"
#define RTT_CTRL_BG_BRIGHT_BLUE "\x1B[4;44m"
#define RTT_CTRL_BG_BRIGHT_MAGENTA "\x1B[4;45m"
#define RTT_CTRL_BG_BRIGHT_CYAN "\x1B[4;46m"
#define RTT_CTRL_BG_BRIGHT_WHITE "\x1B[4;47m"
Functions
int SEGGER_RTT_AllocDownBuffer (const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_AllocUpBuffer (const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_ConfigUpBuffer (unsigned BufferIndex, const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_ConfigDownBuffer (unsigned BufferIndex, const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_GetKey (void)
unsigned SEGGER_RTT_HasData (unsigned BufferIndex)
int SEGGER_RTT_HasKey (void)
unsigned SEGGER_RTT_HasDataUp (unsigned BufferIndex)
void SEGGER_RTT_Init (void)
unsigned SEGGER_RTT_Read (unsigned BufferIndex, void *pBuffer, unsigned BufferSize)
unsigned SEGGER_RTT_ReadNoLock (unsigned BufferIndex, void *pData, unsigned BufferSize)
int SEGGER_RTT_SetNameDownBuffer (unsigned BufferIndex, const char *sName)
int SEGGER_RTT_SetNameUpBuffer (unsigned BufferIndex, const char *sName)
int SEGGER_RTT_SetFlagsDownBuffer (unsigned BufferIndex, unsigned Flags)
int SEGGER_RTT_SetFlagsUpBuffer (unsigned BufferIndex, unsigned Flags)
int SEGGER_RTT_WaitKey (void)
unsigned SEGGER_RTT_Write (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteSkipNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_ASM_WriteSkipNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteString (unsigned BufferIndex, const char *s)
void SEGGER_RTT_WriteWithOverwriteNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_PutChar (unsigned BufferIndex, char c)
unsigned SEGGER_RTT_PutCharSkip (unsigned BufferIndex, char c)
unsigned SEGGER_RTT_PutCharSkipNoLock (unsigned BufferIndex, char c)
unsigned SEGGER_RTT_GetAvailWriteSpace (unsigned BufferIndex)
unsigned SEGGER_RTT_GetBytesInBuffer (unsigned BufferIndex)
unsigned SEGGER_RTT_ReadUpBuffer (unsigned BufferIndex, void *pBuffer, unsigned BufferSize)
unsigned SEGGER_RTT_ReadUpBufferNoLock (unsigned BufferIndex, void *pData, unsigned BufferSize)
unsigned SEGGER_RTT_WriteDownBuffer (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteDownBufferNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
int SEGGER_RTT_SetTerminal (unsigned char TerminalId)
int SEGGER_RTT_TerminalOut (unsigned char TerminalId, const char *s)
int SEGGER_RTT_printf (unsigned BufferIndex, const char *sFormat,...)
int SEGGER_RTT_vprintf (unsigned BufferIndex, const char *sFormat, va_list *pParamList)
Variables
SEGGER_RTT_CB _SEGGER_RTT
Macro Definition Documentation
_CORE_HAS_RTT_ASM_SUPPORT
#define _CORE_HAS_RTT_ASM_SUPPORT 0
Definition at line 247 of file SEGGER_RTT.h.
_CORE_NEEDS_DMB
#define _CORE_NEEDS_DMB 0
Definition at line 257 of file SEGGER_RTT.h.
NULL
#define NULL ((void*)0)
Definition at line 455 of file SEGGER_RTT.h.
Referenced by _EncodeStr(), _VPrintTarget(), _write(), SEGGER_RTT_AllocDownBuffer(), SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_vprintf(), and Sys_ConsoleInit().
RTT__DMB
#define RTT__DMB ()
Definition at line 264 of file SEGGER_RTT.h.
Referenced by _DoInit(), _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_AllocDownBuffer(), SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_PutChar(), SEGGER_RTT_PutCharSkip(), SEGGER_RTT_PutCharSkipNoLock(), SEGGER_RTT_WriteSkipNoLock(), and SEGGER_RTT_WriteWithOverwriteNoLock().
RTT_CTRL_BG_BLACK
#define RTT_CTRL_BG_BLACK "\x1B[24;40m"
Definition at line 498 of file SEGGER_RTT.h.
RTT_CTRL_BG_BLUE
#define RTT_CTRL_BG_BLUE "\x1B[24;44m"
Definition at line 502 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_BLACK
#define RTT_CTRL_BG_BRIGHT_BLACK "\x1B[4;40m"
Definition at line 507 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_BLUE
#define RTT_CTRL_BG_BRIGHT_BLUE "\x1B[4;44m"
Definition at line 511 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_CYAN
#define RTT_CTRL_BG_BRIGHT_CYAN "\x1B[4;46m"
Definition at line 513 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_GREEN
#define RTT_CTRL_BG_BRIGHT_GREEN "\x1B[4;42m"
Definition at line 509 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_MAGENTA
#define RTT_CTRL_BG_BRIGHT_MAGENTA "\x1B[4;45m"
Definition at line 512 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_RED
#define RTT_CTRL_BG_BRIGHT_RED "\x1B[4;41m"
Definition at line 508 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_WHITE
#define RTT_CTRL_BG_BRIGHT_WHITE "\x1B[4;47m"
Definition at line 514 of file SEGGER_RTT.h.
RTT_CTRL_BG_BRIGHT_YELLOW
#define RTT_CTRL_BG_BRIGHT_YELLOW "\x1B[4;43m"
Definition at line 510 of file SEGGER_RTT.h.
RTT_CTRL_BG_CYAN
#define RTT_CTRL_BG_CYAN "\x1B[24;46m"
Definition at line 504 of file SEGGER_RTT.h.
RTT_CTRL_BG_GREEN
#define RTT_CTRL_BG_GREEN "\x1B[24;42m"
Definition at line 500 of file SEGGER_RTT.h.
RTT_CTRL_BG_MAGENTA
#define RTT_CTRL_BG_MAGENTA "\x1B[24;45m"
Definition at line 503 of file SEGGER_RTT.h.
RTT_CTRL_BG_RED
#define RTT_CTRL_BG_RED "\x1B[24;41m"
Definition at line 499 of file SEGGER_RTT.h.
RTT_CTRL_BG_WHITE
#define RTT_CTRL_BG_WHITE "\x1B[24;47m"
Definition at line 505 of file SEGGER_RTT.h.
RTT_CTRL_BG_YELLOW
#define RTT_CTRL_BG_YELLOW "\x1B[24;43m"
Definition at line 501 of file SEGGER_RTT.h.
RTT_CTRL_CLEAR
#define RTT_CTRL_CLEAR "\x1B[2J"
Definition at line 478 of file SEGGER_RTT.h.
RTT_CTRL_RESET
#define RTT_CTRL_RESET "\x1B[0m"
Definition at line 477 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BLACK
#define RTT_CTRL_TEXT_BLACK "\x1B[2;30m"
Definition at line 480 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BLUE
#define RTT_CTRL_TEXT_BLUE "\x1B[2;34m"
Definition at line 484 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_BLACK
#define RTT_CTRL_TEXT_BRIGHT_BLACK "\x1B[1;30m"
Definition at line 489 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_BLUE
#define RTT_CTRL_TEXT_BRIGHT_BLUE "\x1B[1;34m"
Definition at line 493 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_CYAN
#define RTT_CTRL_TEXT_BRIGHT_CYAN "\x1B[1;36m"
Definition at line 495 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_GREEN
#define RTT_CTRL_TEXT_BRIGHT_GREEN "\x1B[1;32m"
Definition at line 491 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_MAGENTA
#define RTT_CTRL_TEXT_BRIGHT_MAGENTA "\x1B[1;35m"
Definition at line 494 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_RED
#define RTT_CTRL_TEXT_BRIGHT_RED "\x1B[1;31m"
Definition at line 490 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_WHITE
#define RTT_CTRL_TEXT_BRIGHT_WHITE "\x1B[1;37m"
Definition at line 496 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_BRIGHT_YELLOW
#define RTT_CTRL_TEXT_BRIGHT_YELLOW "\x1B[1;33m"
Definition at line 492 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_CYAN
#define RTT_CTRL_TEXT_CYAN "\x1B[2;36m"
Definition at line 486 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_GREEN
#define RTT_CTRL_TEXT_GREEN "\x1B[2;32m"
Definition at line 482 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_MAGENTA
#define RTT_CTRL_TEXT_MAGENTA "\x1B[2;35m"
Definition at line 485 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_RED
#define RTT_CTRL_TEXT_RED "\x1B[2;31m"
Definition at line 481 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_WHITE
#define RTT_CTRL_TEXT_WHITE "\x1B[2;37m"
Definition at line 487 of file SEGGER_RTT.h.
RTT_CTRL_TEXT_YELLOW
#define RTT_CTRL_TEXT_YELLOW "\x1B[2;33m"
Definition at line 483 of file SEGGER_RTT.h.
RTT_USE_ASM
#define RTT_USE_ASM (0)
Definition at line 252 of file SEGGER_RTT.h.
SEGGER_RTT__CB_PADDING
#define SEGGER_RTT__CB_PADDING (SEGGER_RTT__ROUND_UP_2_CACHE_LINE_SIZE(SEGGER_RTT__CB_SIZE) - SEGGER_RTT__CB_SIZE)
Definition at line 310 of file SEGGER_RTT.h.
SEGGER_RTT__CB_SIZE
#define SEGGER_RTT__CB_SIZE (16 + 4 + 4 + (SEGGER_RTT_MAX_NUM_UP_BUFFERS * 24) + (SEGGER_RTT_MAX_NUM_DOWN_BUFFERS * 24))
Definition at line 309 of file SEGGER_RTT.h.
SEGGER_RTT__ROUND_UP_2_CACHE_LINE_SIZE
#define SEGGER_RTT__ROUND_UP_2_CACHE_LINE_SIZE (NumBytes)
Value:
(NumBytes)
Definition at line 307 of file SEGGER_RTT.h.
SEGGER_RTT_CPU_CACHE_LINE_SIZE
#define SEGGER_RTT_CPU_CACHE_LINE_SIZE (0)
Definition at line 269 of file SEGGER_RTT.h.
SEGGER_RTT_HASDATA
#define SEGGER_RTT_HASDATA (n)
Value:
(((SEGGER_RTT_BUFFER_DOWN*)((uintptr_t)&_SEGGER_RTT.aDown[n] + SEGGER_RTT_UNCACHED_OFF))->WrOff - ((SEGGER_RTT_BUFFER_DOWN*)((uintptr_t)&_SEGGER_RTT.aDown[n] + SEGGER_RTT_UNCACHED_OFF))->RdOff)
Definition at line 408 of file SEGGER_RTT.h.
Referenced by _SendPacket(), and SEGGER_SYSVIEW_IsStarted().
SEGGER_RTT_HASDATA_UP
#define SEGGER_RTT_HASDATA_UP (n)
Value:
(((SEGGER_RTT_BUFFER_UP*)((uintptr_t)&_SEGGER_RTT.aUp[n] + SEGGER_RTT_UNCACHED_OFF))->WrOff - ((SEGGER_RTT_BUFFER_UP*)((uintptr_t)&_SEGGER_RTT.aUp[n] + SEGGER_RTT_UNCACHED_OFF))->RdOff)
Definition at line 425 of file SEGGER_RTT.h.
SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL
#define SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL (2)
Definition at line 470 of file SEGGER_RTT.h.
Referenced by SEGGER_RTT_PutChar(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), and SEGGER_RTT_WriteNoLock().
SEGGER_RTT_MODE_MASK
#define SEGGER_RTT_MODE_MASK (3)
Definition at line 471 of file SEGGER_RTT.h.
Referenced by SEGGER_RTT_SetTerminal(), and SEGGER_RTT_TerminalOut().
SEGGER_RTT_MODE_NO_BLOCK_SKIP
#define SEGGER_RTT_MODE_NO_BLOCK_SKIP (0)
Definition at line 468 of file SEGGER_RTT.h.
Referenced by SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), SEGGER_RTT_WriteNoLock(), and SEGGER_SYSVIEW_Init().
SEGGER_RTT_MODE_NO_BLOCK_TRIM
#define SEGGER_RTT_MODE_NO_BLOCK_TRIM (1)
Definition at line 469 of file SEGGER_RTT.h.
Referenced by SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), and SEGGER_RTT_WriteNoLock().
SEGGER_RTT_UNCACHED_OFF
#define SEGGER_RTT_UNCACHED_OFF (0)
Definition at line 276 of file SEGGER_RTT.h.
Referenced by _DoInit(), _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_AllocDownBuffer(), SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_ConfigUpBuffer(), SEGGER_RTT_GetAvailWriteSpace(), SEGGER_RTT_GetBytesInBuffer(), SEGGER_RTT_HasData(), SEGGER_RTT_HasDataUp(), SEGGER_RTT_HasKey(), SEGGER_RTT_PutChar(), SEGGER_RTT_PutCharSkip(), SEGGER_RTT_PutCharSkipNoLock(), SEGGER_RTT_ReadNoLock(), SEGGER_RTT_ReadUpBufferNoLock(), SEGGER_RTT_SetFlagsDownBuffer(), SEGGER_RTT_SetFlagsUpBuffer(), SEGGER_RTT_SetNameDownBuffer(), SEGGER_RTT_SetNameUpBuffer(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), SEGGER_RTT_WriteNoLock(), SEGGER_RTT_WriteSkipNoLock(), and SEGGER_RTT_WriteWithOverwriteNoLock().
Function Documentation
SEGGER_RTT_AllocDownBuffer()
int SEGGER_RTT_AllocDownBuffer (const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1559 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, NULL, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, SEGGER_RTT_BUFFER_DOWN::sName, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_AllocUpBuffer()
int SEGGER_RTT_AllocUpBuffer (const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1608 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, NULL, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, SEGGER_RTT_BUFFER_UP::sName, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_ASM_WriteSkipNoLock()
unsigned SEGGER_RTT_ASM_WriteSkipNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
SEGGER_RTT_ConfigDownBuffer()
int SEGGER_RTT_ConfigDownBuffer (unsigned BufferIndex, const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1715 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, SEGGER_RTT_BUFFER_DOWN::sName, and SEGGER_RTT_BUFFER_DOWN::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_ConfigUpBuffer()
int SEGGER_RTT_ConfigUpBuffer (unsigned BufferIndex, const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1663 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, SEGGER_RTT_BUFFER_UP::sName, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_GetAvailWriteSpace()
unsigned SEGGER_RTT_GetAvailWriteSpace (unsigned BufferIndex)
Definition at line 2051 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, SEGGER_RTT_CB::aUp, and SEGGER_RTT_UNCACHED_OFF.
SEGGER_RTT_GetBytesInBuffer()
unsigned SEGGER_RTT_GetBytesInBuffer (unsigned BufferIndex)
Definition at line 2072 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_GetKey()
int SEGGER_RTT_GetKey (void)
Definition at line 1430 of file SEGGER_RTT.c.
References SEGGER_RTT_Read().
Referenced by SEGGER_RTT_WaitKey().
SEGGER_RTT_HasData()
unsigned SEGGER_RTT_HasData (unsigned BufferIndex)
Definition at line 1509 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_HasDataUp()
unsigned SEGGER_RTT_HasDataUp (unsigned BufferIndex)
Definition at line 1530 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_HasKey()
int SEGGER_RTT_HasKey (void)
Definition at line 1481 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_Init()
void SEGGER_RTT_Init (void)
Definition at line 1893 of file SEGGER_RTT.c.
References _DoInit().
SEGGER_RTT_printf()
int SEGGER_RTT_printf (unsigned BufferIndex, const char * sFormat, ...)
Definition at line 512 of file SEGGER_RTT_printf.c.
References SEGGER_RTT_vprintf().
SEGGER_RTT_PutChar()
unsigned SEGGER_RTT_PutChar (unsigned BufferIndex, char c)
Definition at line 1367 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_PutCharSkip()
unsigned SEGGER_RTT_PutCharSkip (unsigned BufferIndex, char c)
Definition at line 1308 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_PutCharSkipNoLock()
unsigned SEGGER_RTT_PutCharSkipNoLock (unsigned BufferIndex, char c)
Definition at line 1258 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_Read()
unsigned SEGGER_RTT_Read (unsigned BufferIndex, void * pBuffer, unsigned BufferSize)
Definition at line 787 of file SEGGER_RTT.c.
References SEGGER_RTT_LOCK, SEGGER_RTT_ReadNoLock(), and SEGGER_RTT_UNLOCK.
Referenced by SEGGER_RTT_GetKey().
SEGGER_RTT_ReadNoLock()
unsigned SEGGER_RTT_ReadNoLock (unsigned BufferIndex, void * pData, unsigned BufferSize)
Definition at line 658 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, MIN, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, and SEGGER_RTT_BUFFER_DOWN::WrOff.
Referenced by _HandleIncomingPacket(), and SEGGER_RTT_Read().
SEGGER_RTT_ReadUpBuffer()
unsigned SEGGER_RTT_ReadUpBuffer (unsigned BufferIndex, void * pBuffer, unsigned BufferSize)
Definition at line 755 of file SEGGER_RTT.c.
References SEGGER_RTT_LOCK, SEGGER_RTT_ReadUpBufferNoLock(), and SEGGER_RTT_UNLOCK.
SEGGER_RTT_ReadUpBufferNoLock()
unsigned SEGGER_RTT_ReadUpBufferNoLock (unsigned BufferIndex, void * pData, unsigned BufferSize)
Definition at line 566 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, MIN, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_RTT_ReadUpBuffer().
SEGGER_RTT_SetFlagsDownBuffer()
int SEGGER_RTT_SetFlagsDownBuffer (unsigned BufferIndex, unsigned Flags)
Definition at line 1865 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_SetFlagsUpBuffer()
int SEGGER_RTT_SetFlagsUpBuffer (unsigned BufferIndex, unsigned Flags)
Definition at line 1829 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_SetNameDownBuffer()
int SEGGER_RTT_SetNameDownBuffer (unsigned BufferIndex, const char * sName)
Definition at line 1793 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and SEGGER_RTT_BUFFER_DOWN::sName.
SEGGER_RTT_SetNameUpBuffer()
int SEGGER_RTT_SetNameUpBuffer (unsigned BufferIndex, const char * sName)
Definition at line 1758 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and SEGGER_RTT_BUFFER_UP::sName.
SEGGER_RTT_SetTerminal()
int SEGGER_RTT_SetTerminal (unsigned char TerminalId)
Definition at line 1914 of file SEGGER_RTT.c.
References _ActiveTerminal, _aTerminalId, _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_MASK, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_TerminalOut()
int SEGGER_RTT_TerminalOut (unsigned char TerminalId, const char * s)
Definition at line 1963 of file SEGGER_RTT.c.
References _ActiveTerminal, _aTerminalId, _GetAvailWriteSpace(), _PostTerminalSwitch(), _SEGGER_RTT, _WriteBlocking(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_MASK, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and STRLEN.
SEGGER_RTT_vprintf()
int SEGGER_RTT_vprintf (unsigned BufferIndex, const char * sFormat, va_list * pParamList)
Definition at line 321 of file SEGGER_RTT_printf.c.
References _PrintInt(), _PrintUnsigned(), _StoreChar(), SEGGER_RTT_PRINTF_DESC::BufferSize, SEGGER_RTT_PRINTF_DESC::Cnt, FORMAT_FLAG_ALTERNATE, FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, FORMAT_FLAG_PRINT_SIGN, NULL, SEGGER_RTT_PRINTF_DESC::pBuffer, SEGGER_RTT_PRINTF_DESC::ReturnValue, SEGGER_RTT_PRINTF_DESC::RTTBufferIndex, SEGGER_RTT_PRINTF_BUFFER_SIZE, and SEGGER_RTT_Write().
Referenced by SEGGER_RTT_printf().
SEGGER_RTT_WaitKey()
int SEGGER_RTT_WaitKey (void)
Definition at line 1458 of file SEGGER_RTT.c.
References SEGGER_RTT_GetKey().
SEGGER_RTT_Write()
unsigned SEGGER_RTT_Write (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1198 of file SEGGER_RTT.c.
References INIT, SEGGER_RTT_LOCK, SEGGER_RTT_UNLOCK, and SEGGER_RTT_WriteNoLock().
Referenced by _StoreChar(), SEGGER_RTT_vprintf(), and SEGGER_RTT_WriteString().
SEGGER_RTT_WriteDownBuffer()
unsigned SEGGER_RTT_WriteDownBuffer (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1169 of file SEGGER_RTT.c.
References INIT, SEGGER_RTT_LOCK, SEGGER_RTT_UNLOCK, and SEGGER_RTT_WriteDownBufferNoLock().
SEGGER_RTT_WriteDownBufferNoLock()
unsigned SEGGER_RTT_WriteDownBufferNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1018 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_UP::Flags, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, and SEGGER_RTT_UNCACHED_OFF.
Referenced by SEGGER_RTT_WriteDownBuffer().
SEGGER_RTT_WriteNoLock()
unsigned SEGGER_RTT_WriteNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1093 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, and SEGGER_RTT_UNCACHED_OFF.
Referenced by SEGGER_RTT_Write().
SEGGER_RTT_WriteSkipNoLock()
unsigned SEGGER_RTT_WriteSkipNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 927 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by _SendPacket(), _TrySendOverflowPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_RTT_WriteString()
unsigned SEGGER_RTT_WriteString (unsigned BufferIndex, const char * s)
Definition at line 1228 of file SEGGER_RTT.c.
References SEGGER_RTT_Write(), and STRLEN.
SEGGER_RTT_WriteWithOverwriteNoLock()
void SEGGER_RTT_WriteWithOverwriteNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 826 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by _SendPacket().
Variable Documentation
_SEGGER_RTT
SEGGER_RTT_CB _SEGGER_RTT extern
Referenced by _DoInit(), SEGGER_RTT_AllocDownBuffer(), SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_ConfigUpBuffer(), SEGGER_RTT_GetAvailWriteSpace(), SEGGER_RTT_GetBytesInBuffer(), SEGGER_RTT_HasData(), SEGGER_RTT_HasDataUp(), SEGGER_RTT_HasKey(), SEGGER_RTT_PutChar(), SEGGER_RTT_PutCharSkip(), SEGGER_RTT_PutCharSkipNoLock(), SEGGER_RTT_ReadNoLock(), SEGGER_RTT_ReadUpBufferNoLock(), SEGGER_RTT_SetFlagsDownBuffer(), SEGGER_RTT_SetFlagsUpBuffer(), SEGGER_RTT_SetNameDownBuffer(), SEGGER_RTT_SetNameUpBuffer(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), SEGGER_RTT_WriteNoLock(), SEGGER_RTT_WriteSkipNoLock(), and SEGGER_RTT_WriteWithOverwriteNoLock().