SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_RTT_printf.c File Reference
SEGGER_RTT_printf.c File Reference
#include "SEGGER_RTT.h"
#include "SEGGER_RTT_Conf.h"
#include <stdlib.h>
#include <stdarg.h>
Classes
struct SEGGER_RTT_PRINTF_DESC
Macros
#define FORMAT_FLAG_LEFT_JUSTIFY (1u << 0)
#define FORMAT_FLAG_PAD_ZERO (1u << 1)
#define FORMAT_FLAG_PRINT_SIGN (1u << 2)
#define FORMAT_FLAG_ALTERNATE (1u << 3)
Functions
static void _StoreChar (SEGGER_RTT_PRINTF_DESC *p, char c)
static void _PrintUnsigned (SEGGER_RTT_PRINTF_DESC *pBufferDesc, unsigned v, unsigned Base, unsigned NumDigits, unsigned FieldWidth, unsigned FormatFlags)
static void _PrintInt (SEGGER_RTT_PRINTF_DESC *pBufferDesc, int v, unsigned Base, unsigned NumDigits, unsigned FieldWidth, unsigned FormatFlags)
int SEGGER_RTT_vprintf (unsigned BufferIndex, const char *sFormat, va_list *pParamList)
int SEGGER_RTT_printf (unsigned BufferIndex, const char *sFormat,...)
Macro Definition Documentation
FORMAT_FLAG_ALTERNATE
#define FORMAT_FLAG_ALTERNATE (1u << 3)
Definition at line 75 of file SEGGER_RTT_printf.c.
Referenced by SEGGER_RTT_vprintf().
FORMAT_FLAG_LEFT_JUSTIFY
#define FORMAT_FLAG_LEFT_JUSTIFY (1u << 0)
Definition at line 72 of file SEGGER_RTT_printf.c.
Referenced by _PrintInt(), _PrintUnsigned(), and SEGGER_RTT_vprintf().
FORMAT_FLAG_PAD_ZERO
#define FORMAT_FLAG_PAD_ZERO (1u << 1)
Definition at line 73 of file SEGGER_RTT_printf.c.
Referenced by _PrintInt(), _PrintUnsigned(), and SEGGER_RTT_vprintf().
FORMAT_FLAG_PRINT_SIGN
#define FORMAT_FLAG_PRINT_SIGN (1u << 2)
Definition at line 74 of file SEGGER_RTT_printf.c.
Referenced by _PrintInt(), and SEGGER_RTT_vprintf().
Function Documentation
_PrintInt()
static void _PrintInt (SEGGER_RTT_PRINTF_DESC * pBufferDesc, int v, unsigned Base, unsigned NumDigits, unsigned FieldWidth, unsigned FormatFlags) static
Definition at line 226 of file SEGGER_RTT_printf.c.
References _PrintUnsigned(), _StoreChar(), FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, FORMAT_FLAG_PRINT_SIGN, and SEGGER_RTT_PRINTF_DESC::ReturnValue.
Referenced by SEGGER_RTT_vprintf().
_PrintUnsigned()
static void _PrintUnsigned (SEGGER_RTT_PRINTF_DESC * pBufferDesc, unsigned v, unsigned Base, unsigned NumDigits, unsigned FieldWidth, unsigned FormatFlags) static
Definition at line 136 of file SEGGER_RTT_printf.c.
References _StoreChar(), FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, and SEGGER_RTT_PRINTF_DESC::ReturnValue.
Referenced by _PrintInt(), and SEGGER_RTT_vprintf().
_StoreChar()
static void _StoreChar (SEGGER_RTT_PRINTF_DESC * p, char c) static
Definition at line 111 of file SEGGER_RTT_printf.c.
References SEGGER_RTT_PRINTF_DESC::BufferSize, SEGGER_RTT_PRINTF_DESC::Cnt, SEGGER_RTT_PRINTF_DESC::pBuffer, SEGGER_RTT_PRINTF_DESC::ReturnValue, SEGGER_RTT_PRINTF_DESC::RTTBufferIndex, and SEGGER_RTT_Write().
Referenced by _PrintInt(), _PrintUnsigned(), and SEGGER_RTT_vprintf().
SEGGER_RTT_printf()
int SEGGER_RTT_printf (unsigned BufferIndex, const char * sFormat, ...)
Definition at line 512 of file SEGGER_RTT_printf.c.
References SEGGER_RTT_vprintf().
SEGGER_RTT_vprintf()
int SEGGER_RTT_vprintf (unsigned BufferIndex, const char * sFormat, va_list * pParamList)
Definition at line 321 of file SEGGER_RTT_printf.c.
References _PrintInt(), _PrintUnsigned(), _StoreChar(), SEGGER_RTT_PRINTF_DESC::BufferSize, SEGGER_RTT_PRINTF_DESC::Cnt, FORMAT_FLAG_ALTERNATE, FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, FORMAT_FLAG_PRINT_SIGN, NULL, SEGGER_RTT_PRINTF_DESC::pBuffer, SEGGER_RTT_PRINTF_DESC::ReturnValue, SEGGER_RTT_PRINTF_DESC::RTTBufferIndex, SEGGER_RTT_PRINTF_BUFFER_SIZE, and SEGGER_RTT_Write().
Referenced by SEGGER_RTT_printf().