SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_RTT.c File Reference
SEGGER_RTT.c File Reference
#include "SEGGER_RTT.h"
#include <string.h>
Macros
#define SEGGER_RTT_ALIGNMENT SEGGER_RTT_CPU_CACHE_LINE_SIZE
#define SEGGER_RTT_BUFFER_ALIGNMENT SEGGER_RTT_CPU_CACHE_LINE_SIZE
#define STRLEN(a)
#define STRCPY(pDest, pSrc)
#define SEGGER_RTT_MEMCPY(pDest, pSrc, NumBytes)
#define MIN(a, b)
#define MAX(a, b)
#define SEGGER_RTT_ALIGN(Var, Alignment)
#define SEGGER_RTT_PUT_SECTION(Var, Section)
#define SEGGER_RTT_CB_ALIGN(Var)
#define SEGGER_RTT_BUFFER_ALIGN(Var)
#define SEGGER_RTT_PUT_CB_SECTION(Var)
#define SEGGER_RTT_PUT_BUFFER_SECTION(Var)
#define INIT()
Functions
SEGGER_RTT_PUT_CB_SECTION (SEGGER_RTT_CB_ALIGN(SEGGER_RTT_CB _SEGGER_RTT))
SEGGER_RTT_PUT_BUFFER_SECTION (SEGGER_RTT_BUFFER_ALIGN(static char _acUpBuffer[BUFFER_SIZE_UP]))
SEGGER_RTT_PUT_BUFFER_SECTION (SEGGER_RTT_BUFFER_ALIGN(static char _acDownBuffer[BUFFER_SIZE_DOWN]))
static void _DoInit (void)
static unsigned _WriteBlocking (SEGGER_RTT_BUFFER_UP *pRing, const char *pBuffer, unsigned NumBytes)
static void _WriteNoCheck (SEGGER_RTT_BUFFER_UP *pRing, const char *pData, unsigned NumBytes)
static void _PostTerminalSwitch (SEGGER_RTT_BUFFER_UP *pRing, unsigned char TerminalId)
static unsigned _GetAvailWriteSpace (SEGGER_RTT_BUFFER_UP *pRing)
unsigned SEGGER_RTT_ReadUpBufferNoLock (unsigned BufferIndex, void *pData, unsigned BufferSize)
unsigned SEGGER_RTT_ReadNoLock (unsigned BufferIndex, void *pData, unsigned BufferSize)
unsigned SEGGER_RTT_ReadUpBuffer (unsigned BufferIndex, void *pBuffer, unsigned BufferSize)
unsigned SEGGER_RTT_Read (unsigned BufferIndex, void *pBuffer, unsigned BufferSize)
void SEGGER_RTT_WriteWithOverwriteNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteSkipNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteDownBufferNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteNoLock (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteDownBuffer (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_Write (unsigned BufferIndex, const void *pBuffer, unsigned NumBytes)
unsigned SEGGER_RTT_WriteString (unsigned BufferIndex, const char *s)
unsigned SEGGER_RTT_PutCharSkipNoLock (unsigned BufferIndex, char c)
unsigned SEGGER_RTT_PutCharSkip (unsigned BufferIndex, char c)
unsigned SEGGER_RTT_PutChar (unsigned BufferIndex, char c)
int SEGGER_RTT_GetKey (void)
int SEGGER_RTT_WaitKey (void)
int SEGGER_RTT_HasKey (void)
unsigned SEGGER_RTT_HasData (unsigned BufferIndex)
unsigned SEGGER_RTT_HasDataUp (unsigned BufferIndex)
int SEGGER_RTT_AllocDownBuffer (const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_AllocUpBuffer (const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_ConfigUpBuffer (unsigned BufferIndex, const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_ConfigDownBuffer (unsigned BufferIndex, const char *sName, void *pBuffer, unsigned BufferSize, unsigned Flags)
int SEGGER_RTT_SetNameUpBuffer (unsigned BufferIndex, const char *sName)
int SEGGER_RTT_SetNameDownBuffer (unsigned BufferIndex, const char *sName)
int SEGGER_RTT_SetFlagsUpBuffer (unsigned BufferIndex, unsigned Flags)
int SEGGER_RTT_SetFlagsDownBuffer (unsigned BufferIndex, unsigned Flags)
void SEGGER_RTT_Init (void)
int SEGGER_RTT_SetTerminal (unsigned char TerminalId)
int SEGGER_RTT_TerminalOut (unsigned char TerminalId, const char *s)
unsigned SEGGER_RTT_GetAvailWriteSpace (unsigned BufferIndex)
unsigned SEGGER_RTT_GetBytesInBuffer (unsigned BufferIndex)
Variables
static const unsigned char _aTerminalId [16] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' }
static unsigned char _ActiveTerminal
Macro Definition Documentation
INIT
#define INIT ()
Value:
    do {                                                                                     \
      volatile SEGGER_RTT_CB* pRTTCBInit;                                                    \
      pRTTCBInit = (volatile SEGGER_RTT_CB*)((uintptr_t)&_SEGGER_RTT + SEGGER_RTT_UNCACHED_OFF); \
      if (pRTTCBInit->acID[0] != 'S') {                                                      \
        _DoInit();                                                                           \
      }                                                                                      \
    } while (0)
Definition at line 298 of file SEGGER_RTT.c.
Referenced by SEGGER_RTT_AllocDownBuffer(), SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_ConfigUpBuffer(), SEGGER_RTT_HasKey(), SEGGER_RTT_PutChar(), SEGGER_RTT_PutCharSkip(), SEGGER_RTT_ReadNoLock(), SEGGER_RTT_ReadUpBufferNoLock(), SEGGER_RTT_SetFlagsDownBuffer(), SEGGER_RTT_SetFlagsUpBuffer(), SEGGER_RTT_SetNameDownBuffer(), SEGGER_RTT_SetNameUpBuffer(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_Write(), and SEGGER_RTT_WriteDownBuffer().
MAX
#define MAX (a, b)
Value:
(((a) > (b)) ? (a) : (b))
Definition at line 169 of file SEGGER_RTT.c.
MIN
#define MIN (a, b)
Value:
(((a) < (b)) ? (a) : (b))
Definition at line 165 of file SEGGER_RTT.c.
Referenced by _WriteBlocking(), SEGGER_RTT_ReadNoLock(), and SEGGER_RTT_ReadUpBufferNoLock().
SEGGER_RTT_ALIGN
#define SEGGER_RTT_ALIGN (Var, Alignment)
Value:
Var
Definition at line 195 of file SEGGER_RTT.c.
SEGGER_RTT_ALIGNMENT
#define SEGGER_RTT_ALIGNMENT SEGGER_RTT_CPU_CACHE_LINE_SIZE
Definition at line 125 of file SEGGER_RTT.c.
SEGGER_RTT_BUFFER_ALIGN
#define SEGGER_RTT_BUFFER_ALIGN (Var)
Value:
Var
Definition at line 222 of file SEGGER_RTT.c.
SEGGER_RTT_BUFFER_ALIGNMENT
#define SEGGER_RTT_BUFFER_ALIGNMENT SEGGER_RTT_CPU_CACHE_LINE_SIZE
Definition at line 129 of file SEGGER_RTT.c.
SEGGER_RTT_CB_ALIGN
#define SEGGER_RTT_CB_ALIGN (Var)
Value:
Var
Definition at line 216 of file SEGGER_RTT.c.
SEGGER_RTT_MEMCPY
#define SEGGER_RTT_MEMCPY (pDest, pSrc, NumBytes)
Value:
memcpy((pDest), (pSrc), (NumBytes))
Definition at line 160 of file SEGGER_RTT.c.
Referenced by _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_ReadNoLock(), SEGGER_RTT_ReadUpBufferNoLock(), and SEGGER_RTT_WriteWithOverwriteNoLock().
SEGGER_RTT_PUT_BUFFER_SECTION
#define SEGGER_RTT_PUT_BUFFER_SECTION (Var)
Value:
Var
Definition at line 235 of file SEGGER_RTT.c.
SEGGER_RTT_PUT_CB_SECTION
#define SEGGER_RTT_PUT_CB_SECTION (Var)
Value:
Var
Definition at line 229 of file SEGGER_RTT.c.
SEGGER_RTT_PUT_SECTION
#define SEGGER_RTT_PUT_SECTION (Var, Section)
Value:
Var
Definition at line 210 of file SEGGER_RTT.c.
STRCPY
#define STRCPY (pDest, pSrc)
Value:
strcpy((pDest), (pSrc))
Definition at line 149 of file SEGGER_RTT.c.
STRLEN
#define STRLEN (a)
Value:
strlen((a))
Definition at line 145 of file SEGGER_RTT.c.
Referenced by SEGGER_RTT_TerminalOut(), and SEGGER_RTT_WriteString().
Function Documentation
_DoInit()
static void _DoInit (void) static
Definition at line 307 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::acID, SEGGER_RTT_CB::aDown, SEGGER_RTT_CB::aUp, BUFFER_SIZE_DOWN, BUFFER_SIZE_UP, SEGGER_RTT_BUFFER_DOWN::Flags, SEGGER_RTT_BUFFER_UP::Flags, SEGGER_RTT_CB::MaxNumDownBuffers, SEGGER_RTT_CB::MaxNumUpBuffers, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_MODE_DEFAULT, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, SEGGER_RTT_BUFFER_DOWN::sName, SEGGER_RTT_BUFFER_UP::sName, SEGGER_RTT_BUFFER_DOWN::WrOff, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_RTT_Init().
_GetAvailWriteSpace()
static unsigned _GetAvailWriteSpace (SEGGER_RTT_BUFFER_UP * pRing) static
Definition at line 519 of file SEGGER_RTT.c.
References SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_RTT_GetAvailWriteSpace(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), and SEGGER_RTT_WriteNoLock().
_PostTerminalSwitch()
static void _PostTerminalSwitch (SEGGER_RTT_BUFFER_UP * pRing, unsigned char TerminalId) static
Definition at line 497 of file SEGGER_RTT.c.
References _aTerminalId, and _WriteBlocking().
Referenced by SEGGER_RTT_TerminalOut().
_WriteBlocking()
static unsigned _WriteBlocking (SEGGER_RTT_BUFFER_UP * pRing, const char * pBuffer, unsigned NumBytes) static
Definition at line 367 of file SEGGER_RTT.c.
References MIN, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by _PostTerminalSwitch(), SEGGER_RTT_SetTerminal(), SEGGER_RTT_TerminalOut(), SEGGER_RTT_WriteDownBufferNoLock(), and SEGGER_RTT_WriteNoLock().
_WriteNoCheck()
static void _WriteNoCheck (SEGGER_RTT_BUFFER_UP * pRing, const char * pData, unsigned NumBytes) static
Definition at line 429 of file SEGGER_RTT.c.
References SEGGER_RTT_BUFFER_UP::pBuffer, RTT__DMB, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_RTT_SetTerminal(), SEGGER_RTT_WriteDownBufferNoLock(), and SEGGER_RTT_WriteNoLock().
SEGGER_RTT_AllocDownBuffer()
int SEGGER_RTT_AllocDownBuffer (const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1559 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, NULL, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, SEGGER_RTT_BUFFER_DOWN::sName, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_AllocUpBuffer()
int SEGGER_RTT_AllocUpBuffer (const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1608 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, NULL, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, SEGGER_RTT_BUFFER_UP::sName, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_ConfigDownBuffer()
int SEGGER_RTT_ConfigDownBuffer (unsigned BufferIndex, const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1715 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, SEGGER_RTT_BUFFER_DOWN::sName, and SEGGER_RTT_BUFFER_DOWN::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_ConfigUpBuffer()
int SEGGER_RTT_ConfigUpBuffer (unsigned BufferIndex, const char * sName, void * pBuffer, unsigned BufferSize, unsigned Flags)
Definition at line 1663 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, SEGGER_RTT_BUFFER_UP::sName, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_SYSVIEW_Init().
SEGGER_RTT_GetAvailWriteSpace()
unsigned SEGGER_RTT_GetAvailWriteSpace (unsigned BufferIndex)
Definition at line 2051 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, SEGGER_RTT_CB::aUp, and SEGGER_RTT_UNCACHED_OFF.
SEGGER_RTT_GetBytesInBuffer()
unsigned SEGGER_RTT_GetBytesInBuffer (unsigned BufferIndex)
Definition at line 2072 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_GetKey()
int SEGGER_RTT_GetKey (void)
Definition at line 1430 of file SEGGER_RTT.c.
References SEGGER_RTT_Read().
Referenced by SEGGER_RTT_WaitKey().
SEGGER_RTT_HasData()
unsigned SEGGER_RTT_HasData (unsigned BufferIndex)
Definition at line 1509 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_HasDataUp()
unsigned SEGGER_RTT_HasDataUp (unsigned BufferIndex)
Definition at line 1530 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_HasKey()
int SEGGER_RTT_HasKey (void)
Definition at line 1481 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_BUFFER_DOWN::WrOff.
SEGGER_RTT_Init()
void SEGGER_RTT_Init (void)
Definition at line 1893 of file SEGGER_RTT.c.
References _DoInit().
SEGGER_RTT_PUT_BUFFER_SECTION() [1/2]
SEGGER_RTT_PUT_BUFFER_SECTION (SEGGER_RTT_BUFFER_ALIGN(static char _acDownBuffer[BUFFER_SIZE_DOWN]))
SEGGER_RTT_PUT_BUFFER_SECTION() [2/2]
SEGGER_RTT_PUT_BUFFER_SECTION (SEGGER_RTT_BUFFER_ALIGN(static char _acUpBuffer[BUFFER_SIZE_UP]))
SEGGER_RTT_PUT_CB_SECTION()
SEGGER_RTT_PUT_CB_SECTION (SEGGER_RTT_CB_ALIGN(SEGGER_RTT_CB _SEGGER_RTT))
SEGGER_RTT_PutChar()
unsigned SEGGER_RTT_PutChar (unsigned BufferIndex, char c)
Definition at line 1367 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_PutCharSkip()
unsigned SEGGER_RTT_PutCharSkip (unsigned BufferIndex, char c)
Definition at line 1308 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_LOCK, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_PutCharSkipNoLock()
unsigned SEGGER_RTT_PutCharSkipNoLock (unsigned BufferIndex, char c)
Definition at line 1258 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
SEGGER_RTT_Read()
unsigned SEGGER_RTT_Read (unsigned BufferIndex, void * pBuffer, unsigned BufferSize)
Definition at line 787 of file SEGGER_RTT.c.
References SEGGER_RTT_LOCK, SEGGER_RTT_ReadNoLock(), and SEGGER_RTT_UNLOCK.
Referenced by SEGGER_RTT_GetKey().
SEGGER_RTT_ReadNoLock()
unsigned SEGGER_RTT_ReadNoLock (unsigned BufferIndex, void * pData, unsigned BufferSize)
Definition at line 658 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, MIN, SEGGER_RTT_BUFFER_DOWN::pBuffer, SEGGER_RTT_BUFFER_DOWN::RdOff, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_DOWN::SizeOfBuffer, and SEGGER_RTT_BUFFER_DOWN::WrOff.
Referenced by _HandleIncomingPacket(), and SEGGER_RTT_Read().
SEGGER_RTT_ReadUpBuffer()
unsigned SEGGER_RTT_ReadUpBuffer (unsigned BufferIndex, void * pBuffer, unsigned BufferSize)
Definition at line 755 of file SEGGER_RTT.c.
References SEGGER_RTT_LOCK, SEGGER_RTT_ReadUpBufferNoLock(), and SEGGER_RTT_UNLOCK.
SEGGER_RTT_ReadUpBufferNoLock()
unsigned SEGGER_RTT_ReadUpBufferNoLock (unsigned BufferIndex, void * pData, unsigned BufferSize)
Definition at line 566 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, MIN, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by SEGGER_RTT_ReadUpBuffer().
SEGGER_RTT_SetFlagsDownBuffer()
int SEGGER_RTT_SetFlagsDownBuffer (unsigned BufferIndex, unsigned Flags)
Definition at line 1865 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_DOWN::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_SetFlagsUpBuffer()
int SEGGER_RTT_SetFlagsUpBuffer (unsigned BufferIndex, unsigned Flags)
Definition at line 1829 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_SetNameDownBuffer()
int SEGGER_RTT_SetNameDownBuffer (unsigned BufferIndex, const char * sName)
Definition at line 1793 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aDown, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_DOWN_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and SEGGER_RTT_BUFFER_DOWN::sName.
SEGGER_RTT_SetNameUpBuffer()
int SEGGER_RTT_SetNameUpBuffer (unsigned BufferIndex, const char * sName)
Definition at line 1758 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MAX_NUM_UP_BUFFERS, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and SEGGER_RTT_BUFFER_UP::sName.
SEGGER_RTT_SetTerminal()
int SEGGER_RTT_SetTerminal (unsigned char TerminalId)
Definition at line 1914 of file SEGGER_RTT.c.
References _ActiveTerminal, _aTerminalId, _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_MASK, SEGGER_RTT_UNCACHED_OFF, and SEGGER_RTT_UNLOCK.
SEGGER_RTT_TerminalOut()
int SEGGER_RTT_TerminalOut (unsigned char TerminalId, const char * s)
Definition at line 1963 of file SEGGER_RTT.c.
References _ActiveTerminal, _aTerminalId, _GetAvailWriteSpace(), _PostTerminalSwitch(), _SEGGER_RTT, _WriteBlocking(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, INIT, SEGGER_RTT_LOCK, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_MASK, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_UNLOCK, and STRLEN.
SEGGER_RTT_WaitKey()
int SEGGER_RTT_WaitKey (void)
Definition at line 1458 of file SEGGER_RTT.c.
References SEGGER_RTT_GetKey().
SEGGER_RTT_Write()
unsigned SEGGER_RTT_Write (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1198 of file SEGGER_RTT.c.
References INIT, SEGGER_RTT_LOCK, SEGGER_RTT_UNLOCK, and SEGGER_RTT_WriteNoLock().
Referenced by _StoreChar(), SEGGER_RTT_vprintf(), and SEGGER_RTT_WriteString().
SEGGER_RTT_WriteDownBuffer()
unsigned SEGGER_RTT_WriteDownBuffer (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1169 of file SEGGER_RTT.c.
References INIT, SEGGER_RTT_LOCK, SEGGER_RTT_UNLOCK, and SEGGER_RTT_WriteDownBufferNoLock().
SEGGER_RTT_WriteDownBufferNoLock()
unsigned SEGGER_RTT_WriteDownBufferNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1018 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aDown, SEGGER_RTT_BUFFER_UP::Flags, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, and SEGGER_RTT_UNCACHED_OFF.
Referenced by SEGGER_RTT_WriteDownBuffer().
SEGGER_RTT_WriteNoLock()
unsigned SEGGER_RTT_WriteNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 1093 of file SEGGER_RTT.c.
References _GetAvailWriteSpace(), _SEGGER_RTT, _WriteBlocking(), _WriteNoCheck(), SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::Flags, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL, SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_RTT_MODE_NO_BLOCK_TRIM, and SEGGER_RTT_UNCACHED_OFF.
Referenced by SEGGER_RTT_Write().
SEGGER_RTT_WriteSkipNoLock()
unsigned SEGGER_RTT_WriteSkipNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 927 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by _SendPacket(), _TrySendOverflowPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_RTT_WriteString()
unsigned SEGGER_RTT_WriteString (unsigned BufferIndex, const char * s)
Definition at line 1228 of file SEGGER_RTT.c.
References SEGGER_RTT_Write(), and STRLEN.
SEGGER_RTT_WriteWithOverwriteNoLock()
void SEGGER_RTT_WriteWithOverwriteNoLock (unsigned BufferIndex, const void * pBuffer, unsigned NumBytes)
Definition at line 826 of file SEGGER_RTT.c.
References _SEGGER_RTT, SEGGER_RTT_CB::aUp, SEGGER_RTT_BUFFER_UP::pBuffer, SEGGER_RTT_BUFFER_UP::RdOff, RTT__DMB, SEGGER_RTT_MEMCPY, SEGGER_RTT_UNCACHED_OFF, SEGGER_RTT_BUFFER_UP::SizeOfBuffer, and SEGGER_RTT_BUFFER_UP::WrOff.
Referenced by _SendPacket().
Variable Documentation
_ActiveTerminal
unsigned char _ActiveTerminal static
Definition at line 278 of file SEGGER_RTT.c.
Referenced by SEGGER_RTT_SetTerminal(), and SEGGER_RTT_TerminalOut().
_aTerminalId
const unsigned char _aTerminalId[16] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' } static
Definition at line 245 of file SEGGER_RTT.c.
Referenced by _PostTerminalSwitch(), SEGGER_RTT_SetTerminal(), and SEGGER_RTT_TerminalOut().