SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_SYSVIEW.h File Reference
SEGGER_SYSVIEW.h File Reference
#include "SEGGER.h"
#include "SEGGER_SYSVIEW_ConfDefaults.h"
Classes
struct SEGGER_SYSVIEW_TASKINFO
struct SEGGER_SYSVIEW_STACKINFO
struct SEGGER_SYSVIEW_DATA_SAMPLE
struct SEGGER_SYSVIEW_DATA_REGISTER
struct SEGGER_SYSVIEW_MODULE_STRUCT
struct SEGGER_SYSVIEW_OS_API
Macros
#define SEGGER_SYSVIEW_MAJOR 3
#define SEGGER_SYSVIEW_MINOR 32
#define SEGGER_SYSVIEW_REV 0
#define SEGGER_SYSVIEW_VERSION ((SEGGER_SYSVIEW_MAJOR * 10000) + (SEGGER_SYSVIEW_MINOR * 100) + SEGGER_SYSVIEW_REV)
#define SEGGER_SYSVIEW_INFO_SIZE 9
#define SEGGER_SYSVIEW_QUANTA_U32 5
#define SEGGER_SYSVIEW_LOG (0u)
#define SEGGER_SYSVIEW_WARNING (1u)
#define SEGGER_SYSVIEW_ERROR (2u)
#define SEGGER_SYSVIEW_FLAG_APPEND (1u << 6)
#define SEGGER_SYSVIEW_PREPARE_PACKET(p)
#define SYSVIEW_EVTID_NOP 0
#define SYSVIEW_EVTID_OVERFLOW 1
#define SYSVIEW_EVTID_ISR_ENTER 2
#define SYSVIEW_EVTID_ISR_EXIT 3
#define SYSVIEW_EVTID_TASK_START_EXEC 4
#define SYSVIEW_EVTID_TASK_STOP_EXEC 5
#define SYSVIEW_EVTID_TASK_START_READY 6
#define SYSVIEW_EVTID_TASK_STOP_READY 7
#define SYSVIEW_EVTID_TASK_CREATE 8
#define SYSVIEW_EVTID_TASK_INFO 9
#define SYSVIEW_EVTID_TRACE_START 10
#define SYSVIEW_EVTID_TRACE_STOP 11
#define SYSVIEW_EVTID_SYSTIME_CYCLES 12
#define SYSVIEW_EVTID_SYSTIME_US 13
#define SYSVIEW_EVTID_SYSDESC 14
#define SYSVIEW_EVTID_MARK_START 15
#define SYSVIEW_EVTID_MARK_STOP 16
#define SYSVIEW_EVTID_IDLE 17
#define SYSVIEW_EVTID_ISR_TO_SCHEDULER 18
#define SYSVIEW_EVTID_TIMER_ENTER 19
#define SYSVIEW_EVTID_TIMER_EXIT 20
#define SYSVIEW_EVTID_STACK_INFO 21
#define SYSVIEW_EVTID_MODULEDESC 22
#define SYSVIEW_EVTID_DATA_SAMPLE 23
#define SYSVIEW_EVTID_INIT 24
#define SYSVIEW_EVTID_NAME_RESOURCE 25
#define SYSVIEW_EVTID_PRINT_FORMATTED 26
#define SYSVIEW_EVTID_NUMMODULES 27
#define SYSVIEW_EVTID_END_CALL 28
#define SYSVIEW_EVTID_TASK_TERMINATE 29
#define SYSVIEW_EVTID_EX 31
#define SYSVIEW_EVTID_EX_MARK 0
#define SYSVIEW_EVTID_EX_NAME_MARKER 1
#define SYSVIEW_EVTID_EX_HEAP_DEFINE 2
#define SYSVIEW_EVTID_EX_HEAP_ALLOC 3
#define SYSVIEW_EVTID_EX_HEAP_ALLOC_EX 4
#define SYSVIEW_EVTID_EX_HEAP_FREE 5
#define SYSVIEW_EVTID_EX_REGISTER_DATA 6
#define SYSVIEW_EVTMASK_NOP (1 << SYSVIEW_EVTID_NOP)
#define SYSVIEW_EVTMASK_OVERFLOW (1 << SYSVIEW_EVTID_OVERFLOW)
#define SYSVIEW_EVTMASK_ISR_ENTER (1 << SYSVIEW_EVTID_ISR_ENTER)
#define SYSVIEW_EVTMASK_ISR_EXIT (1 << SYSVIEW_EVTID_ISR_EXIT)
#define SYSVIEW_EVTMASK_TASK_START_EXEC (1 << SYSVIEW_EVTID_TASK_START_EXEC)
#define SYSVIEW_EVTMASK_TASK_STOP_EXEC (1 << SYSVIEW_EVTID_TASK_STOP_EXEC)
#define SYSVIEW_EVTMASK_TASK_START_READY (1 << SYSVIEW_EVTID_TASK_START_READY)
#define SYSVIEW_EVTMASK_TASK_STOP_READY (1 << SYSVIEW_EVTID_TASK_STOP_READY)
#define SYSVIEW_EVTMASK_TASK_CREATE (1 << SYSVIEW_EVTID_TASK_CREATE)
#define SYSVIEW_EVTMASK_TASK_INFO (1 << SYSVIEW_EVTID_TASK_INFO)
#define SYSVIEW_EVTMASK_TRACE_START (1 << SYSVIEW_EVTID_TRACE_START)
#define SYSVIEW_EVTMASK_TRACE_STOP (1 << SYSVIEW_EVTID_TRACE_STOP)
#define SYSVIEW_EVTMASK_SYSTIME_CYCLES (1 << SYSVIEW_EVTID_SYSTIME_CYCLES)
#define SYSVIEW_EVTMASK_SYSTIME_US (1 << SYSVIEW_EVTID_SYSTIME_US)
#define SYSVIEW_EVTMASK_SYSDESC (1 << SYSVIEW_EVTID_SYSDESC)
#define SYSVIEW_EVTMASK_USER_START (1 << SYSVIEW_EVTID_USER_START)
#define SYSVIEW_EVTMASK_USER_STOP (1 << SYSVIEW_EVTID_USER_STOP)
#define SYSVIEW_EVTMASK_IDLE (1 << SYSVIEW_EVTID_IDLE)
#define SYSVIEW_EVTMASK_ISR_TO_SCHEDULER (1 << SYSVIEW_EVTID_ISR_TO_SCHEDULER)
#define SYSVIEW_EVTMASK_TIMER_ENTER (1 << SYSVIEW_EVTID_TIMER_ENTER)
#define SYSVIEW_EVTMASK_TIMER_EXIT (1 << SYSVIEW_EVTID_TIMER_EXIT)
#define SYSVIEW_EVTMASK_STACK_INFO (1 << SYSVIEW_EVTID_STACK_INFO)
#define SYSVIEW_EVTMASK_MODULEDESC (1 << SYSVIEW_EVTID_MODULEDESC)
#define SYSVIEW_EVTMASK_DATA_SAMPLE (1 << SYSVIEW_EVTID_DATA_SAMPLE)
#define SYSVIEW_EVTMASK_INIT (1 << SYSVIEW_EVTID_INIT)
#define SYSVIEW_EVTMASK_NAME_RESOURCE (1 << SYSVIEW_EVTID_NAME_RESOURCE)
#define SYSVIEW_EVTMASK_PRINT_FORMATTED (1 << SYSVIEW_EVTID_PRINT_FORMATTED)
#define SYSVIEW_EVTMASK_NUMMODULES (1 << SYSVIEW_EVTID_NUMMODULES)
#define SYSVIEW_EVTMASK_END_CALL (1 << SYSVIEW_EVTID_END_CALL)
#define SYSVIEW_EVTMASK_TASK_TERMINATE (1 << SYSVIEW_EVTID_TASK_TERMINATE)
#define SYSVIEW_EVTMASK_EX (1 << SYSVIEW_EVTID_EX)
#define SYSVIEW_EVTMASK_ALL_INTERRUPTS
#define SYSVIEW_EVTMASK_ALL_TASKS
#define EXTERN
#define SEGGER_SYSVIEW_OnUserStart SEGGER_SYSVIEW_MarkStart
#define SEGGER_SYSVIEW_OnUserStop SEGGER_SYSVIEW_MarkStop
Typedefs
typedef struct SEGGER_SYSVIEW_MODULE_STRUCT SEGGER_SYSVIEW_MODULE
typedef void SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC(void)
Enumerations
enum SEGGER_SYSVIEW_DATA_TYPE { SEGGER_SYSVIEW_TYPE_U32 = 0 , SEGGER_SYSVIEW_TYPE_I32 = 1 , SEGGER_SYSVIEW_TYPE_FLOAT = 2 }
Functions
void SEGGER_SYSVIEW_Init (U32 SysFreq, U32 CPUFreq, const SEGGER_SYSVIEW_OS_API *pOSAPI, SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC pfSendSysDesc)
void SEGGER_SYSVIEW_SetRAMBase (U32 RAMBaseAddress)
void SEGGER_SYSVIEW_Start (void)
void SEGGER_SYSVIEW_Stop (void)
void SEGGER_SYSVIEW_GetSysDesc (void)
void SEGGER_SYSVIEW_SendTaskList (void)
void SEGGER_SYSVIEW_SendTaskInfo (const SEGGER_SYSVIEW_TASKINFO *pInfo)
void SEGGER_SYSVIEW_SendStackInfo (const SEGGER_SYSVIEW_STACKINFO *pInfo)
void SEGGER_SYSVIEW_SendSysDesc (const char *sSysDesc)
int SEGGER_SYSVIEW_IsStarted (void)
int SEGGER_SYSVIEW_GetChannelID (void)
void SEGGER_SYSVIEW_SampleData (const SEGGER_SYSVIEW_DATA_SAMPLE *pInfo)
void SEGGER_SYSVIEW_RecordVoid (unsigned int EventId)
void SEGGER_SYSVIEW_RecordU32 (unsigned int EventId, U32 Para0)
void SEGGER_SYSVIEW_RecordU32x2 (unsigned int EventId, U32 Para0, U32 Para1)
void SEGGER_SYSVIEW_RecordU32x3 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2)
void SEGGER_SYSVIEW_RecordU32x4 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3)
void SEGGER_SYSVIEW_RecordU32x5 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4)
void SEGGER_SYSVIEW_RecordU32x6 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5)
void SEGGER_SYSVIEW_RecordU32x7 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6)
void SEGGER_SYSVIEW_RecordU32x8 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7)
void SEGGER_SYSVIEW_RecordU32x9 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8)
void SEGGER_SYSVIEW_RecordU32x10 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8, U32 Para9)
void SEGGER_SYSVIEW_RecordString (unsigned int EventId, const char *pString)
void SEGGER_SYSVIEW_RecordSystime (void)
void SEGGER_SYSVIEW_RecordEnterISR (void)
void SEGGER_SYSVIEW_RecordExitISR (void)
void SEGGER_SYSVIEW_RecordExitISRToScheduler (void)
void SEGGER_SYSVIEW_RecordEnterTimer (U32 TimerId)
void SEGGER_SYSVIEW_RecordExitTimer (void)
void SEGGER_SYSVIEW_RecordEndCall (unsigned int EventID)
void SEGGER_SYSVIEW_RecordEndCallU32 (unsigned int EventID, U32 Para0)
void SEGGER_SYSVIEW_OnIdle (void)
void SEGGER_SYSVIEW_OnTaskCreate (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskTerminate (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStartExec (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStopExec (void)
void SEGGER_SYSVIEW_OnTaskStartReady (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStopReady (U32 TaskId, unsigned int Cause)
void SEGGER_SYSVIEW_MarkStart (unsigned int MarkerId)
void SEGGER_SYSVIEW_MarkStop (unsigned int MarkerId)
void SEGGER_SYSVIEW_Mark (unsigned int MarkerId)
void SEGGER_SYSVIEW_NameMarker (unsigned int MarkerId, const char *sName)
void SEGGER_SYSVIEW_HeapDefine (void *pHeap, void *pBase, unsigned int HeapSize, unsigned int MetadataSize)
void SEGGER_SYSVIEW_HeapAlloc (void *pHeap, void *pUserData, unsigned int UserDataLen)
void SEGGER_SYSVIEW_HeapAllocEx (void *pHeap, void *pUserData, unsigned int UserDataLen, unsigned int Tag)
void SEGGER_SYSVIEW_HeapFree (void *pHeap, void *pUserData)
void SEGGER_SYSVIEW_NameResource (U32 ResourceId, const char *sName)
void SEGGER_SYSVIEW_RegisterData (SEGGER_SYSVIEW_DATA_REGISTER *pInfo)
int SEGGER_SYSVIEW_SendPacket (U8 *pPacket, U8 *pPayloadEnd, unsigned int EventId)
U8 * SEGGER_SYSVIEW_EncodeU32 (U8 *pPayload, U32 Value)
U8 * SEGGER_SYSVIEW_EncodeData (U8 *pPayload, const char *pSrc, unsigned int Len)
U8 * SEGGER_SYSVIEW_EncodeString (U8 *pPayload, const char *s, unsigned int MaxLen)
U8 * SEGGER_SYSVIEW_EncodeId (U8 *pPayload, U32 Id)
U32 SEGGER_SYSVIEW_ShrinkId (U32 Id)
void SEGGER_SYSVIEW_RegisterModule (SEGGER_SYSVIEW_MODULE *pModule)
void SEGGER_SYSVIEW_RecordModuleDescription (const SEGGER_SYSVIEW_MODULE *pModule, const char *sDescription)
void SEGGER_SYSVIEW_SendModule (U8 ModuleId)
void SEGGER_SYSVIEW_SendModuleDescription (void)
void SEGGER_SYSVIEW_SendNumModules (void)
void SEGGER_SYSVIEW_PrintfHostEx (const char *s, U32 Options,...)
void SEGGER_SYSVIEW_VPrintfHostEx (const char *s, U32 Options, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfTargetEx (const char *s, U32 Options,...)
void SEGGER_SYSVIEW_VPrintfTargetEx (const char *s, U32 Options, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfHost (const char *s,...)
void SEGGER_SYSVIEW_VPrintfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfTarget (const char *s,...)
void SEGGER_SYSVIEW_VPrintfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_WarnfHost (const char *s,...)
void SEGGER_SYSVIEW_VWarnfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_WarnfTarget (const char *s,...)
void SEGGER_SYSVIEW_VWarnfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_ErrorfHost (const char *s,...)
void SEGGER_SYSVIEW_VErrorfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_ErrorfTarget (const char *s,...)
void SEGGER_SYSVIEW_VErrorfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_Print (const char *s)
void SEGGER_SYSVIEW_Warn (const char *s)
void SEGGER_SYSVIEW_Error (const char *s)
void SEGGER_SYSVIEW_EnableEvents (U32 EnableMask)
void SEGGER_SYSVIEW_DisableEvents (U32 DisableMask)
void SEGGER_SYSVIEW_Conf (void)
U32 SEGGER_SYSVIEW_X_GetTimestamp (void)
U32 SEGGER_SYSVIEW_X_GetInterruptId (void)
void SEGGER_SYSVIEW_X_StartComm (void)
void SEGGER_SYSVIEW_X_OnEventRecorded (unsigned NumBytes)
Variables
EXTERN unsigned int SEGGER_SYSVIEW_TickCnt
EXTERN unsigned int SEGGER_SYSVIEW_InterruptId
Macro Definition Documentation
EXTERN
#define EXTERN
Definition at line 262 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_ERROR
#define SEGGER_SYSVIEW_ERROR (2u)
Definition at line 89 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_ErrorfHost(), SEGGER_SYSVIEW_ErrorfTarget(), SEGGER_SYSVIEW_VErrorfHost(), and SEGGER_SYSVIEW_VErrorfTarget().
SEGGER_SYSVIEW_FLAG_APPEND
#define SEGGER_SYSVIEW_FLAG_APPEND (1u << 6)
Definition at line 90 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_INFO_SIZE
#define SEGGER_SYSVIEW_INFO_SIZE 9
Definition at line 84 of file SEGGER_SYSVIEW.h.
Referenced by _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnIdle(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopExec(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitISR(), SEGGER_SYSVIEW_RecordExitISRToScheduler(), SEGGER_SYSVIEW_RecordExitTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordString(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendSysDesc(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), SEGGER_SYSVIEW_Stop(), and SEGGER_SYSVIEW_Warn().
SEGGER_SYSVIEW_LOG
#define SEGGER_SYSVIEW_LOG (0u)
Definition at line 87 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_PrintfHost(), SEGGER_SYSVIEW_PrintfTarget(), SEGGER_SYSVIEW_VPrintfHost(), and SEGGER_SYSVIEW_VPrintfTarget().
SEGGER_SYSVIEW_MAJOR
#define SEGGER_SYSVIEW_MAJOR 3
Definition at line 79 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_MINOR
#define SEGGER_SYSVIEW_MINOR 32
Definition at line 80 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_OnUserStart
#define SEGGER_SYSVIEW_OnUserStart SEGGER_SYSVIEW_MarkStart
Definition at line 421 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_OnUserStop
#define SEGGER_SYSVIEW_OnUserStop SEGGER_SYSVIEW_MarkStop
Definition at line 422 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_PREPARE_PACKET
#define SEGGER_SYSVIEW_PREPARE_PACKET (p)
Value:
(p) + 4
Definition at line 92 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_QUANTA_U32
#define SEGGER_SYSVIEW_QUANTA_U32 5
Definition at line 85 of file SEGGER_SYSVIEW.h.
Referenced by _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), and SEGGER_SYSVIEW_Warn().
SEGGER_SYSVIEW_REV
#define SEGGER_SYSVIEW_REV 0
Definition at line 81 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_VERSION
#define SEGGER_SYSVIEW_VERSION ((SEGGER_SYSVIEW_MAJOR * 10000) + (SEGGER_SYSVIEW_MINOR * 100) + SEGGER_SYSVIEW_REV)
Definition at line 82 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_WARNING
#define SEGGER_SYSVIEW_WARNING (1u)
Definition at line 88 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_VWarnfHost(), SEGGER_SYSVIEW_VWarnfTarget(), SEGGER_SYSVIEW_Warn(), SEGGER_SYSVIEW_WarnfHost(), and SEGGER_SYSVIEW_WarnfTarget().
SYSVIEW_EVTID_DATA_SAMPLE
#define SYSVIEW_EVTID_DATA_SAMPLE 23
Definition at line 119 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_SampleData().
SYSVIEW_EVTID_END_CALL
#define SYSVIEW_EVTID_END_CALL 28
Definition at line 124 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordEndCall(), and SEGGER_SYSVIEW_RecordEndCallU32().
SYSVIEW_EVTID_EX
#define SYSVIEW_EVTID_EX 31
Definition at line 127 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_NameMarker(), and SEGGER_SYSVIEW_RegisterData().
SYSVIEW_EVTID_EX_HEAP_ALLOC
#define SYSVIEW_EVTID_EX_HEAP_ALLOC 3
Definition at line 134 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_HeapAlloc().
SYSVIEW_EVTID_EX_HEAP_ALLOC_EX
#define SYSVIEW_EVTID_EX_HEAP_ALLOC_EX 4
Definition at line 135 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_HeapAllocEx().
SYSVIEW_EVTID_EX_HEAP_DEFINE
#define SYSVIEW_EVTID_EX_HEAP_DEFINE 2
Definition at line 133 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_HeapDefine().
SYSVIEW_EVTID_EX_HEAP_FREE
#define SYSVIEW_EVTID_EX_HEAP_FREE 5
Definition at line 136 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_HeapFree().
SYSVIEW_EVTID_EX_MARK
#define SYSVIEW_EVTID_EX_MARK 0
Definition at line 131 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_Mark().
SYSVIEW_EVTID_EX_NAME_MARKER
#define SYSVIEW_EVTID_EX_NAME_MARKER 1
Definition at line 132 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_NameMarker().
SYSVIEW_EVTID_EX_REGISTER_DATA
#define SYSVIEW_EVTID_EX_REGISTER_DATA 6
Definition at line 137 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RegisterData().
SYSVIEW_EVTID_IDLE
#define SYSVIEW_EVTID_IDLE 17
Definition at line 113 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnIdle().
SYSVIEW_EVTID_INIT
#define SYSVIEW_EVTID_INIT 24
Definition at line 120 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_GetSysDesc(), and SEGGER_SYSVIEW_Start().
SYSVIEW_EVTID_ISR_ENTER
#define SYSVIEW_EVTID_ISR_ENTER 2
Definition at line 98 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordEnterISR().
SYSVIEW_EVTID_ISR_EXIT
#define SYSVIEW_EVTID_ISR_EXIT 3
Definition at line 99 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordExitISR().
SYSVIEW_EVTID_ISR_TO_SCHEDULER
#define SYSVIEW_EVTID_ISR_TO_SCHEDULER 18
Definition at line 114 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordExitISRToScheduler().
SYSVIEW_EVTID_MARK_START
#define SYSVIEW_EVTID_MARK_START 15
Definition at line 111 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_MarkStart().
SYSVIEW_EVTID_MARK_STOP
#define SYSVIEW_EVTID_MARK_STOP 16
Definition at line 112 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_MarkStop().
SYSVIEW_EVTID_MODULEDESC
#define SYSVIEW_EVTID_MODULEDESC 22
Definition at line 118 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordModuleDescription(), and SEGGER_SYSVIEW_SendModule().
SYSVIEW_EVTID_NAME_RESOURCE
#define SYSVIEW_EVTID_NAME_RESOURCE 25
Definition at line 121 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_NameResource().
SYSVIEW_EVTID_NOP
#define SYSVIEW_EVTID_NOP 0
Definition at line 96 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTID_NUMMODULES
#define SYSVIEW_EVTID_NUMMODULES 27
Definition at line 123 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_SendNumModules().
SYSVIEW_EVTID_OVERFLOW
#define SYSVIEW_EVTID_OVERFLOW 1
Definition at line 97 of file SEGGER_SYSVIEW.h.
Referenced by _TrySendOverflowPacket().
SYSVIEW_EVTID_PRINT_FORMATTED
#define SYSVIEW_EVTID_PRINT_FORMATTED 26
Definition at line 122 of file SEGGER_SYSVIEW.h.
Referenced by _StoreChar(), _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_Print(), and SEGGER_SYSVIEW_Warn().
SYSVIEW_EVTID_STACK_INFO
#define SYSVIEW_EVTID_STACK_INFO 21
Definition at line 117 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_SendTaskInfo().
SYSVIEW_EVTID_SYSDESC
#define SYSVIEW_EVTID_SYSDESC 14
Definition at line 110 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_SendSysDesc().
SYSVIEW_EVTID_SYSTIME_CYCLES
#define SYSVIEW_EVTID_SYSTIME_CYCLES 12
Definition at line 108 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SYSVIEW_EVTID_SYSTIME_US
#define SYSVIEW_EVTID_SYSTIME_US 13
Definition at line 109 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SYSVIEW_EVTID_TASK_CREATE
#define SYSVIEW_EVTID_TASK_CREATE 8
Definition at line 104 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskCreate().
SYSVIEW_EVTID_TASK_INFO
#define SYSVIEW_EVTID_TASK_INFO 9
Definition at line 105 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_SendTaskInfo().
SYSVIEW_EVTID_TASK_START_EXEC
#define SYSVIEW_EVTID_TASK_START_EXEC 4
Definition at line 100 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskStartExec().
SYSVIEW_EVTID_TASK_START_READY
#define SYSVIEW_EVTID_TASK_START_READY 6
Definition at line 102 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskStartReady().
SYSVIEW_EVTID_TASK_STOP_EXEC
#define SYSVIEW_EVTID_TASK_STOP_EXEC 5
Definition at line 101 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskStopExec().
SYSVIEW_EVTID_TASK_STOP_READY
#define SYSVIEW_EVTID_TASK_STOP_READY 7
Definition at line 103 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskStopReady().
SYSVIEW_EVTID_TASK_TERMINATE
#define SYSVIEW_EVTID_TASK_TERMINATE 29
Definition at line 125 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_OnTaskTerminate().
SYSVIEW_EVTID_TIMER_ENTER
#define SYSVIEW_EVTID_TIMER_ENTER 19
Definition at line 115 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordEnterTimer().
SYSVIEW_EVTID_TIMER_EXIT
#define SYSVIEW_EVTID_TIMER_EXIT 20
Definition at line 116 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_RecordExitTimer().
SYSVIEW_EVTID_TRACE_START
#define SYSVIEW_EVTID_TRACE_START 10
Definition at line 106 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_Start().
SYSVIEW_EVTID_TRACE_STOP
#define SYSVIEW_EVTID_TRACE_STOP 11
Definition at line 107 of file SEGGER_SYSVIEW.h.
Referenced by SEGGER_SYSVIEW_Stop().
SYSVIEW_EVTMASK_ALL_INTERRUPTS
#define SYSVIEW_EVTMASK_ALL_INTERRUPTS
Value:
                                            ( SYSVIEW_EVTMASK_ISR_ENTER           \
                                            | SYSVIEW_EVTMASK_ISR_EXIT            \
                                            | SYSVIEW_EVTMASK_ISR_TO_SCHEDULER)
Definition at line 174 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_ALL_TASKS
#define SYSVIEW_EVTMASK_ALL_TASKS
Value:
                                            ( SYSVIEW_EVTMASK_TASK_START_EXEC     \
                                            | SYSVIEW_EVTMASK_TASK_STOP_EXEC      \
                                            | SYSVIEW_EVTMASK_TASK_START_READY    \
                                            | SYSVIEW_EVTMASK_TASK_STOP_READY     \
                                            | SYSVIEW_EVTMASK_TASK_CREATE         \
                                            | SYSVIEW_EVTMASK_TASK_INFO           \
                                            | SYSVIEW_EVTMASK_STACK_INFO          \
                                            | SYSVIEW_EVTMASK_TASK_TERMINATE)
Definition at line 177 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_DATA_SAMPLE
#define SYSVIEW_EVTMASK_DATA_SAMPLE (1 << SYSVIEW_EVTID_DATA_SAMPLE)
Definition at line 164 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_END_CALL
#define SYSVIEW_EVTMASK_END_CALL (1 << SYSVIEW_EVTID_END_CALL)
Definition at line 169 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_EX
#define SYSVIEW_EVTMASK_EX (1 << SYSVIEW_EVTID_EX)
Definition at line 172 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_IDLE
#define SYSVIEW_EVTMASK_IDLE (1 << SYSVIEW_EVTID_IDLE)
Definition at line 158 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_INIT
#define SYSVIEW_EVTMASK_INIT (1 << SYSVIEW_EVTID_INIT)
Definition at line 165 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_ISR_ENTER
#define SYSVIEW_EVTMASK_ISR_ENTER (1 << SYSVIEW_EVTID_ISR_ENTER)
Definition at line 143 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_ISR_EXIT
#define SYSVIEW_EVTMASK_ISR_EXIT (1 << SYSVIEW_EVTID_ISR_EXIT)
Definition at line 144 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_ISR_TO_SCHEDULER
#define SYSVIEW_EVTMASK_ISR_TO_SCHEDULER (1 << SYSVIEW_EVTID_ISR_TO_SCHEDULER)
Definition at line 159 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_MODULEDESC
#define SYSVIEW_EVTMASK_MODULEDESC (1 << SYSVIEW_EVTID_MODULEDESC)
Definition at line 163 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_NAME_RESOURCE
#define SYSVIEW_EVTMASK_NAME_RESOURCE (1 << SYSVIEW_EVTID_NAME_RESOURCE)
Definition at line 166 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_NOP
#define SYSVIEW_EVTMASK_NOP (1 << SYSVIEW_EVTID_NOP)
Definition at line 141 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_NUMMODULES
#define SYSVIEW_EVTMASK_NUMMODULES (1 << SYSVIEW_EVTID_NUMMODULES)
Definition at line 168 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_OVERFLOW
#define SYSVIEW_EVTMASK_OVERFLOW (1 << SYSVIEW_EVTID_OVERFLOW)
Definition at line 142 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_PRINT_FORMATTED
#define SYSVIEW_EVTMASK_PRINT_FORMATTED (1 << SYSVIEW_EVTID_PRINT_FORMATTED)
Definition at line 167 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_STACK_INFO
#define SYSVIEW_EVTMASK_STACK_INFO (1 << SYSVIEW_EVTID_STACK_INFO)
Definition at line 162 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_SYSDESC
#define SYSVIEW_EVTMASK_SYSDESC (1 << SYSVIEW_EVTID_SYSDESC)
Definition at line 155 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_SYSTIME_CYCLES
#define SYSVIEW_EVTMASK_SYSTIME_CYCLES (1 << SYSVIEW_EVTID_SYSTIME_CYCLES)
Definition at line 153 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_SYSTIME_US
#define SYSVIEW_EVTMASK_SYSTIME_US (1 << SYSVIEW_EVTID_SYSTIME_US)
Definition at line 154 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_CREATE
#define SYSVIEW_EVTMASK_TASK_CREATE (1 << SYSVIEW_EVTID_TASK_CREATE)
Definition at line 149 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_INFO
#define SYSVIEW_EVTMASK_TASK_INFO (1 << SYSVIEW_EVTID_TASK_INFO)
Definition at line 150 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_START_EXEC
#define SYSVIEW_EVTMASK_TASK_START_EXEC (1 << SYSVIEW_EVTID_TASK_START_EXEC)
Definition at line 145 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_START_READY
#define SYSVIEW_EVTMASK_TASK_START_READY (1 << SYSVIEW_EVTID_TASK_START_READY)
Definition at line 147 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_STOP_EXEC
#define SYSVIEW_EVTMASK_TASK_STOP_EXEC (1 << SYSVIEW_EVTID_TASK_STOP_EXEC)
Definition at line 146 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_STOP_READY
#define SYSVIEW_EVTMASK_TASK_STOP_READY (1 << SYSVIEW_EVTID_TASK_STOP_READY)
Definition at line 148 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TASK_TERMINATE
#define SYSVIEW_EVTMASK_TASK_TERMINATE (1 << SYSVIEW_EVTID_TASK_TERMINATE)
Definition at line 170 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TIMER_ENTER
#define SYSVIEW_EVTMASK_TIMER_ENTER (1 << SYSVIEW_EVTID_TIMER_ENTER)
Definition at line 160 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TIMER_EXIT
#define SYSVIEW_EVTMASK_TIMER_EXIT (1 << SYSVIEW_EVTID_TIMER_EXIT)
Definition at line 161 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TRACE_START
#define SYSVIEW_EVTMASK_TRACE_START (1 << SYSVIEW_EVTID_TRACE_START)
Definition at line 151 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_TRACE_STOP
#define SYSVIEW_EVTMASK_TRACE_STOP (1 << SYSVIEW_EVTID_TRACE_STOP)
Definition at line 152 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_USER_START
#define SYSVIEW_EVTMASK_USER_START (1 << SYSVIEW_EVTID_USER_START)
Definition at line 156 of file SEGGER_SYSVIEW.h.
SYSVIEW_EVTMASK_USER_STOP
#define SYSVIEW_EVTMASK_USER_STOP (1 << SYSVIEW_EVTID_USER_STOP)
Definition at line 157 of file SEGGER_SYSVIEW.h.
Typedef Documentation
SEGGER_SYSVIEW_MODULE
typedef struct SEGGER_SYSVIEW_MODULE_STRUCT SEGGER_SYSVIEW_MODULE
Definition at line 235 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC
typedef void SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC(void)
Definition at line 245 of file SEGGER_SYSVIEW.h.
Enumeration Type Documentation
SEGGER_SYSVIEW_DATA_TYPE
enum SEGGER_SYSVIEW_DATA_TYPE
Enumerator
SEGGER_SYSVIEW_TYPE_U32
SEGGER_SYSVIEW_TYPE_I32
SEGGER_SYSVIEW_TYPE_FLOAT
Definition at line 218 of file SEGGER_SYSVIEW.h.
Function Documentation
SEGGER_SYSVIEW_Conf()
void SEGGER_SYSVIEW_Conf (void)
Definition at line 88 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References _cbSendSystemDesc(), _NoOSAPI, CYCCNTENA_BIT, DEMCR, DWT_CTRL, NOCYCCNT_BIT, SEGGER_SYSVIEW_Init(), SEGGER_SYSVIEW_SetRAMBase(), SYSVIEW_CPU_FREQ, SYSVIEW_RAM_BASE, SYSVIEW_TIMESTAMP_FREQ, and TRACEENA_BIT.
Referenced by init_SeggerModules().
SEGGER_SYSVIEW_DisableEvents()
void SEGGER_SYSVIEW_DisableEvents (U32 DisableMask)
Definition at line 3587 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::DisabledEvents.
SEGGER_SYSVIEW_EnableEvents()
void SEGGER_SYSVIEW_EnableEvents (U32 EnableMask)
Definition at line 3573 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::DisabledEvents.
SEGGER_SYSVIEW_EncodeData()
U8 * SEGGER_SYSVIEW_EncodeData (U8 * pPayload, const char * pSrc, unsigned int Len)
Definition at line 2854 of file SEGGER_SYSVIEW.c.
References _EncodeData().
SEGGER_SYSVIEW_EncodeId()
U8 * SEGGER_SYSVIEW_EncodeId (U8 * pPayload, U32 Id)
Definition at line 2882 of file SEGGER_SYSVIEW.c.
References ENCODE_U32, and SHRINK_ID.
SEGGER_SYSVIEW_EncodeString()
U8 * SEGGER_SYSVIEW_EncodeString (U8 * pPayload, const char * s, unsigned int MaxLen)
Definition at line 2828 of file SEGGER_SYSVIEW.c.
References _EncodeStr().
SEGGER_SYSVIEW_EncodeU32()
U8 * SEGGER_SYSVIEW_EncodeU32 (U8 * pPayload, U32 Value)
Definition at line 2801 of file SEGGER_SYSVIEW.c.
References ENCODE_U32.
SEGGER_SYSVIEW_Error()
void SEGGER_SYSVIEW_Error (const char * s)
Definition at line 3551 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ERROR, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
SEGGER_SYSVIEW_ErrorfHost()
void SEGGER_SYSVIEW_ErrorfHost (const char * s, ...)
Definition at line 3301 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_ErrorfTarget()
void SEGGER_SYSVIEW_ErrorfTarget (const char * s, ...)
Definition at line 3472 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_GetChannelID()
int SEGGER_SYSVIEW_GetChannelID (void)
Definition at line 1933 of file SEGGER_SYSVIEW.c.
References CHANNEL_ID_UP.
SEGGER_SYSVIEW_GetSysDesc()
void SEGGER_SYSVIEW_GetSysDesc (void)
Definition at line 1945 of file SEGGER_SYSVIEW.c.
References _SendPacket(), _SYSVIEW_Globals, SEGGER_SYSVIEW_GLOBALS::CPUFreq, ENCODE_U32, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_GLOBALS::SysFreq, SYSVIEW_EVTID_INIT, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_HeapAlloc()
void SEGGER_SYSVIEW_HeapAlloc (void * pHeap, void * pUserData, unsigned int UserDataLen)
Definition at line 2662 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_ALLOC, U32, and U8.
SEGGER_SYSVIEW_HeapAllocEx()
void SEGGER_SYSVIEW_HeapAllocEx (void * pHeap, void * pUserData, unsigned int UserDataLen, unsigned int Tag)
Definition at line 2714 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_ALLOC_EX, U32, and U8.
SEGGER_SYSVIEW_HeapDefine()
void SEGGER_SYSVIEW_HeapDefine (void * pHeap, void * pBase, unsigned int HeapSize, unsigned int MetadataSize)
Definition at line 2613 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_DEFINE, U32, and U8.
SEGGER_SYSVIEW_HeapFree()
void SEGGER_SYSVIEW_HeapFree (void * pHeap, void * pUserData)
Definition at line 2744 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_FREE, U32, and U8.
SEGGER_SYSVIEW_Init()
void SEGGER_SYSVIEW_Init (U32 SysFreq, U32 CPUFreq, const SEGGER_SYSVIEW_OS_API * pOSAPI, SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC pfSendSysDesc)
Definition at line 1431 of file SEGGER_SYSVIEW.c.
References _DownBuffer, _SYSVIEW_Globals, _UpBuffer, SEGGER_SYSVIEW_GLOBALS::CPUFreq, SEGGER_SYSVIEW_GLOBALS::DownChannel, SEGGER_SYSVIEW_GLOBALS::EnableState, SEGGER_SYSVIEW_GLOBALS::LastTxTimeStamp, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::pOSAPI, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_ConfigUpBuffer(), SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_ID_BASE, SEGGER_SYSVIEW_RTT_CHANNEL, SEGGER_SYSVIEW_GLOBALS::SysFreq, U8, and SEGGER_SYSVIEW_GLOBALS::UpChannel.
Referenced by SEGGER_SYSVIEW_Conf().
SEGGER_SYSVIEW_IsStarted()
int SEGGER_SYSVIEW_IsStarted (void)
Definition at line 3602 of file SEGGER_SYSVIEW.c.
References _HandleIncomingPacket(), _SYSVIEW_Globals, CHANNEL_ID_DOWN, SEGGER_SYSVIEW_GLOBALS::EnableState, SEGGER_SYSVIEW_GLOBALS::RecursionCnt, and SEGGER_RTT_HASDATA.
SEGGER_SYSVIEW_Mark()
void SEGGER_SYSVIEW_Mark (unsigned int MarkerId)
Definition at line 2460 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_MARK, and U8.
SEGGER_SYSVIEW_MarkStart()
void SEGGER_SYSVIEW_MarkStart (unsigned int MarkerId)
SEGGER_SYSVIEW_MarkStop()
void SEGGER_SYSVIEW_MarkStop (unsigned int MarkerId)
SEGGER_SYSVIEW_NameMarker()
void SEGGER_SYSVIEW_NameMarker (unsigned int MarkerId, const char * sName)
Definition at line 2487 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_NAME_MARKER, and U8.
SEGGER_SYSVIEW_NameResource()
void SEGGER_SYSVIEW_NameResource (U32 ResourceId, const char * sName)
Definition at line 2515 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_NAME_RESOURCE, and U8.
SEGGER_SYSVIEW_OnIdle()
void SEGGER_SYSVIEW_OnIdle (void)
Definition at line 2266 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_IDLE, and U8.
SEGGER_SYSVIEW_OnTaskCreate()
void SEGGER_SYSVIEW_OnTaskCreate (U32 TaskId)
Definition at line 2285 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_CREATE, and U8.
Referenced by SYSVIEW_AddTask().
SEGGER_SYSVIEW_OnTaskStartExec()
void SEGGER_SYSVIEW_OnTaskStartExec (U32 TaskId)
Definition at line 2334 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_START_EXEC, and U8.
SEGGER_SYSVIEW_OnTaskStartReady()
void SEGGER_SYSVIEW_OnTaskStartReady (U32 TaskId)
Definition at line 2372 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_START_READY, and U8.
SEGGER_SYSVIEW_OnTaskStopExec()
void SEGGER_SYSVIEW_OnTaskStopExec (void)
Definition at line 2354 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TASK_STOP_EXEC, and U8.
SEGGER_SYSVIEW_OnTaskStopReady()
void SEGGER_SYSVIEW_OnTaskStopReady (U32 TaskId, unsigned int Cause)
Definition at line 2395 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_STOP_READY, and U8.
SEGGER_SYSVIEW_OnTaskTerminate()
void SEGGER_SYSVIEW_OnTaskTerminate (U32 TaskId)
Definition at line 2310 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_TERMINATE, and U8.
SEGGER_SYSVIEW_Print()
void SEGGER_SYSVIEW_Print (const char * s)
Definition at line 3507 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_LOG, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
Referenced by init_OLED(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_PrintfHost()
void SEGGER_SYSVIEW_PrintfHost (const char * s, ...)
Definition at line 3168 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_PrintfHostEx()
void SEGGER_SYSVIEW_PrintfHostEx (const char * s, U32 Options, ...)
Definition at line 3101 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), and _VPrintTarget().
SEGGER_SYSVIEW_PrintfTarget()
void SEGGER_SYSVIEW_PrintfTarget (const char * s, ...)
Definition at line 3402 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_PrintfTargetEx()
void SEGGER_SYSVIEW_PrintfTargetEx (const char * s, U32 Options, ...)
Definition at line 3366 of file SEGGER_SYSVIEW.c.
References _VPrintTarget().
SEGGER_SYSVIEW_RecordEndCall()
void SEGGER_SYSVIEW_RecordEndCall (unsigned int EventID)
Definition at line 2225 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_END_CALL, and U8.
Referenced by Task_LED().
SEGGER_SYSVIEW_RecordEndCallU32()
void SEGGER_SYSVIEW_RecordEndCallU32 (unsigned int EventID, U32 Para0)
Definition at line 2247 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_END_CALL, and U8.
SEGGER_SYSVIEW_RecordEnterISR()
void SEGGER_SYSVIEW_RecordEnterISR (void)
Definition at line 2122 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_GET_INTERRUPT_ID, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_ISR_ENTER, and U8.
Referenced by Sys_ClockTick().
SEGGER_SYSVIEW_RecordEnterTimer()
void SEGGER_SYSVIEW_RecordEnterTimer (U32 TimerId)
Definition at line 2189 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TIMER_ENTER, and U8.
Referenced by TIM1_UP_TIM10_IRQHandler(), TIM2_IRQHandler(), TIM3_IRQHandler(), TIM4_IRQHandler(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_RecordExitISR()
void SEGGER_SYSVIEW_RecordExitISR (void)
Definition at line 2149 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_ISR_EXIT, and U8.
Referenced by Sys_ClockTick().
SEGGER_SYSVIEW_RecordExitISRToScheduler()
void SEGGER_SYSVIEW_RecordExitISRToScheduler (void)
Definition at line 2171 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_ISR_TO_SCHEDULER, and U8.
SEGGER_SYSVIEW_RecordExitTimer()
void SEGGER_SYSVIEW_RecordExitTimer (void)
Definition at line 2207 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TIMER_EXIT, and U8.
Referenced by TIM1_UP_TIM10_IRQHandler(), TIM2_IRQHandler(), TIM3_IRQHandler(), TIM4_IRQHandler(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_RecordModuleDescription()
void SEGGER_SYSVIEW_RecordModuleDescription (const SEGGER_SYSVIEW_MODULE * pModule, const char * sDescription)
Definition at line 2970 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _pFirstModule, _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_MODULEDESC, and U8.
SEGGER_SYSVIEW_RecordString()
void SEGGER_SYSVIEW_RecordString (unsigned int EventId, const char * pString)
Definition at line 1824 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, and U8.
SEGGER_SYSVIEW_RecordSystime()
void SEGGER_SYSVIEW_RecordSystime (void)
Definition at line 2098 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, SEGGER_SYSVIEW_OS_API::pfGetTime, SEGGER_SYSVIEW_GLOBALS::pOSAPI, SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x2(), SYSVIEW_EVTID_SYSTIME_CYCLES, SYSVIEW_EVTID_SYSTIME_US, U32, and U64.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_RecordU32()
void SEGGER_SYSVIEW_RecordU32 (unsigned int EventId, U32 Para0)
Definition at line 1510 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SEGGER_SYSVIEW_RecordU32x10()
void SEGGER_SYSVIEW_RecordU32x10 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8, U32 Para9)
Definition at line 1789 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x2()
void SEGGER_SYSVIEW_RecordU32x2 (unsigned int EventId, U32 Para0, U32 Para1)
Definition at line 1533 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SEGGER_SYSVIEW_RecordU32x3()
void SEGGER_SYSVIEW_RecordU32x3 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2)
Definition at line 1558 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x4()
void SEGGER_SYSVIEW_RecordU32x4 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3)
Definition at line 1585 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x5()
void SEGGER_SYSVIEW_RecordU32x5 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4)
Definition at line 1614 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x6()
void SEGGER_SYSVIEW_RecordU32x6 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5)
Definition at line 1645 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x7()
void SEGGER_SYSVIEW_RecordU32x7 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6)
Definition at line 1678 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x8()
void SEGGER_SYSVIEW_RecordU32x8 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7)
Definition at line 1713 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x9()
void SEGGER_SYSVIEW_RecordU32x9 (unsigned int EventId, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8)
Definition at line 1750 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordVoid()
void SEGGER_SYSVIEW_RecordVoid (unsigned int EventId)
Definition at line 1490 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, and U8.
Referenced by SEGGER_SYSVIEW_Start(), and Task_LED().
SEGGER_SYSVIEW_RegisterData()
void SEGGER_SYSVIEW_RegisterData (SEGGER_SYSVIEW_DATA_REGISTER * pInfo)
Definition at line 2541 of file SEGGER_SYSVIEW.c.
References _EncodeFloat(), _EncodeStr(), _SendPacket(), SEGGER_SYSVIEW_DATA_REGISTER::DataType, ENCODE_U32, SEGGER_SYSVIEW_DATA_REGISTER::ID, SEGGER_SYSVIEW_DATA_REGISTER::Offset, SEGGER_SYSVIEW_DATA_REGISTER::RangeMax, SEGGER_SYSVIEW_DATA_REGISTER::RangeMin, RECORD_END, RECORD_START, SEGGER_SYSVIEW_DATA_REGISTER::ScalingFactor, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_DATA_REGISTER::sName, SEGGER_SYSVIEW_DATA_REGISTER::sUnit, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_REGISTER_DATA, and U8.
SEGGER_SYSVIEW_RegisterModule()
void SEGGER_SYSVIEW_RegisterModule (SEGGER_SYSVIEW_MODULE * pModule)
Definition at line 2932 of file SEGGER_SYSVIEW.c.
References _NumModules, _pFirstModule, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, MODULE_EVENT_OFFSET, SEGGER_SYSVIEW_MODULE_STRUCT::NumEvents, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_SendModule(), and SEGGER_SYSVIEW_UNLOCK.
SEGGER_SYSVIEW_SampleData()
void SEGGER_SYSVIEW_SampleData (const SEGGER_SYSVIEW_DATA_SAMPLE * pInfo)
Definition at line 2030 of file SEGGER_SYSVIEW.c.
References _EncodeFloat(), _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_DATA_SAMPLE::ID, SEGGER_SYSVIEW_DATA_SAMPLE::pFloat, SEGGER_SYSVIEW_DATA_SAMPLE::pValue, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_DATA_SAMPLE, and U8.
SEGGER_SYSVIEW_SendModule()
void SEGGER_SYSVIEW_SendModule (U8 ModuleId)
Definition at line 3011 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _pFirstModule, _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, SEGGER_SYSVIEW_MODULE_STRUCT::pfSendModuleDesc, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_MODULE_STRUCT::sModule, SYSVIEW_EVTID_MODULEDESC, U32, and U8.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_RegisterModule().
SEGGER_SYSVIEW_SendModuleDescription()
void SEGGER_SYSVIEW_SendModuleDescription (void)
Definition at line 3053 of file SEGGER_SYSVIEW.c.
References _pFirstModule, SEGGER_SYSVIEW_MODULE_STRUCT::pfSendModuleDesc, and SEGGER_SYSVIEW_MODULE_STRUCT::pNext.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_SendNumModules()
void SEGGER_SYSVIEW_SendNumModules (void)
Definition at line 3074 of file SEGGER_SYSVIEW.c.
References _NumModules, _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_NUMMODULES, and U8.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_SendPacket()
int SEGGER_SYSVIEW_SendPacket (U8 * pPacket, U8 * pPayloadEnd, unsigned int EventId)
Definition at line 2774 of file SEGGER_SYSVIEW.c.
References _SendPacket(), SEGGER_SYSVIEW_LOCK, and SEGGER_SYSVIEW_UNLOCK.
SEGGER_SYSVIEW_SendStackInfo()
void SEGGER_SYSVIEW_SendStackInfo (const SEGGER_SYSVIEW_STACKINFO * pInfo)
Definition at line 2005 of file SEGGER_SYSVIEW.c.
References ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SEGGER_SYSVIEW_STACKINFO::StackBase, SEGGER_SYSVIEW_STACKINFO::StackSize, SEGGER_SYSVIEW_STACKINFO::StackUsage, SEGGER_SYSVIEW_STACKINFO::TaskID, and U8.
SEGGER_SYSVIEW_SendSysDesc()
void SEGGER_SYSVIEW_SendSysDesc (const char * sSysDesc)
Definition at line 2080 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SYSVIEW_EVTID_SYSDESC, and U8.
Referenced by _cbSendSystemDesc().
SEGGER_SYSVIEW_SendTaskInfo()
void SEGGER_SYSVIEW_SendTaskInfo (const SEGGER_SYSVIEW_TASKINFO * pInfo)
Definition at line 1973 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_TASKINFO::Prio, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SEGGER_SYSVIEW_TASKINFO::sName, SEGGER_SYSVIEW_TASKINFO::StackBase, SEGGER_SYSVIEW_TASKINFO::StackSize, SEGGER_SYSVIEW_TASKINFO::StackUsage, SYSVIEW_EVTID_STACK_INFO, SYSVIEW_EVTID_TASK_INFO, SEGGER_SYSVIEW_TASKINFO::TaskID, and U8.
Referenced by _cbSendTaskList().
SEGGER_SYSVIEW_SendTaskList()
void SEGGER_SYSVIEW_SendTaskList (void)
Definition at line 2050 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, SEGGER_SYSVIEW_OS_API::pfSendTaskList, and SEGGER_SYSVIEW_GLOBALS::pOSAPI.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_SetRAMBase()
void SEGGER_SYSVIEW_SetRAMBase (U32 RAMBaseAddress)
Definition at line 1476 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress.
Referenced by SEGGER_SYSVIEW_Conf().
SEGGER_SYSVIEW_ShrinkId()
U32 SEGGER_SYSVIEW_ShrinkId (U32 Id)
Definition at line 2910 of file SEGGER_SYSVIEW.c.
References SHRINK_ID.
SEGGER_SYSVIEW_Start()
void SEGGER_SYSVIEW_Start (void)
Definition at line 1860 of file SEGGER_SYSVIEW.c.
References _abSync, _SendPacket(), _SYSVIEW_Globals, CHANNEL_ID_UP, SEGGER_SYSVIEW_GLOBALS::CPUFreq, SEGGER_SYSVIEW_GLOBALS::EnableState, ENCODE_U32, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, RECORD_END, RECORD_START, SEGGER_RTT_WriteSkipNoLock(), SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_ON_EVENT_RECORDED, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_RecordSystime(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendTaskList(), SEGGER_SYSVIEW_UNLOCK, SEGGER_SYSVIEW_GLOBALS::SysFreq, SYSVIEW_EVTID_INIT, SYSVIEW_EVTID_TRACE_START, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_Stop()
void SEGGER_SYSVIEW_Stop (void)
Definition at line 1915 of file SEGGER_SYSVIEW.c.
References _SendPacket(), _SYSVIEW_Globals, SEGGER_SYSVIEW_GLOBALS::EnableState, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TRACE_STOP, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_VErrorfHost()
void SEGGER_SYSVIEW_VErrorfHost (const char * s, va_list * pParamList)
Definition at line 3337 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_VErrorfTarget()
void SEGGER_SYSVIEW_VErrorfTarget (const char * s, va_list * pParamList)
Definition at line 3492 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_VPrintfHost()
void SEGGER_SYSVIEW_VPrintfHost (const char * s, va_list * pParamList)
Definition at line 3203 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_VPrintfHostEx()
void SEGGER_SYSVIEW_VPrintfHostEx (const char * s, U32 Options, va_list * pParamList)
Definition at line 3138 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), and _VPrintTarget().
SEGGER_SYSVIEW_VPrintfTarget()
void SEGGER_SYSVIEW_VPrintfTarget (const char * s, va_list * pParamList)
Definition at line 3422 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_VPrintfTargetEx()
void SEGGER_SYSVIEW_VPrintfTargetEx (const char * s, U32 Options, va_list * pParamList)
Definition at line 3387 of file SEGGER_SYSVIEW.c.
References _VPrintTarget().
SEGGER_SYSVIEW_VWarnfHost()
void SEGGER_SYSVIEW_VWarnfHost (const char * s, va_list * pParamList)
Definition at line 3270 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_VWarnfTarget()
void SEGGER_SYSVIEW_VWarnfTarget (const char * s, va_list * pParamList)
Definition at line 3457 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_Warn()
void SEGGER_SYSVIEW_Warn (const char * s)
Definition at line 3529 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_WARNING, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
SEGGER_SYSVIEW_WarnfHost()
void SEGGER_SYSVIEW_WarnfHost (const char * s, ...)
Definition at line 3234 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_WarnfTarget()
void SEGGER_SYSVIEW_WarnfTarget (const char * s, ...)
Definition at line 3437 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_X_GetInterruptId()
U32 SEGGER_SYSVIEW_X_GetInterruptId (void)
SEGGER_SYSVIEW_X_GetTimestamp()
U32 SEGGER_SYSVIEW_X_GetTimestamp (void)
SEGGER_SYSVIEW_X_OnEventRecorded()
void SEGGER_SYSVIEW_X_OnEventRecorded (unsigned NumBytes)
SEGGER_SYSVIEW_X_StartComm()
void SEGGER_SYSVIEW_X_StartComm (void)
Variable Documentation
SEGGER_SYSVIEW_InterruptId
EXTERN unsigned int SEGGER_SYSVIEW_InterruptId
Definition at line 266 of file SEGGER_SYSVIEW.h.
SEGGER_SYSVIEW_TickCnt
EXTERN unsigned int SEGGER_SYSVIEW_TickCnt
Definition at line 265 of file SEGGER_SYSVIEW.h.