SystemView Application: Drivers/SysView_RTT/SEGGER/SEGGER_SYSVIEW.c File Reference
SEGGER_SYSVIEW.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include "SEGGER_SYSVIEW_Int.h"
#include "SEGGER_RTT.h"
Classes
struct SEGGER_SYSVIEW_PRINTF_DESC
struct SEGGER_SYSVIEW_GLOBALS
Macros
#define SEGGER_SYSVIEW_C
#define SHRINK_ID(Id)
#define CHANNEL_ID_UP _SYSVIEW_Globals.UpChannel
#define CHANNEL_ID_DOWN _SYSVIEW_Globals.DownChannel
#define MAKE_DELTA_32BIT(Delta)
#define _MAX_ID_BYTES 5u
#define _MAX_DATA_BYTES 2u
#define ENABLE_STATE_OFF 0
#define ENABLE_STATE_ON 1
#define ENABLE_STATE_DROPPING 2
#define FORMAT_FLAG_LEFT_JUSTIFY (1u << 0)
#define FORMAT_FLAG_PAD_ZERO (1u << 1)
#define FORMAT_FLAG_PRINT_SIGN (1u << 2)
#define FORMAT_FLAG_ALTERNATE (1u << 3)
#define MODULE_EVENT_OFFSET (512)
#define ENCODE_U32(pDest, Value)
#define RECORD_START(PacketSize)
#define RECORD_END()
Functions
static void _SendPacket (U8 *pStartPacket, U8 *pEndPacket, unsigned int EventId)
static U8 * _EncodeData (U8 *pPayload, const char *pSrc, unsigned int NumBytes)
static U8 * _EncodeFloat (U8 *pPayload, float Value)
static U8 * _EncodeStr (U8 *pPayload, const char *pText, unsigned int Limit)
static U8 * _PreparePacket (U8 *pPacket)
static void _HandleIncomingPacket (void)
static int _TrySendOverflowPacket (void)
static int _VPrintHost (const char *s, U32 Options, va_list *pParamList)
static void _StoreChar (SEGGER_SYSVIEW_PRINTF_DESC *p, char c)
static void _PrintUnsigned (SEGGER_SYSVIEW_PRINTF_DESC *pBufferDesc, unsigned int v, unsigned int Base, unsigned int NumDigits, unsigned int FieldWidth, unsigned int FormatFlags)
static void _PrintInt (SEGGER_SYSVIEW_PRINTF_DESC *pBufferDesc, int v, unsigned int Base, unsigned int NumDigits, unsigned int FieldWidth, unsigned int FormatFlags)
static void _VPrintTarget (const char *sFormat, U32 Options, va_list *pParamList)
void SEGGER_SYSVIEW_Init (U32 SysFreq, U32 CPUFreq, const SEGGER_SYSVIEW_OS_API *pOSAPI, SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC pfSendSysDesc)
void SEGGER_SYSVIEW_SetRAMBase (U32 RAMBaseAddress)
void SEGGER_SYSVIEW_RecordVoid (unsigned int EventID)
void SEGGER_SYSVIEW_RecordU32 (unsigned int EventID, U32 Value)
void SEGGER_SYSVIEW_RecordU32x2 (unsigned int EventID, U32 Para0, U32 Para1)
void SEGGER_SYSVIEW_RecordU32x3 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2)
void SEGGER_SYSVIEW_RecordU32x4 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3)
void SEGGER_SYSVIEW_RecordU32x5 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4)
void SEGGER_SYSVIEW_RecordU32x6 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5)
void SEGGER_SYSVIEW_RecordU32x7 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6)
void SEGGER_SYSVIEW_RecordU32x8 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7)
void SEGGER_SYSVIEW_RecordU32x9 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8)
void SEGGER_SYSVIEW_RecordU32x10 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8, U32 Para9)
void SEGGER_SYSVIEW_RecordString (unsigned int EventID, const char *pString)
void SEGGER_SYSVIEW_Start (void)
void SEGGER_SYSVIEW_Stop (void)
int SEGGER_SYSVIEW_GetChannelID (void)
void SEGGER_SYSVIEW_GetSysDesc (void)
void SEGGER_SYSVIEW_SendTaskInfo (const SEGGER_SYSVIEW_TASKINFO *pInfo)
void SEGGER_SYSVIEW_SendStackInfo (const SEGGER_SYSVIEW_STACKINFO *pInfo)
void SEGGER_SYSVIEW_SampleData (const SEGGER_SYSVIEW_DATA_SAMPLE *pInfo)
void SEGGER_SYSVIEW_SendTaskList (void)
void SEGGER_SYSVIEW_SendSysDesc (const char *sSysDesc)
void SEGGER_SYSVIEW_RecordSystime (void)
void SEGGER_SYSVIEW_RecordEnterISR (void)
void SEGGER_SYSVIEW_RecordExitISR (void)
void SEGGER_SYSVIEW_RecordExitISRToScheduler (void)
void SEGGER_SYSVIEW_RecordEnterTimer (U32 TimerId)
void SEGGER_SYSVIEW_RecordExitTimer (void)
void SEGGER_SYSVIEW_RecordEndCall (unsigned int EventID)
void SEGGER_SYSVIEW_RecordEndCallU32 (unsigned int EventID, U32 Para0)
void SEGGER_SYSVIEW_OnIdle (void)
void SEGGER_SYSVIEW_OnTaskCreate (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskTerminate (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStartExec (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStopExec (void)
void SEGGER_SYSVIEW_OnTaskStartReady (U32 TaskId)
void SEGGER_SYSVIEW_OnTaskStopReady (U32 TaskId, unsigned int Cause)
void SEGGER_SYSVIEW_MarkStart (unsigned MarkerId)
void SEGGER_SYSVIEW_MarkStop (unsigned MarkerId)
void SEGGER_SYSVIEW_Mark (unsigned int MarkerId)
void SEGGER_SYSVIEW_NameMarker (unsigned int MarkerId, const char *sName)
void SEGGER_SYSVIEW_NameResource (U32 ResourceId, const char *sName)
void SEGGER_SYSVIEW_RegisterData (SEGGER_SYSVIEW_DATA_REGISTER *pInfo)
void SEGGER_SYSVIEW_HeapDefine (void *pHeap, void *pBase, unsigned int HeapSize, unsigned int MetadataSize)
void SEGGER_SYSVIEW_HeapAlloc (void *pHeap, void *pUserData, unsigned int UserDataLen)
void SEGGER_SYSVIEW_HeapAllocEx (void *pHeap, void *pUserData, unsigned int UserDataLen, unsigned int Tag)
void SEGGER_SYSVIEW_HeapFree (void *pHeap, void *pUserData)
int SEGGER_SYSVIEW_SendPacket (U8 *pPacket, U8 *pPayloadEnd, unsigned int EventId)
U8 * SEGGER_SYSVIEW_EncodeU32 (U8 *pPayload, U32 Value)
U8 * SEGGER_SYSVIEW_EncodeString (U8 *pPayload, const char *s, unsigned int MaxLen)
U8 * SEGGER_SYSVIEW_EncodeData (U8 *pPayload, const char *pSrc, unsigned int NumBytes)
U8 * SEGGER_SYSVIEW_EncodeId (U8 *pPayload, U32 Id)
U32 SEGGER_SYSVIEW_ShrinkId (U32 Id)
void SEGGER_SYSVIEW_RegisterModule (SEGGER_SYSVIEW_MODULE *pModule)
void SEGGER_SYSVIEW_RecordModuleDescription (const SEGGER_SYSVIEW_MODULE *pModule, const char *sDescription)
void SEGGER_SYSVIEW_SendModule (U8 ModuleId)
void SEGGER_SYSVIEW_SendModuleDescription (void)
void SEGGER_SYSVIEW_SendNumModules (void)
void SEGGER_SYSVIEW_PrintfHostEx (const char *s, U32 Options,...)
void SEGGER_SYSVIEW_VPrintfHostEx (const char *s, U32 Options, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfHost (const char *s,...)
void SEGGER_SYSVIEW_VPrintfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_WarnfHost (const char *s,...)
void SEGGER_SYSVIEW_VWarnfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_ErrorfHost (const char *s,...)
void SEGGER_SYSVIEW_VErrorfHost (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfTargetEx (const char *s, U32 Options,...)
void SEGGER_SYSVIEW_VPrintfTargetEx (const char *s, U32 Options, va_list *pParamList)
void SEGGER_SYSVIEW_PrintfTarget (const char *s,...)
void SEGGER_SYSVIEW_VPrintfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_WarnfTarget (const char *s,...)
void SEGGER_SYSVIEW_VWarnfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_ErrorfTarget (const char *s,...)
void SEGGER_SYSVIEW_VErrorfTarget (const char *s, va_list *pParamList)
void SEGGER_SYSVIEW_Print (const char *s)
void SEGGER_SYSVIEW_Warn (const char *s)
void SEGGER_SYSVIEW_Error (const char *s)
void SEGGER_SYSVIEW_EnableEvents (U32 EnableMask)
void SEGGER_SYSVIEW_DisableEvents (U32 DisableMask)
int SEGGER_SYSVIEW_IsStarted (void)
Variables
static const U8 _abSync [10] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
static char _UpBuffer [SEGGER_SYSVIEW_RTT_BUFFER_SIZE]
static char _DownBuffer [8]
static SEGGER_SYSVIEW_GLOBALS _SYSVIEW_Globals
static SEGGER_SYSVIEW_MODULE * _pFirstModule
static U8 _NumModules
static U8 _aPacket [SEGGER_SYSVIEW_MAX_PACKET_SIZE]
Macro Definition Documentation
_MAX_DATA_BYTES
#define _MAX_DATA_BYTES 2u
Definition at line 202 of file SEGGER_SYSVIEW.c.
Referenced by _PreparePacket().
_MAX_ID_BYTES
#define _MAX_ID_BYTES 5u
Definition at line 194 of file SEGGER_SYSVIEW.c.
Referenced by _PreparePacket().
CHANNEL_ID_DOWN
#define CHANNEL_ID_DOWN _SYSVIEW_Globals.DownChannel
Definition at line 166 of file SEGGER_SYSVIEW.c.
Referenced by _HandleIncomingPacket(), _SendPacket(), and SEGGER_SYSVIEW_IsStarted().
CHANNEL_ID_UP
#define CHANNEL_ID_UP _SYSVIEW_Globals.UpChannel
Definition at line 165 of file SEGGER_SYSVIEW.c.
Referenced by _SendPacket(), _TrySendOverflowPacket(), SEGGER_SYSVIEW_GetChannelID(), and SEGGER_SYSVIEW_Start().
ENABLE_STATE_DROPPING
#define ENABLE_STATE_DROPPING 2
Definition at line 213 of file SEGGER_SYSVIEW.c.
ENABLE_STATE_OFF
#define ENABLE_STATE_OFF 0
Definition at line 211 of file SEGGER_SYSVIEW.c.
ENABLE_STATE_ON
#define ENABLE_STATE_ON 1
Definition at line 212 of file SEGGER_SYSVIEW.c.
ENCODE_U32
#define ENCODE_U32 (pDest, Value)
Value:
                                   {                                                  \
                                   U8* pSysviewPointer;                             \
                                   U32 SysViewData;                                 \
                                   pSysviewPointer = pDest;                         \
                                   SysViewData = (U32)Value;                        \
                                   while(SysViewData > 0x7F) {                      \
                                     *pSysviewPointer++ = (U8)(SysViewData | 0x80); \
                                     SysViewData >>= 7;                             \
                                   };                                               \
                                   *pSysviewPointer++ = (U8)SysViewData;            \
                                   pDest = pSysviewPointer;                         \
                                 };
Definition at line 371 of file SEGGER_SYSVIEW.c.
Referenced by _SendPacket(), _StoreChar(), _TrySendOverflowPacket(), _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_EncodeId(), SEGGER_SYSVIEW_EncodeU32(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), and SEGGER_SYSVIEW_Warn().
FORMAT_FLAG_ALTERNATE
#define FORMAT_FLAG_ALTERNATE (1u << 3)
Definition at line 218 of file SEGGER_SYSVIEW.c.
Referenced by _VPrintTarget().
FORMAT_FLAG_LEFT_JUSTIFY
#define FORMAT_FLAG_LEFT_JUSTIFY (1u << 0)
Definition at line 215 of file SEGGER_SYSVIEW.c.
Referenced by _PrintInt(), _PrintUnsigned(), and _VPrintTarget().
FORMAT_FLAG_PAD_ZERO
#define FORMAT_FLAG_PAD_ZERO (1u << 1)
Definition at line 216 of file SEGGER_SYSVIEW.c.
Referenced by _PrintInt(), _PrintUnsigned(), and _VPrintTarget().
FORMAT_FLAG_PRINT_SIGN
#define FORMAT_FLAG_PRINT_SIGN (1u << 2)
Definition at line 217 of file SEGGER_SYSVIEW.c.
Referenced by _PrintInt(), and _VPrintTarget().
MAKE_DELTA_32BIT
#define MAKE_DELTA_32BIT (Delta)
Definition at line 190 of file SEGGER_SYSVIEW.c.
Referenced by _SendPacket(), and _TrySendOverflowPacket().
MODULE_EVENT_OFFSET
#define MODULE_EVENT_OFFSET (512)
Definition at line 220 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_RegisterModule().
RECORD_END
#define RECORD_END ()
Value:
SEGGER_SYSVIEW_UNLOCK()
Definition at line 390 of file SEGGER_SYSVIEW.c.
Referenced by _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnIdle(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopExec(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitISR(), SEGGER_SYSVIEW_RecordExitISRToScheduler(), SEGGER_SYSVIEW_RecordExitTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordString(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendSysDesc(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), SEGGER_SYSVIEW_Stop(), and SEGGER_SYSVIEW_Warn().
RECORD_START
#define RECORD_START (PacketSize)
Value:
                                  SEGGER_SYSVIEW_LOCK();                            \
                                  pPayloadStart = _PreparePacket(_aPacket);
Definition at line 387 of file SEGGER_SYSVIEW.c.
Referenced by _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnIdle(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopExec(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitISR(), SEGGER_SYSVIEW_RecordExitISRToScheduler(), SEGGER_SYSVIEW_RecordExitTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordString(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendSysDesc(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), SEGGER_SYSVIEW_Stop(), and SEGGER_SYSVIEW_Warn().
SEGGER_SYSVIEW_C
#define SEGGER_SYSVIEW_C
Definition at line 141 of file SEGGER_SYSVIEW.c.
SHRINK_ID
#define SHRINK_ID (Id)
Value:
((Id) - _SYSVIEW_Globals.RAMBaseAddress)
Definition at line 158 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_EncodeId(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_SendStackInfo(), SEGGER_SYSVIEW_SendTaskInfo(), and SEGGER_SYSVIEW_ShrinkId().
Function Documentation
_EncodeData()
static U8 * _EncodeData (U8 * pPayload, const char * pSrc, unsigned int NumBytes) static
Definition at line 423 of file SEGGER_SYSVIEW.c.
References U8.
Referenced by SEGGER_SYSVIEW_EncodeData().
_EncodeFloat()
static U8 * _EncodeFloat (U8 * pPayload, float Value) static
Definition at line 462 of file SEGGER_SYSVIEW.c.
References U32, and U8.
Referenced by SEGGER_SYSVIEW_RegisterData(), and SEGGER_SYSVIEW_SampleData().
_EncodeStr()
static U8 * _EncodeStr (U8 * pPayload, const char * pText, unsigned int Limit) static
Definition at line 502 of file SEGGER_SYSVIEW.c.
References NULL, SEGGER_SYSVIEW_MAX_STRING_LEN, and U8.
Referenced by _VPrintHost(), SEGGER_SYSVIEW_EncodeString(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordString(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendSysDesc(), SEGGER_SYSVIEW_SendTaskInfo(), and SEGGER_SYSVIEW_Warn().
_HandleIncomingPacket()
static void _HandleIncomingPacket (void) static
Definition at line 577 of file SEGGER_SYSVIEW.c.
References CHANNEL_ID_DOWN, SEGGER_RTT_ReadNoLock(), SEGGER_SYSVIEW_COMMAND_ID_GET_MODULE, SEGGER_SYSVIEW_COMMAND_ID_GET_MODULEDESC, SEGGER_SYSVIEW_COMMAND_ID_GET_NUMMODULES, SEGGER_SYSVIEW_COMMAND_ID_GET_SYSDESC, SEGGER_SYSVIEW_COMMAND_ID_GET_SYSTIME, SEGGER_SYSVIEW_COMMAND_ID_GET_TASKLIST, SEGGER_SYSVIEW_COMMAND_ID_HEARTBEAT, SEGGER_SYSVIEW_COMMAND_ID_START, SEGGER_SYSVIEW_COMMAND_ID_STOP, SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_RecordSystime(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendModuleDescription(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendTaskList(), SEGGER_SYSVIEW_Start(), SEGGER_SYSVIEW_Stop(), and U8.
Referenced by _SendPacket(), and SEGGER_SYSVIEW_IsStarted().
_PreparePacket()
static U8 * _PreparePacket (U8 * pPacket) static
Definition at line 560 of file SEGGER_SYSVIEW.c.
References _MAX_DATA_BYTES, and _MAX_ID_BYTES.
Referenced by _StoreChar().
_PrintInt()
static void _PrintInt (SEGGER_SYSVIEW_PRINTF_DESC * pBufferDesc, int v, unsigned int Base, unsigned int NumDigits, unsigned int FieldWidth, unsigned int FormatFlags) static
Definition at line 1167 of file SEGGER_SYSVIEW.c.
References _PrintUnsigned(), _StoreChar(), FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, and FORMAT_FLAG_PRINT_SIGN.
Referenced by _VPrintTarget().
_PrintUnsigned()
static void _PrintUnsigned (SEGGER_SYSVIEW_PRINTF_DESC * pBufferDesc, unsigned int v, unsigned int Base, unsigned int NumDigits, unsigned int FieldWidth, unsigned int FormatFlags) static
Definition at line 1076 of file SEGGER_SYSVIEW.c.
References _StoreChar(), FORMAT_FLAG_LEFT_JUSTIFY, and FORMAT_FLAG_PAD_ZERO.
Referenced by _PrintInt(), and _VPrintTarget().
_SendPacket()
static void _SendPacket (U8 * pStartPacket, U8 * pEndPacket, unsigned int EventId) static
Definition at line 748 of file SEGGER_SYSVIEW.c.
References _HandleIncomingPacket(), _SYSVIEW_Globals, _TrySendOverflowPacket(), CHANNEL_ID_DOWN, CHANNEL_ID_UP, SEGGER_SYSVIEW_GLOBALS::DisabledEvents, SEGGER_SYSVIEW_GLOBALS::EnableState, ENCODE_U32, SEGGER_SYSVIEW_GLOBALS::LastTxTimeStamp, MAKE_DELTA_32BIT, SEGGER_SYSVIEW_GLOBALS::RecursionCnt, SEGGER_RTT_HASDATA, SEGGER_RTT_WriteSkipNoLock(), SEGGER_RTT_WriteWithOverwriteNoLock(), SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_ON_EVENT_RECORDED, SEGGER_SYSVIEW_SYNC_PERIOD_SHIFT, SEGGER_SYSVIEW_UNLOCK, U32, and U8.
Referenced by _StoreChar(), _VPrintHost(), _VPrintTarget(), SEGGER_SYSVIEW_Error(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_HeapAlloc(), SEGGER_SYSVIEW_HeapAllocEx(), SEGGER_SYSVIEW_HeapDefine(), SEGGER_SYSVIEW_HeapFree(), SEGGER_SYSVIEW_Mark(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_NameMarker(), SEGGER_SYSVIEW_NameResource(), SEGGER_SYSVIEW_OnIdle(), SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_OnTaskStartExec(), SEGGER_SYSVIEW_OnTaskStartReady(), SEGGER_SYSVIEW_OnTaskStopExec(), SEGGER_SYSVIEW_OnTaskStopReady(), SEGGER_SYSVIEW_OnTaskTerminate(), SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEndCall(), SEGGER_SYSVIEW_RecordEndCallU32(), SEGGER_SYSVIEW_RecordEnterISR(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitISR(), SEGGER_SYSVIEW_RecordExitISRToScheduler(), SEGGER_SYSVIEW_RecordExitTimer(), SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RecordString(), SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x10(), SEGGER_SYSVIEW_RecordU32x2(), SEGGER_SYSVIEW_RecordU32x3(), SEGGER_SYSVIEW_RecordU32x4(), SEGGER_SYSVIEW_RecordU32x5(), SEGGER_SYSVIEW_RecordU32x6(), SEGGER_SYSVIEW_RecordU32x7(), SEGGER_SYSVIEW_RecordU32x8(), SEGGER_SYSVIEW_RecordU32x9(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_RegisterData(), SEGGER_SYSVIEW_SampleData(), SEGGER_SYSVIEW_SendModule(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendPacket(), SEGGER_SYSVIEW_SendSysDesc(), SEGGER_SYSVIEW_SendTaskInfo(), SEGGER_SYSVIEW_Start(), SEGGER_SYSVIEW_Stop(), and SEGGER_SYSVIEW_Warn().
_StoreChar()
static void _StoreChar (SEGGER_SYSVIEW_PRINTF_DESC * p, char c) static
Definition at line 1034 of file SEGGER_SYSVIEW.c.
References _PreparePacket(), _SendPacket(), SEGGER_SYSVIEW_PRINTF_DESC::Cnt, ENCODE_U32, SEGGER_SYSVIEW_PRINTF_DESC::Options, SEGGER_SYSVIEW_PRINTF_DESC::pBuffer, SEGGER_SYSVIEW_PRINTF_DESC::pPayload, SEGGER_SYSVIEW_PRINTF_DESC::pPayloadStart, SEGGER_SYSVIEW_MAX_STRING_LEN, SYSVIEW_EVTID_PRINT_FORMATTED, U32, and U8.
Referenced by _PrintInt(), _PrintUnsigned(), and _VPrintTarget().
_TrySendOverflowPacket()
static int _TrySendOverflowPacket (void) static
Definition at line 644 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, CHANNEL_ID_UP, SEGGER_SYSVIEW_GLOBALS::DropCount, SEGGER_SYSVIEW_GLOBALS::EnableState, ENCODE_U32, I32, SEGGER_SYSVIEW_GLOBALS::LastTxTimeStamp, MAKE_DELTA_32BIT, SEGGER_RTT_WriteSkipNoLock(), SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_ON_EVENT_RECORDED, SYSVIEW_EVTID_OVERFLOW, U32, and U8.
Referenced by _SendPacket().
_VPrintHost()
static int _VPrintHost (const char * s, U32 Options, va_list * pParamList) static
Definition at line 953 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_ARGUMENTS, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_PRINT_FORMATTED, U32, and U8.
Referenced by SEGGER_SYSVIEW_ErrorfHost(), SEGGER_SYSVIEW_PrintfHost(), SEGGER_SYSVIEW_PrintfHostEx(), SEGGER_SYSVIEW_VErrorfHost(), SEGGER_SYSVIEW_VPrintfHost(), SEGGER_SYSVIEW_VPrintfHostEx(), SEGGER_SYSVIEW_VWarnfHost(), and SEGGER_SYSVIEW_WarnfHost().
_VPrintTarget()
static void _VPrintTarget (const char * sFormat, U32 Options, va_list * pParamList) static
Definition at line 1240 of file SEGGER_SYSVIEW.c.
References _aPacket, _PrintInt(), _PrintUnsigned(), _SendPacket(), _StoreChar(), SEGGER_SYSVIEW_PRINTF_DESC::Cnt, ENCODE_U32, FORMAT_FLAG_ALTERNATE, FORMAT_FLAG_LEFT_JUSTIFY, FORMAT_FLAG_PAD_ZERO, FORMAT_FLAG_PRINT_SIGN, NULL, SEGGER_SYSVIEW_PRINTF_DESC::Options, SEGGER_SYSVIEW_PRINTF_DESC::pBuffer, SEGGER_SYSVIEW_PRINTF_DESC::pPayload, SEGGER_SYSVIEW_PRINTF_DESC::pPayloadStart, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_UNLOCK, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
Referenced by SEGGER_SYSVIEW_ErrorfHost(), SEGGER_SYSVIEW_ErrorfTarget(), SEGGER_SYSVIEW_PrintfHost(), SEGGER_SYSVIEW_PrintfHostEx(), SEGGER_SYSVIEW_PrintfTarget(), SEGGER_SYSVIEW_PrintfTargetEx(), SEGGER_SYSVIEW_VErrorfHost(), SEGGER_SYSVIEW_VErrorfTarget(), SEGGER_SYSVIEW_VPrintfHost(), SEGGER_SYSVIEW_VPrintfHostEx(), SEGGER_SYSVIEW_VPrintfTarget(), SEGGER_SYSVIEW_VPrintfTargetEx(), SEGGER_SYSVIEW_VWarnfHost(), SEGGER_SYSVIEW_VWarnfTarget(), SEGGER_SYSVIEW_WarnfHost(), and SEGGER_SYSVIEW_WarnfTarget().
SEGGER_SYSVIEW_DisableEvents()
void SEGGER_SYSVIEW_DisableEvents (U32 DisableMask)
Definition at line 3587 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::DisabledEvents.
SEGGER_SYSVIEW_EnableEvents()
void SEGGER_SYSVIEW_EnableEvents (U32 EnableMask)
Definition at line 3573 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::DisabledEvents.
SEGGER_SYSVIEW_EncodeData()
U8 * SEGGER_SYSVIEW_EncodeData (U8 * pPayload, const char * pSrc, unsigned int NumBytes)
Definition at line 2854 of file SEGGER_SYSVIEW.c.
References _EncodeData().
SEGGER_SYSVIEW_EncodeId()
U8 * SEGGER_SYSVIEW_EncodeId (U8 * pPayload, U32 Id)
Definition at line 2882 of file SEGGER_SYSVIEW.c.
References ENCODE_U32, and SHRINK_ID.
SEGGER_SYSVIEW_EncodeString()
U8 * SEGGER_SYSVIEW_EncodeString (U8 * pPayload, const char * s, unsigned int MaxLen)
Definition at line 2828 of file SEGGER_SYSVIEW.c.
References _EncodeStr().
SEGGER_SYSVIEW_EncodeU32()
U8 * SEGGER_SYSVIEW_EncodeU32 (U8 * pPayload, U32 Value)
Definition at line 2801 of file SEGGER_SYSVIEW.c.
References ENCODE_U32.
SEGGER_SYSVIEW_Error()
void SEGGER_SYSVIEW_Error (const char * s)
Definition at line 3551 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ERROR, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
SEGGER_SYSVIEW_ErrorfHost()
void SEGGER_SYSVIEW_ErrorfHost (const char * s, ...)
Definition at line 3301 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_ErrorfTarget()
void SEGGER_SYSVIEW_ErrorfTarget (const char * s, ...)
Definition at line 3472 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_GetChannelID()
int SEGGER_SYSVIEW_GetChannelID (void)
Definition at line 1933 of file SEGGER_SYSVIEW.c.
References CHANNEL_ID_UP.
SEGGER_SYSVIEW_GetSysDesc()
void SEGGER_SYSVIEW_GetSysDesc (void)
Definition at line 1945 of file SEGGER_SYSVIEW.c.
References _SendPacket(), _SYSVIEW_Globals, SEGGER_SYSVIEW_GLOBALS::CPUFreq, ENCODE_U32, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_GLOBALS::SysFreq, SYSVIEW_EVTID_INIT, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_HeapAlloc()
void SEGGER_SYSVIEW_HeapAlloc (void * pHeap, void * pUserData, unsigned int UserDataLen)
Definition at line 2662 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_ALLOC, U32, and U8.
SEGGER_SYSVIEW_HeapAllocEx()
void SEGGER_SYSVIEW_HeapAllocEx (void * pHeap, void * pUserData, unsigned int UserDataLen, unsigned int Tag)
Definition at line 2714 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_ALLOC_EX, U32, and U8.
SEGGER_SYSVIEW_HeapDefine()
void SEGGER_SYSVIEW_HeapDefine (void * pHeap, void * pBase, unsigned int HeapSize, unsigned int MetadataSize)
Definition at line 2613 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_DEFINE, U32, and U8.
SEGGER_SYSVIEW_HeapFree()
void SEGGER_SYSVIEW_HeapFree (void * pHeap, void * pUserData)
Definition at line 2744 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_HEAP_FREE, U32, and U8.
SEGGER_SYSVIEW_Init()
void SEGGER_SYSVIEW_Init (U32 SysFreq, U32 CPUFreq, const SEGGER_SYSVIEW_OS_API * pOSAPI, SEGGER_SYSVIEW_SEND_SYS_DESC_FUNC pfSendSysDesc)
Definition at line 1431 of file SEGGER_SYSVIEW.c.
References _DownBuffer, _SYSVIEW_Globals, _UpBuffer, SEGGER_SYSVIEW_GLOBALS::CPUFreq, SEGGER_SYSVIEW_GLOBALS::DownChannel, SEGGER_SYSVIEW_GLOBALS::EnableState, SEGGER_SYSVIEW_GLOBALS::LastTxTimeStamp, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::pOSAPI, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, SEGGER_RTT_AllocUpBuffer(), SEGGER_RTT_ConfigDownBuffer(), SEGGER_RTT_ConfigUpBuffer(), SEGGER_RTT_MODE_NO_BLOCK_SKIP, SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_ID_BASE, SEGGER_SYSVIEW_RTT_CHANNEL, SEGGER_SYSVIEW_GLOBALS::SysFreq, U8, and SEGGER_SYSVIEW_GLOBALS::UpChannel.
Referenced by SEGGER_SYSVIEW_Conf().
SEGGER_SYSVIEW_IsStarted()
int SEGGER_SYSVIEW_IsStarted (void)
Definition at line 3602 of file SEGGER_SYSVIEW.c.
References _HandleIncomingPacket(), _SYSVIEW_Globals, CHANNEL_ID_DOWN, SEGGER_SYSVIEW_GLOBALS::EnableState, SEGGER_SYSVIEW_GLOBALS::RecursionCnt, and SEGGER_RTT_HASDATA.
SEGGER_SYSVIEW_Mark()
void SEGGER_SYSVIEW_Mark (unsigned int MarkerId)
Definition at line 2460 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_MARK, and U8.
SEGGER_SYSVIEW_MarkStart()
void SEGGER_SYSVIEW_MarkStart (unsigned MarkerId)
Definition at line 2418 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_MARK_START, and U8.
Referenced by init_OLED().
SEGGER_SYSVIEW_MarkStop()
void SEGGER_SYSVIEW_MarkStop (unsigned MarkerId)
Definition at line 2439 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_MARK_STOP, and U8.
Referenced by init_OLED().
SEGGER_SYSVIEW_NameMarker()
void SEGGER_SYSVIEW_NameMarker (unsigned int MarkerId, const char * sName)
Definition at line 2487 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_NAME_MARKER, and U8.
SEGGER_SYSVIEW_NameResource()
void SEGGER_SYSVIEW_NameResource (U32 ResourceId, const char * sName)
Definition at line 2515 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_NAME_RESOURCE, and U8.
SEGGER_SYSVIEW_OnIdle()
void SEGGER_SYSVIEW_OnIdle (void)
Definition at line 2266 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_IDLE, and U8.
SEGGER_SYSVIEW_OnTaskCreate()
void SEGGER_SYSVIEW_OnTaskCreate (U32 TaskId)
Definition at line 2285 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_CREATE, and U8.
Referenced by SYSVIEW_AddTask().
SEGGER_SYSVIEW_OnTaskStartExec()
void SEGGER_SYSVIEW_OnTaskStartExec (U32 TaskId)
Definition at line 2334 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_START_EXEC, and U8.
SEGGER_SYSVIEW_OnTaskStartReady()
void SEGGER_SYSVIEW_OnTaskStartReady (U32 TaskId)
Definition at line 2372 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_START_READY, and U8.
SEGGER_SYSVIEW_OnTaskStopExec()
void SEGGER_SYSVIEW_OnTaskStopExec (void)
Definition at line 2354 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TASK_STOP_EXEC, and U8.
SEGGER_SYSVIEW_OnTaskStopReady()
void SEGGER_SYSVIEW_OnTaskStopReady (U32 TaskId, unsigned int Cause)
Definition at line 2395 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_STOP_READY, and U8.
SEGGER_SYSVIEW_OnTaskTerminate()
void SEGGER_SYSVIEW_OnTaskTerminate (U32 TaskId)
Definition at line 2310 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TASK_TERMINATE, and U8.
SEGGER_SYSVIEW_Print()
void SEGGER_SYSVIEW_Print (const char * s)
Definition at line 3507 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_LOG, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
Referenced by init_OLED(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_PrintfHost()
void SEGGER_SYSVIEW_PrintfHost (const char * s, ...)
Definition at line 3168 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_PrintfHostEx()
void SEGGER_SYSVIEW_PrintfHostEx (const char * s, U32 Options, ...)
Definition at line 3101 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), and _VPrintTarget().
SEGGER_SYSVIEW_PrintfTarget()
void SEGGER_SYSVIEW_PrintfTarget (const char * s, ...)
Definition at line 3402 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_PrintfTargetEx()
void SEGGER_SYSVIEW_PrintfTargetEx (const char * s, U32 Options, ...)
Definition at line 3366 of file SEGGER_SYSVIEW.c.
References _VPrintTarget().
SEGGER_SYSVIEW_RecordEndCall()
void SEGGER_SYSVIEW_RecordEndCall (unsigned int EventID)
Definition at line 2225 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_END_CALL, and U8.
Referenced by Task_LED().
SEGGER_SYSVIEW_RecordEndCallU32()
void SEGGER_SYSVIEW_RecordEndCallU32 (unsigned int EventID, U32 Para0)
Definition at line 2247 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_END_CALL, and U8.
SEGGER_SYSVIEW_RecordEnterISR()
void SEGGER_SYSVIEW_RecordEnterISR (void)
Definition at line 2122 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_GET_INTERRUPT_ID, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_ISR_ENTER, and U8.
Referenced by Sys_ClockTick().
SEGGER_SYSVIEW_RecordEnterTimer()
void SEGGER_SYSVIEW_RecordEnterTimer (U32 TimerId)
Definition at line 2189 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SYSVIEW_EVTID_TIMER_ENTER, and U8.
Referenced by TIM1_UP_TIM10_IRQHandler(), TIM2_IRQHandler(), TIM3_IRQHandler(), TIM4_IRQHandler(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_RecordExitISR()
void SEGGER_SYSVIEW_RecordExitISR (void)
Definition at line 2149 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_ISR_EXIT, and U8.
Referenced by Sys_ClockTick().
SEGGER_SYSVIEW_RecordExitISRToScheduler()
void SEGGER_SYSVIEW_RecordExitISRToScheduler (void)
Definition at line 2171 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_ISR_TO_SCHEDULER, and U8.
SEGGER_SYSVIEW_RecordExitTimer()
void SEGGER_SYSVIEW_RecordExitTimer (void)
Definition at line 2207 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TIMER_EXIT, and U8.
Referenced by TIM1_UP_TIM10_IRQHandler(), TIM2_IRQHandler(), TIM3_IRQHandler(), TIM4_IRQHandler(), and TIM5_IRQHandler().
SEGGER_SYSVIEW_RecordModuleDescription()
void SEGGER_SYSVIEW_RecordModuleDescription (const SEGGER_SYSVIEW_MODULE * pModule, const char * sDescription)
Definition at line 2970 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _pFirstModule, _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_MODULEDESC, and U8.
SEGGER_SYSVIEW_RecordString()
void SEGGER_SYSVIEW_RecordString (unsigned int EventID, const char * pString)
Definition at line 1824 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, and U8.
SEGGER_SYSVIEW_RecordSystime()
void SEGGER_SYSVIEW_RecordSystime (void)
Definition at line 2098 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, SEGGER_SYSVIEW_OS_API::pfGetTime, SEGGER_SYSVIEW_GLOBALS::pOSAPI, SEGGER_SYSVIEW_GET_TIMESTAMP, SEGGER_SYSVIEW_RecordU32(), SEGGER_SYSVIEW_RecordU32x2(), SYSVIEW_EVTID_SYSTIME_CYCLES, SYSVIEW_EVTID_SYSTIME_US, U32, and U64.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_RecordU32()
void SEGGER_SYSVIEW_RecordU32 (unsigned int EventID, U32 Value)
Definition at line 1510 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SEGGER_SYSVIEW_RecordU32x10()
void SEGGER_SYSVIEW_RecordU32x10 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8, U32 Para9)
Definition at line 1789 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x2()
void SEGGER_SYSVIEW_RecordU32x2 (unsigned int EventID, U32 Para0, U32 Para1)
Definition at line 1533 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
Referenced by SEGGER_SYSVIEW_RecordSystime().
SEGGER_SYSVIEW_RecordU32x3()
void SEGGER_SYSVIEW_RecordU32x3 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2)
Definition at line 1558 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x4()
void SEGGER_SYSVIEW_RecordU32x4 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3)
Definition at line 1585 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x5()
void SEGGER_SYSVIEW_RecordU32x5 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4)
Definition at line 1614 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x6()
void SEGGER_SYSVIEW_RecordU32x6 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5)
Definition at line 1645 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x7()
void SEGGER_SYSVIEW_RecordU32x7 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6)
Definition at line 1678 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x8()
void SEGGER_SYSVIEW_RecordU32x8 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7)
Definition at line 1713 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordU32x9()
void SEGGER_SYSVIEW_RecordU32x9 (unsigned int EventID, U32 Para0, U32 Para1, U32 Para2, U32 Para3, U32 Para4, U32 Para5, U32 Para6, U32 Para7, U32 Para8)
Definition at line 1750 of file SEGGER_SYSVIEW.c.
References _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, and U8.
SEGGER_SYSVIEW_RecordVoid()
void SEGGER_SYSVIEW_RecordVoid (unsigned int EventID)
Definition at line 1490 of file SEGGER_SYSVIEW.c.
References _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, and U8.
Referenced by SEGGER_SYSVIEW_Start(), and Task_LED().
SEGGER_SYSVIEW_RegisterData()
void SEGGER_SYSVIEW_RegisterData (SEGGER_SYSVIEW_DATA_REGISTER * pInfo)
Definition at line 2541 of file SEGGER_SYSVIEW.c.
References _EncodeFloat(), _EncodeStr(), _SendPacket(), SEGGER_SYSVIEW_DATA_REGISTER::DataType, ENCODE_U32, SEGGER_SYSVIEW_DATA_REGISTER::ID, SEGGER_SYSVIEW_DATA_REGISTER::Offset, SEGGER_SYSVIEW_DATA_REGISTER::RangeMax, SEGGER_SYSVIEW_DATA_REGISTER::RangeMin, RECORD_END, RECORD_START, SEGGER_SYSVIEW_DATA_REGISTER::ScalingFactor, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_DATA_REGISTER::sName, SEGGER_SYSVIEW_DATA_REGISTER::sUnit, SYSVIEW_EVTID_EX, SYSVIEW_EVTID_EX_REGISTER_DATA, and U8.
SEGGER_SYSVIEW_RegisterModule()
void SEGGER_SYSVIEW_RegisterModule (SEGGER_SYSVIEW_MODULE * pModule)
Definition at line 2932 of file SEGGER_SYSVIEW.c.
References _NumModules, _pFirstModule, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, MODULE_EVENT_OFFSET, SEGGER_SYSVIEW_MODULE_STRUCT::NumEvents, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_SendModule(), and SEGGER_SYSVIEW_UNLOCK.
SEGGER_SYSVIEW_SampleData()
void SEGGER_SYSVIEW_SampleData (const SEGGER_SYSVIEW_DATA_SAMPLE * pInfo)
Definition at line 2030 of file SEGGER_SYSVIEW.c.
References _EncodeFloat(), _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_DATA_SAMPLE::ID, SEGGER_SYSVIEW_DATA_SAMPLE::pFloat, SEGGER_SYSVIEW_DATA_SAMPLE::pValue, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_DATA_SAMPLE, and U8.
SEGGER_SYSVIEW_SendModule()
void SEGGER_SYSVIEW_SendModule (U8 ModuleId)
Definition at line 3011 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _pFirstModule, _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_MODULE_STRUCT::EventOffset, SEGGER_SYSVIEW_MODULE_STRUCT::pfSendModuleDesc, SEGGER_SYSVIEW_MODULE_STRUCT::pNext, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_MODULE_STRUCT::sModule, SYSVIEW_EVTID_MODULEDESC, U32, and U8.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_RegisterModule().
SEGGER_SYSVIEW_SendModuleDescription()
void SEGGER_SYSVIEW_SendModuleDescription (void)
Definition at line 3053 of file SEGGER_SYSVIEW.c.
References _pFirstModule, SEGGER_SYSVIEW_MODULE_STRUCT::pfSendModuleDesc, and SEGGER_SYSVIEW_MODULE_STRUCT::pNext.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_SendNumModules()
void SEGGER_SYSVIEW_SendNumModules (void)
Definition at line 3074 of file SEGGER_SYSVIEW.c.
References _NumModules, _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SYSVIEW_EVTID_NUMMODULES, and U8.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_SendPacket()
int SEGGER_SYSVIEW_SendPacket (U8 * pPacket, U8 * pPayloadEnd, unsigned int EventId)
Definition at line 2774 of file SEGGER_SYSVIEW.c.
References _SendPacket(), SEGGER_SYSVIEW_LOCK, and SEGGER_SYSVIEW_UNLOCK.
SEGGER_SYSVIEW_SendStackInfo()
void SEGGER_SYSVIEW_SendStackInfo (const SEGGER_SYSVIEW_STACKINFO * pInfo)
Definition at line 2005 of file SEGGER_SYSVIEW.c.
References ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SEGGER_SYSVIEW_STACKINFO::StackBase, SEGGER_SYSVIEW_STACKINFO::StackSize, SEGGER_SYSVIEW_STACKINFO::StackUsage, SEGGER_SYSVIEW_STACKINFO::TaskID, and U8.
SEGGER_SYSVIEW_SendSysDesc()
void SEGGER_SYSVIEW_SendSysDesc (const char * sSysDesc)
Definition at line 2080 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SYSVIEW_EVTID_SYSDESC, and U8.
Referenced by _cbSendSystemDesc().
SEGGER_SYSVIEW_SendTaskInfo()
void SEGGER_SYSVIEW_SendTaskInfo (const SEGGER_SYSVIEW_TASKINFO * pInfo)
Definition at line 1973 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, SEGGER_SYSVIEW_TASKINFO::Prio, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_QUANTA_U32, SHRINK_ID, SEGGER_SYSVIEW_TASKINFO::sName, SEGGER_SYSVIEW_TASKINFO::StackBase, SEGGER_SYSVIEW_TASKINFO::StackSize, SEGGER_SYSVIEW_TASKINFO::StackUsage, SYSVIEW_EVTID_STACK_INFO, SYSVIEW_EVTID_TASK_INFO, SEGGER_SYSVIEW_TASKINFO::TaskID, and U8.
Referenced by _cbSendTaskList().
SEGGER_SYSVIEW_SendTaskList()
void SEGGER_SYSVIEW_SendTaskList (void)
Definition at line 2050 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, SEGGER_SYSVIEW_OS_API::pfSendTaskList, and SEGGER_SYSVIEW_GLOBALS::pOSAPI.
Referenced by _HandleIncomingPacket(), and SEGGER_SYSVIEW_Start().
SEGGER_SYSVIEW_SetRAMBase()
void SEGGER_SYSVIEW_SetRAMBase (U32 RAMBaseAddress)
Definition at line 1476 of file SEGGER_SYSVIEW.c.
References _SYSVIEW_Globals, and SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress.
Referenced by SEGGER_SYSVIEW_Conf().
SEGGER_SYSVIEW_ShrinkId()
U32 SEGGER_SYSVIEW_ShrinkId (U32 Id)
Definition at line 2910 of file SEGGER_SYSVIEW.c.
References SHRINK_ID.
SEGGER_SYSVIEW_Start()
void SEGGER_SYSVIEW_Start (void)
Definition at line 1860 of file SEGGER_SYSVIEW.c.
References _abSync, _SendPacket(), _SYSVIEW_Globals, CHANNEL_ID_UP, SEGGER_SYSVIEW_GLOBALS::CPUFreq, SEGGER_SYSVIEW_GLOBALS::EnableState, ENCODE_U32, SEGGER_SYSVIEW_GLOBALS::pfSendSysDesc, SEGGER_SYSVIEW_GLOBALS::RAMBaseAddress, RECORD_END, RECORD_START, SEGGER_RTT_WriteSkipNoLock(), SEGGER_SYSVIEW_ID_SHIFT, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_LOCK, SEGGER_SYSVIEW_ON_EVENT_RECORDED, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_RecordSystime(), SEGGER_SYSVIEW_RecordVoid(), SEGGER_SYSVIEW_SendNumModules(), SEGGER_SYSVIEW_SendTaskList(), SEGGER_SYSVIEW_UNLOCK, SEGGER_SYSVIEW_GLOBALS::SysFreq, SYSVIEW_EVTID_INIT, SYSVIEW_EVTID_TRACE_START, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_Stop()
void SEGGER_SYSVIEW_Stop (void)
Definition at line 1915 of file SEGGER_SYSVIEW.c.
References _SendPacket(), _SYSVIEW_Globals, SEGGER_SYSVIEW_GLOBALS::EnableState, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SYSVIEW_EVTID_TRACE_STOP, and U8.
Referenced by _HandleIncomingPacket().
SEGGER_SYSVIEW_VErrorfHost()
void SEGGER_SYSVIEW_VErrorfHost (const char * s, va_list * pParamList)
Definition at line 3337 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_VErrorfTarget()
void SEGGER_SYSVIEW_VErrorfTarget (const char * s, va_list * pParamList)
Definition at line 3492 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_ERROR.
SEGGER_SYSVIEW_VPrintfHost()
void SEGGER_SYSVIEW_VPrintfHost (const char * s, va_list * pParamList)
Definition at line 3203 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_VPrintfHostEx()
void SEGGER_SYSVIEW_VPrintfHostEx (const char * s, U32 Options, va_list * pParamList)
Definition at line 3138 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), and _VPrintTarget().
SEGGER_SYSVIEW_VPrintfTarget()
void SEGGER_SYSVIEW_VPrintfTarget (const char * s, va_list * pParamList)
Definition at line 3422 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_LOG.
SEGGER_SYSVIEW_VPrintfTargetEx()
void SEGGER_SYSVIEW_VPrintfTargetEx (const char * s, U32 Options, va_list * pParamList)
Definition at line 3387 of file SEGGER_SYSVIEW.c.
References _VPrintTarget().
SEGGER_SYSVIEW_VWarnfHost()
void SEGGER_SYSVIEW_VWarnfHost (const char * s, va_list * pParamList)
Definition at line 3270 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_VWarnfTarget()
void SEGGER_SYSVIEW_VWarnfTarget (const char * s, va_list * pParamList)
Definition at line 3457 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_Warn()
void SEGGER_SYSVIEW_Warn (const char * s)
Definition at line 3529 of file SEGGER_SYSVIEW.c.
References _EncodeStr(), _SendPacket(), ENCODE_U32, RECORD_END, RECORD_START, SEGGER_SYSVIEW_INFO_SIZE, SEGGER_SYSVIEW_MAX_STRING_LEN, SEGGER_SYSVIEW_QUANTA_U32, SEGGER_SYSVIEW_WARNING, SYSVIEW_EVTID_PRINT_FORMATTED, and U8.
SEGGER_SYSVIEW_WarnfHost()
void SEGGER_SYSVIEW_WarnfHost (const char * s, ...)
Definition at line 3234 of file SEGGER_SYSVIEW.c.
References _VPrintHost(), _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
SEGGER_SYSVIEW_WarnfTarget()
void SEGGER_SYSVIEW_WarnfTarget (const char * s, ...)
Definition at line 3437 of file SEGGER_SYSVIEW.c.
References _VPrintTarget(), and SEGGER_SYSVIEW_WARNING.
Variable Documentation
_abSync
const U8 _abSync[10] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00} static
Definition at line 269 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_Start().
_aPacket
U8 _aPacket[SEGGER_SYSVIEW_MAX_PACKET_SIZE] static
Definition at line 385 of file SEGGER_SYSVIEW.c.
Referenced by _VPrintTarget().
_DownBuffer
char _DownBuffer[8] static
Definition at line 354 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_Init().
_NumModules
U8 _NumModules static
Definition at line 362 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_RegisterModule(), and SEGGER_SYSVIEW_SendNumModules().
_pFirstModule
SEGGER_SYSVIEW_MODULE* _pFirstModule static
Definition at line 361 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_RecordModuleDescription(), SEGGER_SYSVIEW_RegisterModule(), SEGGER_SYSVIEW_SendModule(), and SEGGER_SYSVIEW_SendModuleDescription().
_SYSVIEW_Globals
SEGGER_SYSVIEW_GLOBALS _SYSVIEW_Globals static
Definition at line 359 of file SEGGER_SYSVIEW.c.
Referenced by _SendPacket(), _TrySendOverflowPacket(), SEGGER_SYSVIEW_DisableEvents(), SEGGER_SYSVIEW_EnableEvents(), SEGGER_SYSVIEW_GetSysDesc(), SEGGER_SYSVIEW_Init(), SEGGER_SYSVIEW_IsStarted(), SEGGER_SYSVIEW_RecordSystime(), SEGGER_SYSVIEW_SendTaskList(), SEGGER_SYSVIEW_SetRAMBase(), SEGGER_SYSVIEW_Start(), and SEGGER_SYSVIEW_Stop().
_UpBuffer
char _UpBuffer[SEGGER_SYSVIEW_RTT_BUFFER_SIZE] static
Definition at line 352 of file SEGGER_SYSVIEW.c.
Referenced by SEGGER_SYSVIEW_Init().