SystemView Application: CRYP Data processing functions
CRYP Data processing functions
STM32F4xx_StdPeriph_Driver » CRYP » CRYP_Private_Functions
CRYP Data processing functions.
Functions
void CRYP_DataIn (uint32_t Data)
Writes data in the Data Input register (DIN).
uint32_t CRYP_DataOut (void)
Returns the last data entered into the output FIFO.
Detailed Description
CRYP Data processing functions.
 ===============================================================================
                    ##### CRYP Data processing functions #####
 ===============================================================================
 [..] This section provides functions allowing the encryption and decryption
      operations:
   (+) Enter data to be treated in the IN FIFO : using CRYP_DataIn() function.
   (+) Get the data result from the OUT FIFO : using CRYP_DataOut() function.
Function Documentation
CRYP_DataIn()
void CRYP_DataIn (uint32_t Data)
Writes data in the Data Input register (DIN).
Note
After the DIN register has been read once or several times, the FIFO must be flushed (using CRYP_FIFOFlush() function).
Parameters
Data data to write in Data Input register
Return values
None
Definition at line 439 of file stm32f4xx_cryp.c.
References CRYP.
Referenced by CRYP_AES_CBC(), CRYP_AES_CCM(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_AES_GCM(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
CRYP_DataOut()
uint32_t CRYP_DataOut (void)
Returns the last data entered into the output FIFO.
Parameters
None
Return values
Last data entered into the output FIFO.
Definition at line 449 of file stm32f4xx_cryp.c.
References CRYP.
Referenced by CRYP_AES_CBC(), CRYP_AES_CCM(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_AES_GCM(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().