SystemView Application: SPI
SPI
STM32F4xx_StdPeriph_Driver
SPI driver modules.
Topics
SPI_Exported_Constants
SPI_Private_Functions
Classes
struct SPI_InitTypeDef
SPI Init structure definition
struct I2S_InitTypeDef
I2S Init structure definition
Macros
#define CR1_CLEAR_MASK ((uint16_t)0x3040)
#define I2SCFGR_CLEAR_MASK ((uint16_t)0xF040)
#define PLLCFGR_PPLR_MASK ((uint32_t)0x70000000)
#define PLLCFGR_PPLN_MASK ((uint32_t)0x00007FC0)
#define SPI_CR2_FRF ((uint16_t)0x0010)
#define SPI_SR_TIFRFE ((uint16_t)0x0100)
Functions
void SPI_I2S_DeInit (SPI_TypeDef *SPIx)
De-initialize the SPIx peripheral registers to their default reset values.
void SPI_Init (SPI_TypeDef *SPIx, SPI_InitTypeDef *SPI_InitStruct)
Initializes the SPIx peripheral according to the specified parameters in the SPI_InitStruct.
void I2S_Init (SPI_TypeDef *SPIx, I2S_InitTypeDef *I2S_InitStruct)
Initializes the SPIx peripheral according to the specified parameters in the I2S_InitStruct.
void SPI_StructInit (SPI_InitTypeDef *SPI_InitStruct)
Fills each SPI_InitStruct member with its default value.
void I2S_StructInit (I2S_InitTypeDef *I2S_InitStruct)
Fills each I2S_InitStruct member with its default value.
void SPI_Cmd (SPI_TypeDef *SPIx, FunctionalState NewState)
Enables or disables the specified SPI peripheral.
void I2S_Cmd (SPI_TypeDef *SPIx, FunctionalState NewState)
Enables or disables the specified SPI peripheral (in I2S mode).
void SPI_DataSizeConfig (SPI_TypeDef *SPIx, uint16_t SPI_DataSize)
Configures the data size for the selected SPI.
void SPI_BiDirectionalLineConfig (SPI_TypeDef *SPIx, uint16_t SPI_Direction)
Selects the data transfer direction in bidirectional mode for the specified SPI.
void SPI_NSSInternalSoftwareConfig (SPI_TypeDef *SPIx, uint16_t SPI_NSSInternalSoft)
Configures internally by software the NSS pin for the selected SPI.
void SPI_SSOutputCmd (SPI_TypeDef *SPIx, FunctionalState NewState)
Enables or disables the SS output for the selected SPI.
void SPI_TIModeCmd (SPI_TypeDef *SPIx, FunctionalState NewState)
Enables or disables the SPIx/I2Sx DMA interface.
void I2S_FullDuplexConfig (SPI_TypeDef *I2Sxext, I2S_InitTypeDef *I2S_InitStruct)
Configures the full duplex mode for the I2Sx peripheral using its extension I2Sxext according to the specified parameters in the I2S_InitStruct.
void SPI_I2S_SendData (SPI_TypeDef *SPIx, uint16_t Data)
Transmits a Data through the SPIx/I2Sx peripheral.
uint16_t SPI_I2S_ReceiveData (SPI_TypeDef *SPIx)
Returns the most recent received data by the SPIx/I2Sx peripheral.
void SPI_CalculateCRC (SPI_TypeDef *SPIx, FunctionalState NewState)
Enables or disables the CRC value calculation of the transferred bytes.
void SPI_TransmitCRC (SPI_TypeDef *SPIx)
Transmit the SPIx CRC value.
uint16_t SPI_GetCRC (SPI_TypeDef *SPIx, uint8_t SPI_CRC)
Returns the transmit or the receive CRC register value for the specified SPI.
uint16_t SPI_GetCRCPolynomial (SPI_TypeDef *SPIx)
Returns the CRC Polynomial register value for the specified SPI.
void SPI_I2S_DMACmd (SPI_TypeDef *SPIx, uint16_t SPI_I2S_DMAReq, FunctionalState NewState)
Enables or disables the SPIx/I2Sx DMA interface.
void SPI_I2S_ITConfig (SPI_TypeDef *SPIx, uint8_t SPI_I2S_IT, FunctionalState NewState)
Enables or disables the specified SPI/I2S interrupts.
FlagStatus SPI_I2S_GetFlagStatus (SPI_TypeDef *SPIx, uint16_t SPI_I2S_FLAG)
Checks whether the specified SPIx/I2Sx flag is set or not.
void SPI_I2S_ClearFlag (SPI_TypeDef *SPIx, uint16_t SPI_I2S_FLAG)
Clears the SPIx CRC Error (CRCERR) flag.
ITStatus SPI_I2S_GetITStatus (SPI_TypeDef *SPIx, uint8_t SPI_I2S_IT)
Checks whether the specified SPIx/I2Sx interrupt has occurred or not.
void SPI_I2S_ClearITPendingBit (SPI_TypeDef *SPIx, uint8_t SPI_I2S_IT)
Clears the SPIx CRC Error (CRCERR) interrupt pending bit.
Detailed Description
SPI driver modules.
Macro Definition Documentation
CR1_CLEAR_MASK
#define CR1_CLEAR_MASK ((uint16_t)0x3040)
Definition at line 168 of file stm32f4xx_spi.c.
Referenced by SPI_Init().
I2SCFGR_CLEAR_MASK
#define I2SCFGR_CLEAR_MASK ((uint16_t)0xF040)
Definition at line 169 of file stm32f4xx_spi.c.
Referenced by I2S_FullDuplexConfig(), and I2S_Init().
PLLCFGR_PPLN_MASK
#define PLLCFGR_PPLN_MASK ((uint32_t)0x00007FC0)
Definition at line 173 of file stm32f4xx_spi.c.
PLLCFGR_PPLR_MASK
#define PLLCFGR_PPLR_MASK ((uint32_t)0x70000000)
Definition at line 172 of file stm32f4xx_spi.c.
SPI_CR2_FRF
#define SPI_CR2_FRF ((uint16_t)0x0010)
Definition at line 175 of file stm32f4xx_spi.c.
Referenced by SPI_TIModeCmd().
SPI_SR_TIFRFE
#define SPI_SR_TIFRFE ((uint16_t)0x0100)
Definition at line 176 of file stm32f4xx_spi.c.
Function Documentation
I2S_Cmd()
void I2S_Cmd (SPI_TypeDef * SPIx, FunctionalState NewState)
Enables or disables the specified SPI peripheral (in I2S mode).
Parameters
SPIx where x can be 2 or 3 to select the SPI peripheral (or I2Sxext for full duplex mode).
NewState new state of the SPIx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 576 of file stm32f4xx_spi.c.
References assert_param, DISABLE, SPI_TypeDef::I2SCFGR, IS_FUNCTIONAL_STATE, IS_SPI_23_PERIPH_EXT, and SPI_I2SCFGR_I2SE.
I2S_FullDuplexConfig()
void I2S_FullDuplexConfig (SPI_TypeDef * I2Sxext, I2S_InitTypeDef * I2S_InitStruct)
Configures the full duplex mode for the I2Sx peripheral using its extension I2Sxext according to the specified parameters in the I2S_InitStruct.
Parameters
I2Sxext where x can be 2 or 3 to select the I2S peripheral extension block.
I2S_InitStruct pointer to an I2S_InitTypeDef structure that contains the configuration information for the specified I2S peripheral extension.
Note
The structure pointed by I2S_InitStruct parameter should be the same used for the master I2S peripheral. In this case, if the master is configured as transmitter, the slave will be receiver and vice versa. Or you can force a different mode by modifying the field I2S_Mode to the value I2S_SlaveRx or I2S_SlaveTx independently of the master configuration.
The I2S full duplex extension can be configured in slave mode only.
Return values
None
Definition at line 741 of file stm32f4xx_spi.c.
References assert_param, I2S_InitTypeDef::I2S_CPOL, I2S_InitTypeDef::I2S_DataFormat, I2S_InitTypeDef::I2S_Mode, I2S_Mode_MasterRx, I2S_Mode_MasterTx, I2S_Mode_SlaveRx, I2S_Mode_SlaveTx, I2S_InitTypeDef::I2S_Standard, SPI_TypeDef::I2SCFGR, I2SCFGR_CLEAR_MASK, SPI_TypeDef::I2SPR, IS_I2S_CPOL, IS_I2S_DATA_FORMAT, IS_I2S_EXT_PERIPH, IS_I2S_MODE, IS_I2S_STANDARD, and SPI_I2SCFGR_I2SMOD.
I2S_Init()
void I2S_Init (SPI_TypeDef * SPIx, I2S_InitTypeDef * I2S_InitStruct)
Initializes the SPIx peripheral according to the specified parameters in the I2S_InitStruct.
Parameters
SPIx where x can be 2 or 3 to select the SPI peripheral (configured in I2S mode).
I2S_InitStruct pointer to an I2S_InitTypeDef structure that contains the configuration information for the specified SPI peripheral configured in I2S mode.
Note
The function calculates the optimal prescaler needed to obtain the most accurate audio frequency (depending on the I2S clock source, the PLL values and the product configuration). But in case the prescaler value is greater than 511, the default value (0x02) will be configured instead.
if an external clock is used as source clock for the I2S, then the define I2S_EXTERNAL_CLOCK_VAL in file stm32f4xx_conf.h should be enabled and set to the value of the source clock frequency (in Hz).
Return values
None
Definition at line 341 of file stm32f4xx_spi.c.
References assert_param, HSI_VALUE, I2S_InitTypeDef::I2S_AudioFreq, I2S_AudioFreq_Default, I2S_InitTypeDef::I2S_CPOL, I2S_InitTypeDef::I2S_DataFormat, I2S_DataFormat_16b, I2S_InitTypeDef::I2S_MCLKOutput, I2S_MCLKOutput_Enable, I2S_InitTypeDef::I2S_Mode, I2S_InitTypeDef::I2S_Standard, I2S_Standard_LSB, I2S_Standard_PCMLong, I2S_Standard_PCMShort, SPI_TypeDef::I2SCFGR, I2SCFGR_CLEAR_MASK, SPI_TypeDef::I2SPR, IS_I2S_AUDIO_FREQ, IS_I2S_CPOL, IS_I2S_DATA_FORMAT, IS_I2S_MCLK_OUTPUT, IS_I2S_MODE, IS_I2S_STANDARD, IS_SPI_23_PERIPH, RCC, RCC_CFGR_I2SSRC, RCC_PLLCFGR_PLLM, RCC_PLLCFGR_PLLSRC, RCC_PLLCFGR_PLLSRC_HSE, RCC_PLLI2SCFGR_PLLI2SN, RCC_PLLI2SCFGR_PLLI2SR, and SPI_I2SCFGR_I2SMOD.
I2S_StructInit()
void I2S_StructInit (I2S_InitTypeDef * I2S_InitStruct)
Fills each I2S_InitStruct member with its default value.
Parameters
I2S_InitStruct pointer to a I2S_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 522 of file stm32f4xx_spi.c.
References I2S_InitTypeDef::I2S_AudioFreq, I2S_AudioFreq_Default, I2S_InitTypeDef::I2S_CPOL, I2S_CPOL_Low, I2S_InitTypeDef::I2S_DataFormat, I2S_DataFormat_16b, I2S_InitTypeDef::I2S_MCLKOutput, I2S_MCLKOutput_Disable, I2S_InitTypeDef::I2S_Mode, I2S_Mode_SlaveTx, I2S_InitTypeDef::I2S_Standard, and I2S_Standard_Phillips.
SPI_BiDirectionalLineConfig()
void SPI_BiDirectionalLineConfig (SPI_TypeDef * SPIx, uint16_t SPI_Direction)
Selects the data transfer direction in bidirectional mode for the specified SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
SPI_Direction specifies the data transfer direction in bidirectional mode. This parameter can be one of the following values:
SPI_Direction_Tx: Selects Tx transmission direction
SPI_Direction_Rx: Selects Rx receive direction
Return values
None
Definition at line 623 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, IS_SPI_ALL_PERIPH, IS_SPI_DIRECTION, SPI_Direction_Rx, and SPI_Direction_Tx.
SPI_CalculateCRC()
void SPI_CalculateCRC (SPI_TypeDef * SPIx, FunctionalState NewState)
Enables or disables the CRC value calculation of the transferred bytes.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
NewState new state of the SPIx CRC value calculation. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 921 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH, and SPI_CR1_CRCEN.
SPI_Cmd()
void SPI_Cmd (SPI_TypeDef * SPIx, FunctionalState NewState)
Enables or disables the specified SPI peripheral.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
NewState new state of the SPIx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 551 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH, and SPI_CR1_SPE.
Referenced by HSPI_Start().
SPI_DataSizeConfig()
void SPI_DataSizeConfig (SPI_TypeDef * SPIx, uint16_t SPI_DataSize)
Configures the data size for the selected SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
SPI_DataSize specifies the SPI data size. This parameter can be one of the following values:
SPI_DataSize_16b: Set data frame format to 16bit
SPI_DataSize_8b: Set data frame format to 8bit
Return values
None
Definition at line 603 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, IS_SPI_ALL_PERIPH, IS_SPI_DATASIZE, and SPI_DataSize_16b.
SPI_GetCRC()
uint16_t SPI_GetCRC (SPI_TypeDef * SPIx, uint8_t SPI_CRC)
Returns the transmit or the receive CRC register value for the specified SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
SPI_CRC specifies the CRC register to be read. This parameter can be one of the following values:
SPI_CRC_Tx: Selects Tx CRC register
SPI_CRC_Rx: Selects Rx CRC register
Return values
The selected CRC register value..
Definition at line 961 of file stm32f4xx_spi.c.
References assert_param, IS_SPI_ALL_PERIPH, IS_SPI_CRC, SPI_TypeDef::RXCRCR, SPI_CRC_Rx, and SPI_TypeDef::TXCRCR.
SPI_GetCRCPolynomial()
uint16_t SPI_GetCRCPolynomial (SPI_TypeDef * SPIx)
Returns the CRC Polynomial register value for the specified SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
Return values
The CRC Polynomial register value.
Definition at line 986 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CRCPR, and IS_SPI_ALL_PERIPH.
SPI_I2S_ClearFlag()
void SPI_I2S_ClearFlag (SPI_TypeDef * SPIx, uint16_t SPI_I2S_FLAG)
Clears the SPIx CRC Error (CRCERR) flag.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_FLAG specifies the SPI flag to clear. This function clears only CRCERR flag.
SPI_FLAG_CRCERR: CRC Error flag.
Note
OVR (OverRun error) flag is cleared by software sequence: a read operation to SPI_DR register (SPI_I2S_ReceiveData()) followed by a read operation to SPI_SR register (SPI_I2S_GetFlagStatus()).
UDR (UnderRun error) flag is cleared by a read operation to SPI_SR register (SPI_I2S_GetFlagStatus()).
MODF (Mode Fault) flag is cleared by software sequence: a read/write operation to SPI_SR register (SPI_I2S_GetFlagStatus()) followed by a write operation to SPI_CR1 register (SPI_Cmd() to enable the SPI).
Return values
None
Definition at line 1216 of file stm32f4xx_spi.c.
References assert_param, IS_SPI_ALL_PERIPH_EXT, IS_SPI_I2S_CLEAR_FLAG, and SPI_TypeDef::SR.
SPI_I2S_ClearITPendingBit()
void SPI_I2S_ClearITPendingBit (SPI_TypeDef * SPIx, uint8_t SPI_I2S_IT)
Clears the SPIx CRC Error (CRCERR) interrupt pending bit.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_IT specifies the SPI interrupt pending bit to clear. This function clears only CRCERR interrupt pending bit.
SPI_IT_CRCERR: CRC Error interrupt.
Note
OVR (OverRun Error) interrupt pending bit is cleared by software sequence: a read operation to SPI_DR register (SPI_I2S_ReceiveData()) followed by a read operation to SPI_SR register (SPI_I2S_GetITStatus()).
UDR (UnderRun Error) interrupt pending bit is cleared by a read operation to SPI_SR register (SPI_I2S_GetITStatus()).
MODF (Mode Fault) interrupt pending bit is cleared by software sequence: a read/write operation to SPI_SR register (SPI_I2S_GetITStatus()) followed by a write operation to SPI_CR1 register (SPI_Cmd() to enable the SPI).
Return values
None
Definition at line 1296 of file stm32f4xx_spi.c.
References assert_param, IS_SPI_ALL_PERIPH_EXT, IS_SPI_I2S_CLEAR_IT, and SPI_TypeDef::SR.
SPI_I2S_DeInit()
void SPI_I2S_DeInit (SPI_TypeDef * SPIx)
De-initialize the SPIx peripheral registers to their default reset values.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode.
Note
The extended I2S blocks (ie. I2S2ext and I2S3ext blocks) are de-initialized when the relative I2S peripheral is de-initialized (the extended block's clock is managed by the I2S peripheral clock).
Return values
None
Definition at line 217 of file stm32f4xx_spi.c.
References assert_param, DISABLE, ENABLE, IS_SPI_ALL_PERIPH, RCC_APB1Periph_SPI2, RCC_APB1Periph_SPI3, RCC_APB1PeriphResetCmd(), RCC_APB2Periph_SPI1, RCC_APB2Periph_SPI4, RCC_APB2Periph_SPI5, RCC_APB2Periph_SPI6, RCC_APB2PeriphResetCmd(), SPI1, SPI2, SPI3, SPI4, SPI5, and SPI6.
SPI_I2S_DMACmd()
void SPI_I2S_DMACmd (SPI_TypeDef * SPIx, uint16_t SPI_I2S_DMAReq, FunctionalState NewState)
Enables or disables the SPIx/I2Sx DMA interface.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_DMAReq specifies the SPI DMA transfer request to be enabled or disabled. This parameter can be any combination of the following values:
SPI_I2S_DMAReq_Tx: Tx buffer DMA transfer request
SPI_I2S_DMAReq_Rx: Rx buffer DMA transfer request
NewState new state of the selected SPI DMA transfer request. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1023 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR2, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH_EXT, and IS_SPI_I2S_DMAREQ.
SPI_I2S_GetFlagStatus()
FlagStatus SPI_I2S_GetFlagStatus (SPI_TypeDef * SPIx, uint16_t SPI_I2S_FLAG)
Checks whether the specified SPIx/I2Sx flag is set or not.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_FLAG specifies the SPI flag to check. This parameter can be one of the following values:
SPI_I2S_FLAG_TXE: Transmit buffer empty flag.
SPI_I2S_FLAG_RXNE: Receive buffer not empty flag.
SPI_I2S_FLAG_BSY: Busy flag.
SPI_I2S_FLAG_OVR: Overrun flag.
SPI_FLAG_MODF: Mode Fault flag.
SPI_FLAG_CRCERR: CRC Error flag.
SPI_I2S_FLAG_TIFRFE: Format Error.
I2S_FLAG_UDR: Underrun Error flag.
I2S_FLAG_CHSIDE: Channel Side flag.
Return values
The new state of SPI_I2S_FLAG (SET or RESET).
Definition at line 1175 of file stm32f4xx_spi.c.
References assert_param, IS_SPI_ALL_PERIPH_EXT, IS_SPI_I2S_GET_FLAG, RESET, SET, and SPI_TypeDef::SR.
Referenced by HSPI_Data().
SPI_I2S_GetITStatus()
ITStatus SPI_I2S_GetITStatus (SPI_TypeDef * SPIx, uint8_t SPI_I2S_IT)
Checks whether the specified SPIx/I2Sx interrupt has occurred or not.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_IT specifies the SPI interrupt source to check. This parameter can be one of the following values:
SPI_I2S_IT_TXE: Transmit buffer empty interrupt.
SPI_I2S_IT_RXNE: Receive buffer not empty interrupt.
SPI_I2S_IT_OVR: Overrun interrupt.
SPI_IT_MODF: Mode Fault interrupt.
SPI_IT_CRCERR: CRC Error interrupt.
I2S_IT_UDR: Underrun interrupt.
SPI_I2S_IT_TIFRFE: Format Error interrupt.
Return values
The new state of SPI_I2S_IT (SET or RESET).
Definition at line 1241 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR2, IS_SPI_ALL_PERIPH_EXT, IS_SPI_I2S_GET_IT, RESET, SET, and SPI_TypeDef::SR.
SPI_I2S_ITConfig()
void SPI_I2S_ITConfig (SPI_TypeDef * SPIx, uint8_t SPI_I2S_IT, FunctionalState NewState)
Enables or disables the specified SPI/I2S interrupts.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
SPI_I2S_IT specifies the SPI interrupt source to be enabled or disabled. This parameter can be one of the following values:
SPI_I2S_IT_TXE: Tx buffer empty interrupt mask
SPI_I2S_IT_RXNE: Rx buffer not empty interrupt mask
SPI_I2S_IT_ERR: Error interrupt mask
NewState new state of the specified SPI interrupt. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1131 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR2, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH_EXT, and IS_SPI_I2S_CONFIG_IT.
SPI_I2S_ReceiveData()
uint16_t SPI_I2S_ReceiveData (SPI_TypeDef * SPIx)
Returns the most recent received data by the SPIx/I2Sx peripheral.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
Return values
The value of the received data.
Definition at line 815 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::DR, and IS_SPI_ALL_PERIPH_EXT.
Referenced by HSPI_Data().
SPI_I2S_SendData()
void SPI_I2S_SendData (SPI_TypeDef * SPIx, uint16_t Data)
Transmits a Data through the SPIx/I2Sx peripheral.
Parameters
SPIx To select the SPIx/I2Sx peripheral, where x can be: 1, 2, 3, 4, 5 or 6 in SPI mode or 2 or 3 in I2S mode or I2Sxext for I2S full duplex mode.
Data Data to be transmitted.
Return values
None
Definition at line 831 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::DR, and IS_SPI_ALL_PERIPH_EXT.
Referenced by HSPI_Data().
SPI_Init()
void SPI_Init (SPI_TypeDef * SPIx, SPI_InitTypeDef * SPI_InitStruct)
Initializes the SPIx peripheral according to the specified parameters in the SPI_InitStruct.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
SPI_InitStruct pointer to a SPI_InitTypeDef structure that contains the configuration information for the specified SPI peripheral.
Return values
None
Definition at line 277 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, CR1_CLEAR_MASK, SPI_TypeDef::CRCPR, SPI_TypeDef::I2SCFGR, IS_SPI_ALL_PERIPH, IS_SPI_BAUDRATE_PRESCALER, IS_SPI_CPHA, IS_SPI_CPOL, IS_SPI_CRC_POLYNOMIAL, IS_SPI_DATASIZE, IS_SPI_DIRECTION_MODE, IS_SPI_FIRST_BIT, IS_SPI_MODE, IS_SPI_NSS, SPI_InitTypeDef::SPI_BaudRatePrescaler, SPI_InitTypeDef::SPI_CPHA, SPI_InitTypeDef::SPI_CPOL, SPI_InitTypeDef::SPI_CRCPolynomial, SPI_InitTypeDef::SPI_DataSize, SPI_InitTypeDef::SPI_Direction, SPI_InitTypeDef::SPI_FirstBit, SPI_I2SCFGR_I2SMOD, SPI_InitTypeDef::SPI_Mode, and SPI_InitTypeDef::SPI_NSS.
Referenced by HSPI_Start().
SPI_NSSInternalSoftwareConfig()
void SPI_NSSInternalSoftwareConfig (SPI_TypeDef * SPIx, uint16_t SPI_NSSInternalSoft)
Configures internally by software the NSS pin for the selected SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
SPI_NSSInternalSoft specifies the SPI NSS internal state. This parameter can be one of the following values:
SPI_NSSInternalSoft_Set: Set NSS pin internally
SPI_NSSInternalSoft_Reset: Reset NSS pin internally
Return values
None
Definition at line 649 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, IS_SPI_ALL_PERIPH, IS_SPI_NSS_INTERNAL, SPI_NSSInternalSoft_Reset, and SPI_NSSInternalSoft_Set.
SPI_SSOutputCmd()
void SPI_SSOutputCmd (SPI_TypeDef * SPIx, FunctionalState NewState)
Enables or disables the SS output for the selected SPI.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
NewState new state of the SPIx SS output. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 673 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR2, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH, and SPI_CR2_SSOE.
SPI_StructInit()
void SPI_StructInit (SPI_InitTypeDef * SPI_InitStruct)
Fills each SPI_InitStruct member with its default value.
Parameters
SPI_InitStruct pointer to a SPI_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 494 of file stm32f4xx_spi.c.
References SPI_InitTypeDef::SPI_BaudRatePrescaler, SPI_BaudRatePrescaler_2, SPI_InitTypeDef::SPI_CPHA, SPI_CPHA_1Edge, SPI_InitTypeDef::SPI_CPOL, SPI_CPOL_Low, SPI_InitTypeDef::SPI_CRCPolynomial, SPI_InitTypeDef::SPI_DataSize, SPI_DataSize_8b, SPI_InitTypeDef::SPI_Direction, SPI_Direction_2Lines_FullDuplex, SPI_InitTypeDef::SPI_FirstBit, SPI_FirstBit_MSB, SPI_InitTypeDef::SPI_Mode, SPI_Mode_Slave, SPI_InitTypeDef::SPI_NSS, and SPI_NSS_Hard.
SPI_TIModeCmd()
void SPI_TIModeCmd (SPI_TypeDef * SPIx, FunctionalState NewState)
Enables or disables the SPIx/I2Sx DMA interface.
Note
This function can be called only after the SPI_Init() function has been called.
When TI mode is selected, the control bits SSM, SSI, CPOL and CPHA are not taken into consideration and are configured by hardware respectively to the TI mode requirements.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6
NewState new state of the selected SPI TI communication mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 704 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR2, DISABLE, IS_FUNCTIONAL_STATE, IS_SPI_ALL_PERIPH, and SPI_CR2_FRF.
SPI_TransmitCRC()
void SPI_TransmitCRC (SPI_TypeDef * SPIx)
Transmit the SPIx CRC value.
Parameters
SPIx where x can be 1, 2, 3, 4, 5 or 6 to select the SPI peripheral.
Return values
None
Definition at line 943 of file stm32f4xx_spi.c.
References assert_param, SPI_TypeDef::CR1, IS_SPI_ALL_PERIPH, and SPI_CR1_CRCNEXT.