SystemView Application: TimeBase management functions
TimeBase management functions
STM32F4xx_StdPeriph_Driver » TIM » TIM_Private_Functions
TimeBase management functions.
Functions
void TIM_DeInit (TIM_TypeDef *TIMx)
Deinitializes the TIMx peripheral registers to their default reset values.
void TIM_TimeBaseInit (TIM_TypeDef *TIMx, TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Initializes the TIMx Time Base Unit peripheral according to the specified parameters in the TIM_TimeBaseInitStruct.
void TIM_TimeBaseStructInit (TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Fills each TIM_TimeBaseInitStruct member with its default value.
void TIM_PrescalerConfig (TIM_TypeDef *TIMx, uint16_t Prescaler, uint16_t TIM_PSCReloadMode)
Configures the TIMx Prescaler.
void TIM_CounterModeConfig (TIM_TypeDef *TIMx, uint16_t TIM_CounterMode)
Specifies the TIMx Counter Mode to be used.
void TIM_SetCounter (TIM_TypeDef *TIMx, uint32_t Counter)
Sets the TIMx Counter Register value.
void TIM_SetAutoreload (TIM_TypeDef *TIMx, uint32_t Autoreload)
Sets the TIMx Autoreload Register value.
uint32_t TIM_GetCounter (TIM_TypeDef *TIMx)
Gets the TIMx Counter value.
uint16_t TIM_GetPrescaler (TIM_TypeDef *TIMx)
Gets the TIMx Prescaler value.
void TIM_UpdateDisableConfig (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or Disables the TIMx Update event.
void TIM_UpdateRequestConfig (TIM_TypeDef *TIMx, uint16_t TIM_UpdateSource)
Configures the TIMx Update Request Interrupt source.
void TIM_ARRPreloadConfig (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables TIMx peripheral Preload register on ARR.
void TIM_SelectOnePulseMode (TIM_TypeDef *TIMx, uint16_t TIM_OPMode)
Selects the TIMx's One Pulse Mode.
void TIM_SetClockDivision (TIM_TypeDef *TIMx, uint16_t TIM_CKD)
Sets the TIMx Clock Division value.
void TIM_Cmd (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the specified TIM peripheral.
Detailed Description
TimeBase management functions.
 ===============================================================================
                     ##### TimeBase management functions #####
 ===============================================================================
            ##### TIM Driver: how to use it in Timing(Time base) Mode #####
 ===============================================================================
    [..]
    To use the Timer in Timing(Time base) mode, the following steps are mandatory:
      (#) Enable TIM clock using RCC_APBxPeriphClockCmd(RCC_APBxPeriph_TIMx, ENABLE) function
      (#) Fill the TIM_TimeBaseInitStruct with the desired parameters.
      (#) Call TIM_TimeBaseInit(TIMx, &TIM_TimeBaseInitStruct) to configure the Time Base unit
          with the corresponding configuration
      (#) Enable the NVIC if you need to generate the update interrupt.
      (#) Enable the corresponding interrupt using the function TIM_ITConfig(TIMx, TIM_IT_Update)
      (#) Call the TIM_Cmd(ENABLE) function to enable the TIM counter.
       -@- All other functions can be used separately to modify, if needed,
           a specific feature of the Timer.
Function Documentation
TIM_ARRPreloadConfig()
void TIM_ARRPreloadConfig (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables TIMx peripheral Preload register on ARR.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
NewState new state of the TIMx peripheral Preload register This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 515 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, DISABLE, IS_FUNCTIONAL_STATE, IS_TIM_ALL_PERIPH, and TIM_CR1_ARPE.
Referenced by PWM_Init().
TIM_Cmd()
void TIM_Cmd (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables the specified TIM peripheral.
Parameters
TIMx where x can be 1 to 14 to select the TIMx peripheral.
NewState new state of the TIMx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 585 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, DISABLE, IS_FUNCTIONAL_STATE, IS_TIM_ALL_PERIPH, and TIM_CR1_CEN.
Referenced by Timer_Start().
TIM_CounterModeConfig()
void TIM_CounterModeConfig (TIM_TypeDef * TIMx, uint16_t TIM_CounterMode)
Specifies the TIMx Counter Mode to be used.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_CounterMode specifies the Counter Mode to be used This parameter can be one of the following values:
TIM_CounterMode_Up: TIM Up Counting Mode
TIM_CounterMode_Down: TIM Down Counting Mode
TIM_CounterMode_CenterAligned1: TIM Center Aligned Mode1
TIM_CounterMode_CenterAligned2: TIM Center Aligned Mode2
TIM_CounterMode_CenterAligned3: TIM Center Aligned Mode3
Return values
None
Definition at line 376 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, IS_TIM_COUNTER_MODE, IS_TIM_LIST3_PERIPH, TIM_CR1_CMS, and TIM_CR1_DIR.
TIM_DeInit()
void TIM_DeInit (TIM_TypeDef * TIMx)
Deinitializes the TIMx peripheral registers to their default reset values.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
None
Definition at line 193 of file stm32f4xx_tim.c.
References assert_param, DISABLE, ENABLE, IS_TIM_ALL_PERIPH, RCC_APB1Periph_TIM12, RCC_APB1Periph_TIM13, RCC_APB1Periph_TIM14, RCC_APB1Periph_TIM2, RCC_APB1Periph_TIM3, RCC_APB1Periph_TIM4, RCC_APB1Periph_TIM5, RCC_APB1Periph_TIM6, RCC_APB1Periph_TIM7, RCC_APB1PeriphResetCmd(), RCC_APB2Periph_TIM1, RCC_APB2Periph_TIM10, RCC_APB2Periph_TIM11, RCC_APB2Periph_TIM8, RCC_APB2Periph_TIM9, RCC_APB2PeriphResetCmd(), TIM1, TIM10, TIM11, TIM12, TIM13, TIM14, TIM2, TIM3, TIM4, TIM5, TIM6, TIM7, TIM8, and TIM9.
TIM_GetCounter()
uint32_t TIM_GetCounter (TIM_TypeDef * TIMx)
Gets the TIMx Counter value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
Counter Register value
Definition at line 431 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CNT, and IS_TIM_ALL_PERIPH.
TIM_GetPrescaler()
uint16_t TIM_GetPrescaler (TIM_TypeDef * TIMx)
Gets the TIMx Prescaler value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
Prescaler Register value.
Definition at line 445 of file stm32f4xx_tim.c.
References assert_param, IS_TIM_ALL_PERIPH, and TIM_TypeDef::PSC.
TIM_PrescalerConfig()
void TIM_PrescalerConfig (TIM_TypeDef * TIMx, uint16_t Prescaler, uint16_t TIM_PSCReloadMode)
Configures the TIMx Prescaler.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Prescaler specifies the Prescaler Register value
TIM_PSCReloadMode specifies the TIM Prescaler Reload mode This parameter can be one of the following values:
TIM_PSCReloadMode_Update: The Prescaler is loaded at the update event.
TIM_PSCReloadMode_Immediate: The Prescaler is loaded immediately.
Return values
None
Definition at line 353 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::EGR, IS_TIM_ALL_PERIPH, IS_TIM_PRESCALER_RELOAD, and TIM_TypeDef::PSC.
TIM_SelectOnePulseMode()
void TIM_SelectOnePulseMode (TIM_TypeDef * TIMx, uint16_t TIM_OPMode)
Selects the TIMx's One Pulse Mode.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_OPMode specifies the OPM Mode to be used. This parameter can be one of the following values:
TIM_OPMode_Single
TIM_OPMode_Repetitive
Return values
None
Definition at line 542 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, IS_TIM_ALL_PERIPH, IS_TIM_OPM_MODE, and TIM_CR1_OPM.
TIM_SetAutoreload()
void TIM_SetAutoreload (TIM_TypeDef * TIMx, uint32_t Autoreload)
Sets the TIMx Autoreload Register value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Autoreload specifies the Autoreload register new value.
Return values
None
Definition at line 417 of file stm32f4xx_tim.c.
References TIM_TypeDef::ARR, assert_param, and IS_TIM_ALL_PERIPH.
TIM_SetClockDivision()
void TIM_SetClockDivision (TIM_TypeDef * TIMx, uint16_t TIM_CKD)
Sets the TIMx Clock Division value.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_CKD specifies the clock division value. This parameter can be one of the following value:
TIM_CKD_DIV1: TDTS = Tck_tim
TIM_CKD_DIV2: TDTS = 2*Tck_tim
TIM_CKD_DIV4: TDTS = 4*Tck_tim
Return values
None
Definition at line 565 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, IS_TIM_CKD_DIV, IS_TIM_LIST1_PERIPH, and TIM_CR1_CKD.
TIM_SetCounter()
void TIM_SetCounter (TIM_TypeDef * TIMx, uint32_t Counter)
Sets the TIMx Counter Register value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Counter specifies the Counter register new value.
Return values
None
Definition at line 402 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CNT, and IS_TIM_ALL_PERIPH.
Referenced by Timer_Reset().
TIM_TimeBaseInit()
void TIM_TimeBaseInit (TIM_TypeDef * TIMx, TIM_TimeBaseInitTypeDef * TIM_TimeBaseInitStruct)
Initializes the TIMx Time Base Unit peripheral according to the specified parameters in the TIM_TimeBaseInitStruct.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_TimeBaseInitStruct pointer to a TIM_TimeBaseInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 281 of file stm32f4xx_tim.c.
References TIM_TypeDef::ARR, assert_param, TIM_TypeDef::CR1, TIM_TypeDef::EGR, IS_TIM_ALL_PERIPH, IS_TIM_CKD_DIV, IS_TIM_COUNTER_MODE, TIM_TypeDef::PSC, TIM_TypeDef::RCR, TIM1, TIM2, TIM3, TIM4, TIM5, TIM6, TIM7, TIM8, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CR1_CKD, TIM_CR1_CMS, TIM_CR1_DIR, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM_PSCReloadMode_Immediate, and TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter.
Referenced by Timer_Init().
TIM_TimeBaseStructInit()
void TIM_TimeBaseStructInit (TIM_TimeBaseInitTypeDef * TIM_TimeBaseInitStruct)
Fills each TIM_TimeBaseInitStruct member with its default value.
Parameters
TIM_TimeBaseInitStruct : pointer to a TIM_TimeBaseInitTypeDef structure which will be initialized.
Return values
None
Definition at line 333 of file stm32f4xx_tim.c.
References TIM_CKD_DIV1, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CounterMode_Up, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, and TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter.
TIM_UpdateDisableConfig()
void TIM_UpdateDisableConfig (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or Disables the TIMx Update event.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
NewState new state of the TIMx UDIS bit This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 461 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, DISABLE, IS_FUNCTIONAL_STATE, IS_TIM_ALL_PERIPH, and TIM_CR1_UDIS.
TIM_UpdateRequestConfig()
void TIM_UpdateRequestConfig (TIM_TypeDef * TIMx, uint16_t TIM_UpdateSource)
Configures the TIMx Update Request Interrupt source.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_UpdateSource specifies the Update source. This parameter can be one of the following values:
TIM_UpdateSource_Global: Source of update is the counter overflow/underflow or the setting of UG bit, or an update generation through the slave mode controller.
TIM_UpdateSource_Regular: Source of update is counter overflow/underflow.
Return values
None
Definition at line 490 of file stm32f4xx_tim.c.
References assert_param, TIM_TypeDef::CR1, IS_TIM_ALL_PERIPH, IS_TIM_UPDATE_SOURCE, TIM_CR1_URS, and TIM_UpdateSource_Global.