SystemView Application: io.h File Reference
io.h File Reference
#include "stm32f4xx.h"
Classes
struct IO_PIN
Macros
#define IO_OLED_RES
#define IO_OLED_CS
Enumerations
enum IO_MODE {
IO_MODE_INPUT , IO_MODE_OUTPUT , IO_MODE_ALTERNATE , IO_MODE_ANALOG ,
IO_MODE_INPUT_PD , IO_MODE_INPUT_PU , IO_MODE_OUTPUT_OD , IO_MODE_ALTERNATE_OD ,
IO_MODE_ALTERNATE_PU
}
enum IO_PORTS {
IO_PORT_A , IO_PORT_B , IO_PORT_C , IO_PORT_D ,
IO_PORT_E , IO_PORT_F , IO_PORT_G
}
enum IO_IDX {
IOP_LED , IOP_PWM , IOP_CAPTURE1 , IOP_CAPTURE2 ,
IOP_SPI1_SCK , IOP_SPI1_MISO , IOP_SPI1_MOSI , IOP_SPI2_SCK ,
IOP_SPI2_MISO , IOP_SPI2_MOSI , IOP_SPI_SCK , IOP_SPI_MISO ,
IOP_SPI_MOSI , IOP_OLED_RES , IOP_OLED_DC , IOP_OLED_CS
}
Functions
void IO_Init (IO_IDX idx, IO_MODE mode)
void IO_Write (IO_IDX idx, int val)
int IO_Read (IO_IDX idx)
Variables
IO_PIN _ios []
GPIO_TypeDef * GPIO_Ports []
Macro Definition Documentation
IO_OLED_CS
#define IO_OLED_CS
Definition at line 14 of file io.h.
IO_OLED_RES
#define IO_OLED_RES
Definition at line 13 of file io.h.
Enumeration Type Documentation
IO_IDX
enum IO_IDX
Enumerator
IOP_LED
IOP_PWM
IOP_CAPTURE1
IOP_CAPTURE2
IOP_SPI1_SCK
IOP_SPI1_MISO
IOP_SPI1_MOSI
IOP_SPI2_SCK
IOP_SPI2_MISO
IOP_SPI2_MOSI
IOP_SPI_SCK
IOP_SPI_MISO
IOP_SPI_MOSI
IOP_OLED_RES
IOP_OLED_DC
IOP_OLED_CS
Definition at line 46 of file io.h.
IO_MODE
enum IO_MODE
Enumerator
IO_MODE_INPUT
IO_MODE_OUTPUT
IO_MODE_ALTERNATE
IO_MODE_ANALOG
IO_MODE_INPUT_PD
IO_MODE_INPUT_PU
IO_MODE_OUTPUT_OD
IO_MODE_ALTERNATE_OD
IO_MODE_ALTERNATE_PU
Definition at line 17 of file io.h.
IO_PORTS
enum IO_PORTS
Enumerator
IO_PORT_A
IO_PORT_B
IO_PORT_C
IO_PORT_D
IO_PORT_E
IO_PORT_F
IO_PORT_G
Definition at line 30 of file io.h.
Function Documentation
IO_Init()
void IO_Init (IO_IDX idx, IO_MODE mode)
Definition at line 4 of file io.c.
References _ios, GPIO_High_Speed, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_Mode_AN, GPIO_Mode_IN, GPIO_Mode_OUT, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_OD, GPIO_OType_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_Ports, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_DOWN, GPIO_PuPd_NOPULL, GPIO_PuPd_UP, GPIO_InitTypeDef::GPIO_Speed, IO_MODE_ALTERNATE, IO_MODE_ALTERNATE_OD, IO_MODE_ALTERNATE_PU, IO_MODE_ANALOG, IO_MODE_INPUT, IO_MODE_INPUT_PD, IO_MODE_INPUT_PU, IO_MODE_OUTPUT, IO_MODE_OUTPUT_OD, IO_PIN::pin, and IO_PIN::port.
Referenced by Capture_Init(), HSPI_Start(), init(), OLED_Start(), and PWM_Init().
IO_Read()
int IO_Read (IO_IDX idx)
Definition at line 86 of file io.c.
References _ios, GPIO_Ports, GPIO_TypeDef::IDR, IO_PIN::pin, and IO_PIN::port.
IO_Write()
void IO_Write (IO_IDX idx, int val)
Definition at line 71 of file io.c.
References _ios, GPIO_TypeDef::BSRR, GPIO_Ports, IO_PIN::pin, and IO_PIN::port.
Referenced by init(), OLED_Command(), OLED_Data(), OLED_Start(), and Task_LED().
Variable Documentation
_ios
IO_PIN _ios[] extern
Referenced by HSPI_Start(), IO_Init(), IO_Read(), IO_Write(), and PWM_Init().
GPIO_Ports
GPIO_TypeDef* GPIO_Ports[] extern
Referenced by HSPI_Start(), IO_Init(), IO_Read(), IO_Write(), and PWM_Init().