SystemView Application: io.c File Reference
io.c File Reference
#include "io.h"
Macros
#define _IOS_
Functions
void IO_Init (IO_IDX idx, IO_MODE mode)
void IO_Write (IO_IDX idx, int val)
int IO_Read (IO_IDX idx)
Macro Definition Documentation
_IOS_
#define _IOS_
Definition at line 1 of file io.c.
Function Documentation
IO_Init()
void IO_Init (IO_IDX idx, IO_MODE mode)
Definition at line 4 of file io.c.
References _ios, GPIO_High_Speed, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_Mode_AN, GPIO_Mode_IN, GPIO_Mode_OUT, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_OD, GPIO_OType_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_Ports, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_DOWN, GPIO_PuPd_NOPULL, GPIO_PuPd_UP, GPIO_InitTypeDef::GPIO_Speed, IO_MODE_ALTERNATE, IO_MODE_ALTERNATE_OD, IO_MODE_ALTERNATE_PU, IO_MODE_ANALOG, IO_MODE_INPUT, IO_MODE_INPUT_PD, IO_MODE_INPUT_PU, IO_MODE_OUTPUT, IO_MODE_OUTPUT_OD, IO_PIN::pin, and IO_PIN::port.
Referenced by Capture_Init(), HSPI_Start(), init(), OLED_Start(), and PWM_Init().
IO_Read()
int IO_Read (IO_IDX idx)
Definition at line 86 of file io.c.
References _ios, GPIO_Ports, GPIO_TypeDef::IDR, IO_PIN::pin, and IO_PIN::port.
IO_Write()
void IO_Write (IO_IDX idx, int val)
Definition at line 71 of file io.c.
References _ios, GPIO_TypeDef::BSRR, GPIO_Ports, IO_PIN::pin, and IO_PIN::port.
Referenced by init(), OLED_Command(), OLED_Data(), OLED_Start(), and Task_LED().