SystemView Application: main.c File Reference
main.c File Reference
SystemView Real-time Analysis Application for STM32F411CE.
#include "main.h"
Macros
#define EXEC_TASK(p)
Macro for SystemView task execution tracking.
Functions
void SYSVIEW_AddTask (void *pTask, const char *sName, U32 Prio)
int main ()
Main application entry point for SystemView analysis.
void init (void)
void init_SeggerModules (void)
void init_Timers (void)
void Task_Print (void)
void init_OLED (void)
void Task_LED (void)
Detailed Description
SystemView Real-time Analysis Application for STM32F411CE.
Author
Fatih Kaptan
Date
08.03.2025
Version
1.0
This application demonstrates SEGGER SystemView integration for real-time task analysis on STM32F411CE. Features include:
Real-time task monitoring and analysis
Timer3 Input Capture with 10µs precision (100MHz÷1000)
OLED display integration for visual feedback
Task scheduling analysis and performance metrics
RTT communication for data logging
Note
Requires SEGGER J-Link for SystemView functionality
Timer3 configured for 10µs Input Capture precision (100MHz÷1000=100kHz)
Warning
Ensure proper SystemView configuration before use
Definition in file main.c.
Macro Definition Documentation
EXEC_TASK
#define EXEC_TASK (p)
Value:
                        SEGGER_SYSVIEW_OnTaskStartExec((U32)p);   \
                        p();                                      \
                        SEGGER_SYSVIEW_OnTaskStopReady((U32)p, 0);
Macro for SystemView task execution tracking.
Parameters
p Task function pointer
This macro wraps task execution with SystemView markers for real-time analysis and timeline visualization.
Definition at line 31 of file main.c.
Referenced by main().
Function Documentation
init()
void init (void)
Definition at line 65 of file main.c.
References Capture_Init(), init_OLED(), init_Timers(), IO_Init(), IO_MODE_OUTPUT, IO_Write(), IOP_LED, PWM_Init(), Sys_ConsoleInit(), Sys_IoInit(), and Sys_TickInit().
Referenced by main().
init_OLED()
void init_OLED (void)
Definition at line 163 of file main.c.
References DelayMs, FNT_LARGE, OLED_Circle(), OLED_ClearDisplay(), OLED_Line(), OLED_Rotate(), OLED_SetCursor(), OLED_SetFont(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_Print(), and SET_PIXEL.
Referenced by init().
init_SeggerModules()
void init_SeggerModules (void)
Definition at line 81 of file main.c.
References SEGGER_SYSVIEW_Conf(), SYSVIEW_AddTask(), Task_LED(), and Task_Print().
Referenced by main().
init_Timers()
void init_Timers (void)
Definition at line 94 of file main.c.
References SYS_CLOCK_FREQ, TIMER_1, TIMER_4, TIMER_5, Timer_Init(), Timer_Start(), and TimerIntConfig().
Referenced by init().
main()
int main ()
Main application entry point for SystemView analysis.
Returns
int Return status (never reached in embedded application)
Initializes SystemView modules and enters the main task loop. The application continuously executes two main tasks:
Task_LED: Controls LED state with SystemView monitoring
Task_Print: Updates OLED display with Timer3 capture data
Note
Timer3 provides 10µs precision for Input Capture timing measurements
See also
init_SeggerModules() for SystemView initialization
EXEC_TASK() macro for task execution tracking
Definition at line 52 of file main.c.
References EXEC_TASK, init(), init_SeggerModules(), Task_LED(), and Task_Print().
SYSVIEW_AddTask()
void SYSVIEW_AddTask (void * pTask, const char * sName, U32 Prio)
Definition at line 70 of file SEGGER_SYSVIEW_Conf._NoOS.c.
Referenced by init_SeggerModules().
Task_LED()
void Task_LED (void)
Definition at line 191 of file main.c.
References clock(), CLOCKS_PER_SEC, IO_Write(), IOP_LED, SEGGER_SYSVIEW_RecordEndCall(), and SEGGER_SYSVIEW_RecordVoid().
Referenced by init_SeggerModules(), and main().
Task_Print()
void Task_Print (void)
Definition at line 116 of file main.c.
References _TmTick, FNT_BIG, FNT_SMALL, g_T3CaptureCount, g_T3CaptureCountOntime, g_T5Count, OLED_GetCursor(), OLED_GetFont(), OLED_SetCursor(), and OLED_SetFont().
Referenced by init_SeggerModules(), and main().