SystemView Application: main.h File Reference
main.h File Reference
#include "system.h"
#include "io.h"
#include "oled.h"
#include "timer.h"
Macros
#define SYS_CLOCK_FREQ CLOCK_FREQ
Functions
void init (void)
void Task_Print (void)
void init_OLED (void)
void Task_LED (void)
void init_Timers (void)
void init_SeggerModules (void)
void SYSVIEW_AddTask (void *pTask, const char *sName, U32 Prio)
Macro Definition Documentation
SYS_CLOCK_FREQ
#define SYS_CLOCK_FREQ CLOCK_FREQ
Definition at line 13 of file main.h.
Referenced by init_Timers().
Function Documentation
init()
void init (void)
Definition at line 65 of file main.c.
References Capture_Init(), init_OLED(), init_Timers(), IO_Init(), IO_MODE_OUTPUT, IO_Write(), IOP_LED, PWM_Init(), Sys_ConsoleInit(), Sys_IoInit(), and Sys_TickInit().
Referenced by main().
init_OLED()
void init_OLED (void)
Definition at line 163 of file main.c.
References DelayMs, FNT_LARGE, OLED_Circle(), OLED_ClearDisplay(), OLED_Line(), OLED_Rotate(), OLED_SetCursor(), OLED_SetFont(), SEGGER_SYSVIEW_MarkStart(), SEGGER_SYSVIEW_MarkStop(), SEGGER_SYSVIEW_Print(), and SET_PIXEL.
Referenced by init().
init_SeggerModules()
void init_SeggerModules (void)
Definition at line 81 of file main.c.
References SEGGER_SYSVIEW_Conf(), SYSVIEW_AddTask(), Task_LED(), and Task_Print().
Referenced by main().
init_Timers()
void init_Timers (void)
Definition at line 94 of file main.c.
References SYS_CLOCK_FREQ, TIMER_1, TIMER_4, TIMER_5, Timer_Init(), Timer_Start(), and TimerIntConfig().
Referenced by init().
SYSVIEW_AddTask()
void SYSVIEW_AddTask (void * pTask, const char * sName, U32 Prio)
Definition at line 70 of file SEGGER_SYSVIEW_Conf._NoOS.c.
References _aTasks, _NumTasks, NUM_TASKS, SEGGER_SYSVIEW_TASKINFO::Prio, SEGGER_SYSVIEW_OnTaskCreate(), SEGGER_SYSVIEW_TASKINFO::sName, SEGGER_SYSVIEW_TASKINFO::StackBase, SEGGER_SYSVIEW_TASKINFO::StackSize, SEGGER_SYSVIEW_TASKINFO::TaskID, and U32.
Task_LED()
void Task_LED (void)
Definition at line 191 of file main.c.
References clock(), CLOCKS_PER_SEC, IO_Write(), IOP_LED, SEGGER_SYSVIEW_RecordEndCall(), and SEGGER_SYSVIEW_RecordVoid().
Referenced by init_SeggerModules(), and main().
Task_Print()
void Task_Print (void)
Definition at line 116 of file main.c.
References _TmTick, FNT_BIG, FNT_SMALL, g_T3CaptureCount, g_T3CaptureCountOntime, g_T5Count, OLED_GetCursor(), OLED_GetFont(), OLED_SetCursor(), and OLED_SetFont().
Referenced by init_SeggerModules(), and main().