SystemView Application: oled.c File Reference
oled.c File Reference
#include "io.h"
#include "system.h"
#include "spi.h"
#include "oled.h"
#include <math.h>
#include "font_5x8.h"
#include "font_7x16.h"
#include "font_15x32.h"
Macros
#define NPGS 8
#define NSEG 128
#define T_COLS (NSEG / (_szWidth + 1))
#define T_ROWS (NPGS / _szHeight)
#define abs(a)
#define PI 3.141592654
Functions
static void OLED_Command (unsigned char cmd)
void OLED_Data (unsigned char data)
void OLED_Rotate (int bRotate)
void SSD1306_Init (int bRotate)
void OLED_Start (int bRotate)
void OLED_SetPage (unsigned char page)
void OLED_SetSegment (unsigned char segment)
void OLED_FillPage (unsigned char page, unsigned char c)
void OLED_FillDisplay (unsigned char c)
void OLED_ClearDisplay (void)
FNT_t OLED_GetFont (void)
void OLED_SetFont (FNT_t font)
void OLED_SetCursor (unsigned char row, unsigned char col)
void OLED_GetCursor (int *pRow, int *pCol)
void OLED_UpdateDisplay (void)
void OLED_Scroll (int nPgs)
void OLED_Return (void)
void OLED_NewLine (void)
void OLED_PutChar (char ch)
COLOR_t OLED_GetPixel (int x, int y)
void OLED_SetPixel (int x, int y, COLOR_t c)
void OLED_Line (int x0, int y0, int x1, int y1, COLOR_t c)
void OLED_Circle (int x, int y, int r, COLOR_t c)
void OLED_putch (unsigned char c)
Variables
static unsigned char _DspRam [NPGS *NSEG]
static unsigned char _page
static unsigned char _segment
static int _szWidth
static int _szHeight
static const unsigned char * _pFont
static unsigned char _row
static unsigned char _col
static FNT_t _font
Macro Definition Documentation
abs
#define abs (a)
Value:
(((a) > 0) ? (a) : -(a))
Definition at line 401 of file oled.c.
Referenced by OLED_Line().
NPGS
#define NPGS 8
Definition at line 16 of file oled.c.
Referenced by OLED_FillDisplay(), OLED_Scroll(), OLED_UpdateDisplay(), and SSD1306_Init().
NSEG
#define NSEG 128
Definition at line 17 of file oled.c.
Referenced by OLED_Data(), OLED_FillPage(), OLED_GetPixel(), OLED_Scroll(), OLED_SetPixel(), OLED_UpdateDisplay(), and SSD1306_Init().
PI
#define PI 3.141592654
Definition at line 452 of file oled.c.
Referenced by OLED_Circle().
T_COLS
#define T_COLS (NSEG / (_szWidth + 1))
Definition at line 30 of file oled.c.
Referenced by OLED_PutChar().
T_ROWS
#define T_ROWS (NPGS / _szHeight)
Definition at line 31 of file oled.c.
Referenced by OLED_NewLine().
Function Documentation
OLED_Circle()
void OLED_Circle (int x, int y, int r, COLOR_t c)
Definition at line 454 of file oled.c.
References OLED_SetPixel(), and PI.
Referenced by init_OLED().
OLED_ClearDisplay()
void OLED_ClearDisplay (void)
Definition at line 203 of file oled.c.
References OLED_FillDisplay().
Referenced by init_OLED(), and OLED_putch().
OLED_Command()
static void OLED_Command (unsigned char cmd) static
Definition at line 33 of file oled.c.
References IO_Write(), IOP_OLED_CS, IOP_OLED_DC, and SPI_Data.
Referenced by OLED_Rotate(), OLED_SetPage(), OLED_SetSegment(), and SSD1306_Init().
OLED_Data()
void OLED_Data (unsigned char data)
Definition at line 46 of file oled.c.
References _DspRam, _page, _segment, IO_Write(), IOP_OLED_CS, IOP_OLED_DC, NSEG, and SPI_Data.
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_FillDisplay()
void OLED_FillDisplay (unsigned char c)
Definition at line 195 of file oled.c.
References NPGS, and OLED_FillPage().
Referenced by OLED_ClearDisplay().
OLED_FillPage()
void OLED_FillPage (unsigned char page, unsigned char c)
Definition at line 184 of file oled.c.
References NSEG, OLED_Data(), OLED_SetPage(), and OLED_SetSegment().
Referenced by OLED_FillDisplay().
OLED_GetCursor()
void OLED_GetCursor (int * pRow, int * pCol)
Definition at line 256 of file oled.c.
References _col, and _row.
Referenced by Task_Print().
OLED_GetFont()
FNT_t OLED_GetFont (void)
Definition at line 210 of file oled.c.
References _font.
Referenced by Task_Print().
OLED_GetPixel()
COLOR_t OLED_GetPixel (int x, int y)
Definition at line 349 of file oled.c.
References _DspRam, CLR_PIXEL, NSEG, and SET_PIXEL.
OLED_Line()
void OLED_Line (int x0, int y0, int x1, int y1, COLOR_t c)
Definition at line 403 of file oled.c.
References abs, and OLED_SetPixel().
Referenced by init_OLED().
OLED_NewLine()
void OLED_NewLine (void)
Definition at line 299 of file oled.c.
References _row, _szHeight, OLED_Scroll(), and T_ROWS.
Referenced by OLED_putch(), and OLED_PutChar().
OLED_putch()
void OLED_putch (unsigned char c)
Definition at line 483 of file oled.c.
References OLED_ClearDisplay(), OLED_NewLine(), OLED_PutChar(), and OLED_Return().
Referenced by _putch().
OLED_PutChar()
void OLED_PutChar (char ch)
Definition at line 310 of file oled.c.
References _col, _font, _pFont, _row, _szHeight, _szWidth, FNT_BIG, OLED_Data(), OLED_NewLine(), OLED_Return(), OLED_SetPage(), OLED_SetSegment(), and T_COLS.
Referenced by OLED_putch().
OLED_Return()
void OLED_Return (void)
Definition at line 294 of file oled.c.
References _col.
Referenced by OLED_putch(), and OLED_PutChar().
OLED_Rotate()
void OLED_Rotate (int bRotate)
Definition at line 65 of file oled.c.
References OLED_Command(), and OLED_UpdateDisplay().
Referenced by init_OLED(), and SSD1306_Init().
OLED_Scroll()
void OLED_Scroll (int nPgs)
Definition at line 275 of file oled.c.
References _DspRam, NPGS, NSEG, and OLED_UpdateDisplay().
Referenced by OLED_NewLine().
OLED_SetCursor()
void OLED_SetCursor (unsigned char row, unsigned char col)
Definition at line 250 of file oled.c.
References _col, and _row.
Referenced by init_OLED(), and Task_Print().
OLED_SetFont()
void OLED_SetFont (FNT_t font)
Definition at line 215 of file oled.c.
References _font, _pFont, _szHeight, _szWidth, FNT_BIG, FNT_LARGE, FNT_SMALL, g_ChrTab, g_ChrTab2, and g_ChrTab3.
Referenced by init_OLED(), OLED_Start(), and Task_Print().
OLED_SetPage()
void OLED_SetPage (unsigned char page)
Definition at line 165 of file oled.c.
References _page, and OLED_Command().
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_SetPixel()
void OLED_SetPixel (int x, int y, COLOR_t c)
Definition at line 367 of file oled.c.
References _DspRam, CLR_PIXEL, INV_PIXEL, NSEG, OLED_Data(), OLED_SetPage(), OLED_SetSegment(), and SET_PIXEL.
Referenced by OLED_Circle(), and OLED_Line().
OLED_SetSegment()
void OLED_SetSegment (unsigned char segment)
Definition at line 174 of file oled.c.
References _segment, and OLED_Command().
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_Start()
void OLED_Start (int bRotate)
Definition at line 121 of file oled.c.
References DelayMs, FNT_BIG, FNT_LARGE, FNT_SMALL, IO_Init(), IO_MODE_OUTPUT, IO_Write(), IOP_OLED_CS, IOP_OLED_DC, IOP_OLED_RES, OLED_SetFont(), SPI_Start, and SSD1306_Init().
Referenced by Sys_ConsoleInit().
OLED_UpdateDisplay()
void OLED_UpdateDisplay (void)
Definition at line 262 of file oled.c.
References _DspRam, NPGS, NSEG, OLED_Data(), OLED_SetPage(), and OLED_SetSegment().
Referenced by OLED_Rotate(), and OLED_Scroll().
SSD1306_Init()
void SSD1306_Init (int bRotate)
Definition at line 84 of file oled.c.
References _DspRam, NPGS, NSEG, OLED_Command(), and OLED_Rotate().
Referenced by OLED_Start().
Variable Documentation
_col
unsigned char _col static
Definition at line 27 of file oled.c.
Referenced by OLED_GetCursor(), OLED_PutChar(), OLED_Return(), and OLED_SetCursor().
_DspRam
unsigned char _DspRam[NPGS *NSEG] static
Definition at line 20 of file oled.c.
Referenced by OLED_Data(), OLED_GetPixel(), OLED_Scroll(), OLED_SetPixel(), OLED_UpdateDisplay(), and SSD1306_Init().
_font
FNT_t _font static
Definition at line 28 of file oled.c.
Referenced by OLED_GetFont(), OLED_PutChar(), and OLED_SetFont().
_page
unsigned char _page static
Definition at line 21 of file oled.c.
Referenced by OLED_Data(), and OLED_SetPage().
_pFont
const unsigned char* _pFont static
Definition at line 25 of file oled.c.
Referenced by OLED_PutChar(), and OLED_SetFont().
_row
unsigned char _row static
Definition at line 27 of file oled.c.
Referenced by OLED_GetCursor(), OLED_NewLine(), OLED_PutChar(), and OLED_SetCursor().
_segment
unsigned char _segment static
Definition at line 21 of file oled.c.
Referenced by OLED_Data(), and OLED_SetSegment().
_szHeight
int _szHeight static
Definition at line 24 of file oled.c.
Referenced by OLED_NewLine(), OLED_PutChar(), and OLED_SetFont().
_szWidth
int _szWidth static
Definition at line 23 of file oled.c.
Referenced by OLED_PutChar(), and OLED_SetFont().