SystemView Application: oled.h File Reference
oled.h File Reference
Macros
#define OL_FNT_SMALL
#define OL_FNT_LARGE
#define OL_FNT_BIG
#define OL_LINE
#define OL_CIRCLE
#define OL_SPI_PORT SPI_1
#define SPI_Start(m)
#define SPI_Data(v)
Enumerations
enum FNT_t { FNT_SMALL , FNT_LARGE , FNT_BIG }
enum COLOR_t { CLR_PIXEL , SET_PIXEL , INV_PIXEL }
Functions
void OLED_Start (int bRotate)
void OLED_SetPage (unsigned char page)
void OLED_SetSegment (unsigned char segment)
void OLED_Data (unsigned char data)
void OLED_ClearDisplay (void)
void OLED_UpdateDisplay (void)
void OLED_Rotate (int bRotate)
COLOR_t OLED_GetPixel (int x, int y)
void OLED_SetPixel (int x, int y, COLOR_t c)
void OLED_Line (int x0, int y0, int x1, int y1, COLOR_t c)
void OLED_Circle (int x, int y, int r, COLOR_t c)
FNT_t OLED_GetFont (void)
void OLED_SetFont (FNT_t font)
void OLED_SetCursor (unsigned char row, unsigned char col)
void OLED_GetCursor (int *pRow, int *pCol)
void OLED_PutChar (char ch)
void OLED_putch (unsigned char c)
Macro Definition Documentation
OL_CIRCLE
#define OL_CIRCLE
Definition at line 9 of file oled.h.
OL_FNT_BIG
#define OL_FNT_BIG
Definition at line 6 of file oled.h.
OL_FNT_LARGE
#define OL_FNT_LARGE
Definition at line 5 of file oled.h.
OL_FNT_SMALL
#define OL_FNT_SMALL
Definition at line 4 of file oled.h.
OL_LINE
#define OL_LINE
Definition at line 8 of file oled.h.
OL_SPI_PORT
#define OL_SPI_PORT SPI_1
Definition at line 11 of file oled.h.
SPI_Data
#define SPI_Data (v)
Value:
HSPI_Data(OL_SPI_PORT, v)
Definition at line 13 of file oled.h.
Referenced by OLED_Command(), and OLED_Data().
SPI_Start
#define SPI_Start (m)
Value:
HSPI_Start(OL_SPI_PORT, m)
Definition at line 12 of file oled.h.
Referenced by OLED_Start().
Enumeration Type Documentation
COLOR_t
enum COLOR_t
Enumerator
CLR_PIXEL
SET_PIXEL
INV_PIXEL
Definition at line 21 of file oled.h.
FNT_t
enum FNT_t
Enumerator
FNT_SMALL
FNT_LARGE
FNT_BIG
Definition at line 15 of file oled.h.
Function Documentation
OLED_Circle()
void OLED_Circle (int x, int y, int r, COLOR_t c)
Definition at line 454 of file oled.c.
References OLED_SetPixel(), and PI.
Referenced by init_OLED().
OLED_ClearDisplay()
void OLED_ClearDisplay (void)
Definition at line 203 of file oled.c.
References OLED_FillDisplay().
Referenced by init_OLED(), and OLED_putch().
OLED_Data()
void OLED_Data (unsigned char data)
Definition at line 46 of file oled.c.
References _DspRam, _page, _segment, IO_Write(), IOP_OLED_CS, IOP_OLED_DC, NSEG, and SPI_Data.
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_GetCursor()
void OLED_GetCursor (int * pRow, int * pCol)
Definition at line 256 of file oled.c.
References _col, and _row.
Referenced by Task_Print().
OLED_GetFont()
FNT_t OLED_GetFont (void)
Definition at line 210 of file oled.c.
References _font.
Referenced by Task_Print().
OLED_GetPixel()
COLOR_t OLED_GetPixel (int x, int y)
Definition at line 349 of file oled.c.
References _DspRam, CLR_PIXEL, NSEG, and SET_PIXEL.
OLED_Line()
void OLED_Line (int x0, int y0, int x1, int y1, COLOR_t c)
Definition at line 403 of file oled.c.
References abs, and OLED_SetPixel().
Referenced by init_OLED().
OLED_putch()
void OLED_putch (unsigned char c)
Definition at line 483 of file oled.c.
References OLED_ClearDisplay(), OLED_NewLine(), OLED_PutChar(), and OLED_Return().
Referenced by _putch().
OLED_PutChar()
void OLED_PutChar (char ch)
Definition at line 310 of file oled.c.
References _col, _font, _pFont, _row, _szHeight, _szWidth, FNT_BIG, OLED_Data(), OLED_NewLine(), OLED_Return(), OLED_SetPage(), OLED_SetSegment(), and T_COLS.
Referenced by OLED_putch().
OLED_Rotate()
void OLED_Rotate (int bRotate)
Definition at line 65 of file oled.c.
References OLED_Command(), and OLED_UpdateDisplay().
Referenced by init_OLED(), and SSD1306_Init().
OLED_SetCursor()
void OLED_SetCursor (unsigned char row, unsigned char col)
Definition at line 250 of file oled.c.
References _col, and _row.
Referenced by init_OLED(), and Task_Print().
OLED_SetFont()
void OLED_SetFont (FNT_t font)
Definition at line 215 of file oled.c.
References _font, _pFont, _szHeight, _szWidth, FNT_BIG, FNT_LARGE, FNT_SMALL, g_ChrTab, g_ChrTab2, and g_ChrTab3.
Referenced by init_OLED(), OLED_Start(), and Task_Print().
OLED_SetPage()
void OLED_SetPage (unsigned char page)
Definition at line 165 of file oled.c.
References _page, and OLED_Command().
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_SetPixel()
void OLED_SetPixel (int x, int y, COLOR_t c)
Definition at line 367 of file oled.c.
References _DspRam, CLR_PIXEL, INV_PIXEL, NSEG, OLED_Data(), OLED_SetPage(), OLED_SetSegment(), and SET_PIXEL.
Referenced by OLED_Circle(), and OLED_Line().
OLED_SetSegment()
void OLED_SetSegment (unsigned char segment)
Definition at line 174 of file oled.c.
References _segment, and OLED_Command().
Referenced by OLED_FillPage(), OLED_PutChar(), OLED_SetPixel(), and OLED_UpdateDisplay().
OLED_Start()
void OLED_Start (int bRotate)
Definition at line 121 of file oled.c.
References DelayMs, FNT_BIG, FNT_LARGE, FNT_SMALL, IO_Init(), IO_MODE_OUTPUT, IO_Write(), IOP_OLED_CS, IOP_OLED_DC, IOP_OLED_RES, OLED_SetFont(), SPI_Start, and SSD1306_Init().
Referenced by Sys_ConsoleInit().
OLED_UpdateDisplay()
void OLED_UpdateDisplay (void)
Definition at line 262 of file oled.c.
References _DspRam, NPGS, NSEG, OLED_Data(), OLED_SetPage(), and OLED_SetSegment().
Referenced by OLED_Rotate(), and OLED_Scroll().