SystemView Application: spi.c File Reference
spi.c File Reference
#include "io.h"
#include "system.h"
#include "stm32f4xx_spi.h"
#include "spi.h"
Functions
void HSPI_Start (SPI_t nSPI, int mode)
unsigned char HSPI_Data (SPI_t nSPI, unsigned char val)
Variables
static SPI_TypeDef * _pSPI []
Function Documentation
HSPI_Data()
unsigned char HSPI_Data (SPI_t nSPI, unsigned char val)
Definition at line 67 of file spi.c.
References _pSPI, SPI_I2S_FLAG_RXNE, SPI_I2S_FLAG_TXE, SPI_I2S_GetFlagStatus(), SPI_I2S_ReceiveData(), and SPI_I2S_SendData().
HSPI_Start()
void HSPI_Start (SPI_t nSPI, int mode)
Definition at line 15 of file spi.c.
References _ios, _pSPI, ENABLE, GPIO_AF_SPI1, GPIO_AF_SPI2, GPIO_PinAFConfig(), GPIO_Ports, IO_Init(), IO_MODE_ALTERNATE, IOP_SPI1_MISO, IOP_SPI1_MOSI, IOP_SPI1_SCK, IOP_SPI2_MISO, IOP_SPI2_MOSI, IOP_SPI2_SCK, RCC_APB1Periph_SPI2, RCC_APB1PeriphClockCmd(), RCC_APB2Periph_SPI1, RCC_APB2PeriphClockCmd(), SPI_1, SPI_2, SPI_InitTypeDef::SPI_BaudRatePrescaler, SPI_BaudRatePrescaler_2, SPI_Cmd(), SPI_InitTypeDef::SPI_CPHA, SPI_CPHA_1Edge, SPI_CPHA_2Edge, SPI_InitTypeDef::SPI_CPOL, SPI_CPOL_High, SPI_CPOL_Low, SPI_InitTypeDef::SPI_DataSize, SPI_DataSize_8b, SPI_InitTypeDef::SPI_Direction, SPI_Direction_2Lines_FullDuplex, SPI_InitTypeDef::SPI_FirstBit, SPI_FirstBit_MSB, SPI_Init(), SPI_InitTypeDef::SPI_Mode, SPI_Mode_Master, SPI_InitTypeDef::SPI_NSS, and SPI_NSS_Soft.
Variable Documentation
_pSPI
SPI_TypeDef* _pSPI[] static
Initial value:
= {
  SPI1,
  SPI2
}
Definition at line 10 of file spi.c.
Referenced by HSPI_Data(), and HSPI_Start().