SystemView Application: system.h File Reference
system.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "SEGGER_SYSVIEW.h"
#include "SEGGER_SYSVIEW_Conf.h"
Macros
#define CLOCKS_PER_SEC 1000
#define _STDIN 0
#define _STDOUT 1
#define _STDERR 2
#define CLOCK_FREQ 100000000
#define INSTR_FREQ ((CLOCK_FREQ) * 8 / 9)
#define US_CYCLES (INSTR_FREQ / 1000000)
#define MS_CYCLES (INSTR_FREQ / 1000)
#define DelayUs(us)
#define DelayMs(ms)
Typedefs
typedef uint32_t clock_t
Functions
clock_t clock (void)
void __delay (unsigned long ncy)
void Sys_IoInit (void)
void Sys_TickInit (void)
Variables
volatile clock_t _TmTick
Macro Definition Documentation
_STDERR
#define _STDERR 2
Definition at line 19 of file system.h.
_STDIN
#define _STDIN 0
Definition at line 17 of file system.h.
_STDOUT
#define _STDOUT 1
Definition at line 18 of file system.h.
CLOCK_FREQ
#define CLOCK_FREQ 100000000
Definition at line 28 of file system.h.
CLOCKS_PER_SEC
#define CLOCKS_PER_SEC 1000
Definition at line 15 of file system.h.
Referenced by Sys_TickInit(), and Task_LED().
DelayMs
#define DelayMs (ms)
Value:
__delay((ms) * MS_CYCLES)
Definition at line 34 of file system.h.
Referenced by init_OLED(), and OLED_Start().
DelayUs
#define DelayUs (us)
Value:
__delay((us) * US_CYCLES)
Definition at line 33 of file system.h.
INSTR_FREQ
#define INSTR_FREQ ((CLOCK_FREQ) * 8 / 9)
Definition at line 29 of file system.h.
MS_CYCLES
#define MS_CYCLES (INSTR_FREQ / 1000)
Definition at line 31 of file system.h.
US_CYCLES
#define US_CYCLES (INSTR_FREQ / 1000000)
Definition at line 30 of file system.h.
Typedef Documentation
clock_t
typedef uint32_t clock_t
Definition at line 21 of file system.h.
Function Documentation
__delay()
void __delay (unsigned long ncy)
clock()
clock_t clock (void)
Definition at line 45 of file system.c.
References _TmTick.
Referenced by Task_LED().
Sys_IoInit()
void Sys_IoInit (void)
Definition at line 22 of file system.c.
References ENABLE, GPIO_Clocks, N_PORTS, and RCC_AHB1PeriphClockCmd().
Referenced by init().
Sys_TickInit()
void Sys_TickInit (void)
Definition at line 30 of file system.c.
References CLOCKS_PER_SEC, and SystemCoreClock.
Referenced by init().
Variable Documentation
_TmTick
volatile clock_t _TmTick extern
Definition at line 20 of file system.c.
Referenced by clock(), Sys_ClockTick(), and Task_Print().