SystemView Application: system.c File Reference
system.c File Reference
#include "io.h"
#include "system.h"
Macros
#define _STDIN 0
#define _STDOUT 1
#define _STDERR 2
#define N_PORTS (sizeof(GPIO_Clocks) / sizeof(int))
Functions
void Sys_IoInit (void)
void Sys_TickInit (void)
void Sys_ClockTick (void)
clock_t clock (void)
void Sys_ConsoleInit (void)
void _putch (unsigned char c)
size_t _write (int handle, unsigned char *buffer, size_t size)
Variables
static const int GPIO_Clocks []
volatile clock_t _TmTick = 0
Macro Definition Documentation
_STDERR
#define _STDERR 2
Definition at line 5 of file system.c.
Referenced by _write().
_STDIN
#define _STDIN 0
Definition at line 3 of file system.c.
_STDOUT
#define _STDOUT 1
Definition at line 4 of file system.c.
Referenced by _write().
N_PORTS
#define N_PORTS (sizeof(GPIO_Clocks) / sizeof(int))
Definition at line 17 of file system.c.
Referenced by Sys_IoInit().
Function Documentation
_putch()
void _putch (unsigned char c)
Definition at line 59 of file system.c.
References OLED_putch().
Referenced by _write().
_write()
size_t _write (int handle, unsigned char * buffer, size_t size)
Definition at line 68 of file system.c.
References _putch(), _STDERR, _STDOUT, and NULL.
clock()
clock_t clock (void)
Definition at line 45 of file system.c.
References _TmTick.
Referenced by Task_LED().
Sys_ClockTick()
void Sys_ClockTick (void)
Definition at line 37 of file system.c.
References _TmTick, SEGGER_SYSVIEW_RecordEnterISR(), and SEGGER_SYSVIEW_RecordExitISR().
Referenced by SysTick_Handler().
Sys_ConsoleInit()
void Sys_ConsoleInit (void)
Definition at line 50 of file system.c.
References NULL, and OLED_Start().
Referenced by init().
Sys_IoInit()
void Sys_IoInit (void)
Definition at line 22 of file system.c.
References ENABLE, GPIO_Clocks, N_PORTS, and RCC_AHB1PeriphClockCmd().
Referenced by init().
Sys_TickInit()
void Sys_TickInit (void)
Definition at line 30 of file system.c.
References CLOCKS_PER_SEC, and SystemCoreClock.
Referenced by init().
Variable Documentation
_TmTick
volatile clock_t _TmTick = 0
Definition at line 20 of file system.c.
Referenced by clock(), Sys_ClockTick(), and Task_Print().
GPIO_Clocks
const int GPIO_Clocks[] static
Initial value:
= {
  RCC_AHB1Periph_GPIOA,
  RCC_AHB1Periph_GPIOB,
  RCC_AHB1Periph_GPIOC,
  RCC_AHB1Periph_GPIOD,
  RCC_AHB1Periph_GPIOE,
  RCC_AHB1Periph_GPIOF,
  RCC_AHB1Periph_GPIOG,
}
Definition at line 7 of file system.c.
Referenced by Sys_IoInit().