SystemView Application: timer.h File Reference
timer.h File Reference
Macros
#define TIMER_DEBUG 1
Enumerations
enum {
TIMER_1 , TIMER_2 , TIMER_3 , TIMER_4 ,
TIMER_5
}
Functions
void Timer_Init (int tmNo, unsigned prescale, unsigned period, unsigned repeat)
void Timer_Start (int tmNo, int bStart)
void Timer_Reset (int tmNo)
void TimerIntConfig (int tmNo, int priority)
void PWM_Init (uint32_t period, uint32_t duty)
void Capture_Init (void)
Variables
volatile unsigned long g_T1Count
volatile unsigned long g_T2Count
volatile unsigned long g_T3Count
volatile unsigned long g_T4Count
volatile unsigned long g_T5Count
volatile uint16_t g_T3CaptureCount
volatile uint16_t g_T3CaptureCountOntime
Macro Definition Documentation
TIMER_DEBUG
#define TIMER_DEBUG 1
Definition at line 4 of file timer.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TIMER_1
TIMER_2
TIMER_3
TIMER_4
TIMER_5
Definition at line 6 of file timer.h.
Function Documentation
Capture_Init()
void Capture_Init (void)
Definition at line 103 of file timer.c.
References ENABLE, GPIO_AF_TIM3, GPIO_PinAFConfig(), GPIO_PinSource5, GPIO_PinSource6, GPIOA, GPIOB, IO_Init(), IO_MODE_ALTERNATE_PU, IOP_CAPTURE1, IOP_CAPTURE2, TIM3, TIM_ICInitTypeDef::TIM_Channel, TIM_Channel_1, TIM_Channel_2, TIM_ClearITPendingBit(), TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInit(), TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICPolarity_BothEdge, TIM_ICPolarity_Falling, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICPSC_DIV1, TIM_ICInitTypeDef::TIM_ICSelection, TIM_ICSelection_DirectTI, TIM_IT_CC1, TIM_IT_CC2, TIM_ITConfig(), TIMER_3, Timer_Init(), and Timer_Start().
Referenced by init().
PWM_Init()
void PWM_Init (uint32_t period, uint32_t duty)
Definition at line 75 of file timer.c.
References _ios, ENABLE, GPIO_AF_TIM2, GPIO_PinAFConfig(), GPIO_Ports, IO_Init(), IO_MODE_ALTERNATE, IOP_PWM, SystemCoreClock, TIM2, TIM_ARRPreloadConfig(), TIM_OC3Init(), TIM_OC3PreloadConfig(), TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCIdleState_Reset, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCMode_PWM1, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCPolarity_High, TIM_OCPreload_Enable, TIM_OCInitTypeDef::TIM_OutputState, TIM_OutputState_Enable, TIM_OCInitTypeDef::TIM_Pulse, TIMER_2, Timer_Init(), and Timer_Start().
Referenced by init().
Timer_Init()
void Timer_Init (int tmNo, unsigned prescale, unsigned period, unsigned repeat)
Definition at line 26 of file timer.c.
References ENABLE, RCC_APB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), TIM_CKD_DIV1, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CounterMode_Up, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter, TIM_TimeBaseInit(), TIMER_1, Timer_Reset(), TimerTable, and TimRccTab.
Referenced by Capture_Init(), init_Timers(), and PWM_Init().
Timer_Reset()
void Timer_Reset (int tmNo)
Definition at line 54 of file timer.c.
References TIM_SetCounter(), and TimerTable.
Referenced by Timer_Init().
Timer_Start()
void Timer_Start (int tmNo, int bStart)
Definition at line 49 of file timer.c.
References DISABLE, ENABLE, TIM_Cmd(), and TimerTable.
Referenced by Capture_Init(), init_Timers(), and PWM_Init().
TimerIntConfig()
void TimerIntConfig (int tmNo, int priority)
Definition at line 60 of file timer.c.
References ENABLE, TIM_ClearITPendingBit(), TIM_IT_Update, TIM_ITConfig(), TimerTable, and TimIrqTab.
Referenced by init_Timers().
Variable Documentation
g_T1Count
volatile unsigned long g_T1Count extern
Definition at line 150 of file timer.c.
Referenced by TIM1_UP_TIM10_IRQHandler().
g_T2Count
volatile unsigned long g_T2Count extern
Definition at line 165 of file timer.c.
Referenced by TIM2_IRQHandler().
g_T3CaptureCount
volatile uint16_t g_T3CaptureCount extern
Definition at line 181 of file timer.c.
Referenced by Task_Print(), and TIM3_IRQHandler().
g_T3CaptureCountOntime
volatile uint16_t g_T3CaptureCountOntime extern
Definition at line 182 of file timer.c.
Referenced by Task_Print(), and TIM3_IRQHandler().
g_T3Count
volatile unsigned long g_T3Count extern
Definition at line 180 of file timer.c.
Referenced by TIM3_IRQHandler().
g_T4Count
volatile unsigned long g_T4Count extern
Definition at line 229 of file timer.c.
Referenced by TIM4_IRQHandler().
g_T5Count
volatile unsigned long g_T5Count extern
Definition at line 241 of file timer.c.
Referenced by Task_Print(), and TIM5_IRQHandler().