SystemView Application: timer.c File Reference
timer.c File Reference
#include "io.h"
#include "system.h"
#include "timer.h"
Functions
void Timer_Init (int tmNo, unsigned prescale, unsigned period, unsigned repeat)
void Timer_Start (int tmNo, int bStart)
void Timer_Reset (int tmNo)
void TimerIntConfig (int tmNo, int priority)
void PWM_Init (uint32_t period, uint32_t duty)
void Capture_Init (void)
void TIM1_UP_TIM10_IRQHandler (void)
void TIM2_IRQHandler (void)
void TIM3_IRQHandler (void)
void TIM4_IRQHandler (void)
void TIM5_IRQHandler (void)
Variables
TIM_TypeDef * TimerTable []
uint32_t TimRccTab []
IRQn_Type TimIrqTab []
volatile unsigned long g_T1Count = 0
volatile unsigned long g_T2Count = 0
volatile unsigned long g_T3Count = 0
volatile uint16_t g_T3CaptureCount = 0
volatile uint16_t g_T3CaptureCountOntime = 0
volatile unsigned long g_T4Count = 0
volatile unsigned long g_T5Count = 0
unsigned long debug_int =0
Function Documentation
Capture_Init()
void Capture_Init (void)
Definition at line 103 of file timer.c.
References ENABLE, GPIO_AF_TIM3, GPIO_PinAFConfig(), GPIO_PinSource5, GPIO_PinSource6, GPIOA, GPIOB, IO_Init(), IO_MODE_ALTERNATE_PU, IOP_CAPTURE1, IOP_CAPTURE2, TIM3, TIM_ICInitTypeDef::TIM_Channel, TIM_Channel_1, TIM_Channel_2, TIM_ClearITPendingBit(), TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInit(), TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICPolarity_BothEdge, TIM_ICPolarity_Falling, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICPSC_DIV1, TIM_ICInitTypeDef::TIM_ICSelection, TIM_ICSelection_DirectTI, TIM_IT_CC1, TIM_IT_CC2, TIM_ITConfig(), TIMER_3, Timer_Init(), and Timer_Start().
Referenced by init().
PWM_Init()
void PWM_Init (uint32_t period, uint32_t duty)
Definition at line 75 of file timer.c.
References _ios, ENABLE, GPIO_AF_TIM2, GPIO_PinAFConfig(), GPIO_Ports, IO_Init(), IO_MODE_ALTERNATE, IOP_PWM, SystemCoreClock, TIM2, TIM_ARRPreloadConfig(), TIM_OC3Init(), TIM_OC3PreloadConfig(), TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCIdleState_Reset, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCMode_PWM1, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCPolarity_High, TIM_OCPreload_Enable, TIM_OCInitTypeDef::TIM_OutputState, TIM_OutputState_Enable, TIM_OCInitTypeDef::TIM_Pulse, TIMER_2, Timer_Init(), and Timer_Start().
Referenced by init().
TIM1_UP_TIM10_IRQHandler()
void TIM1_UP_TIM10_IRQHandler (void)
Definition at line 151 of file timer.c.
References g_T1Count, SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitTimer(), SET, TIM_ClearITPendingBit(), TIM_GetITStatus(), TIM_IT_Update, TIMER_1, and TimerTable.
TIM2_IRQHandler()
void TIM2_IRQHandler (void)
Definition at line 166 of file timer.c.
References g_T2Count, SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitTimer(), SET, TIM_ClearITPendingBit(), TIM_GetITStatus(), TIM_IT_Update, TIMER_2, and TimerTable.
TIM3_IRQHandler()
void TIM3_IRQHandler (void)
Definition at line 183 of file timer.c.
References g_T3CaptureCount, g_T3CaptureCountOntime, g_T3Count, SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitTimer(), SET, TIM3, TIM_ClearITPendingBit(), TIM_GetCapture1(), TIM_GetCapture2(), TIM_GetITStatus(), TIM_IT_CC1, TIM_IT_CC2, TIM_IT_Update, TIMER_3, and TimerTable.
TIM4_IRQHandler()
void TIM4_IRQHandler (void)
Definition at line 230 of file timer.c.
References g_T4Count, SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitTimer(), SET, TIM_ClearITPendingBit(), TIM_GetITStatus(), TIM_IT_Update, TIMER_4, and TimerTable.
TIM5_IRQHandler()
void TIM5_IRQHandler (void)
Definition at line 243 of file timer.c.
References debug_int, g_T5Count, SEGGER_SYSVIEW_Print(), SEGGER_SYSVIEW_RecordEnterTimer(), SEGGER_SYSVIEW_RecordExitTimer(), SET, TIM_ClearITPendingBit(), TIM_GetITStatus(), TIM_IT_Update, TIMER_5, and TimerTable.
Timer_Init()
void Timer_Init (int tmNo, unsigned prescale, unsigned period, unsigned repeat)
Definition at line 26 of file timer.c.
References ENABLE, RCC_APB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), TIM_CKD_DIV1, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CounterMode_Up, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter, TIM_TimeBaseInit(), TIMER_1, Timer_Reset(), TimerTable, and TimRccTab.
Referenced by Capture_Init(), init_Timers(), and PWM_Init().
Timer_Reset()
void Timer_Reset (int tmNo)
Definition at line 54 of file timer.c.
References TIM_SetCounter(), and TimerTable.
Referenced by Timer_Init().
Timer_Start()
void Timer_Start (int tmNo, int bStart)
Definition at line 49 of file timer.c.
References DISABLE, ENABLE, TIM_Cmd(), and TimerTable.
Referenced by Capture_Init(), init_Timers(), and PWM_Init().
TimerIntConfig()
void TimerIntConfig (int tmNo, int priority)
Definition at line 60 of file timer.c.
References ENABLE, TIM_ClearITPendingBit(), TIM_IT_Update, TIM_ITConfig(), TimerTable, and TimIrqTab.
Referenced by init_Timers().
Variable Documentation
debug_int
unsigned long debug_int =0
Definition at line 242 of file timer.c.
Referenced by TIM5_IRQHandler().
g_T1Count
volatile unsigned long g_T1Count = 0
Definition at line 150 of file timer.c.
Referenced by TIM1_UP_TIM10_IRQHandler().
g_T2Count
volatile unsigned long g_T2Count = 0
Definition at line 165 of file timer.c.
Referenced by TIM2_IRQHandler().
g_T3CaptureCount
volatile uint16_t g_T3CaptureCount = 0
Definition at line 181 of file timer.c.
Referenced by Task_Print(), and TIM3_IRQHandler().
g_T3CaptureCountOntime
volatile uint16_t g_T3CaptureCountOntime = 0
Definition at line 182 of file timer.c.
Referenced by Task_Print(), and TIM3_IRQHandler().
g_T3Count
volatile unsigned long g_T3Count = 0
Definition at line 180 of file timer.c.
Referenced by TIM3_IRQHandler().
g_T4Count
volatile unsigned long g_T4Count = 0
Definition at line 229 of file timer.c.
Referenced by TIM4_IRQHandler().
g_T5Count
volatile unsigned long g_T5Count = 0
Definition at line 241 of file timer.c.
Referenced by Task_Print(), and TIM5_IRQHandler().
TimerTable
TIM_TypeDef* TimerTable[]
Initial value:
= {
  TIM1,TIM2,TIM3,TIM4,TIM5
}
Definition at line 5 of file timer.c.
Referenced by TIM1_UP_TIM10_IRQHandler(), TIM2_IRQHandler(), TIM3_IRQHandler(), TIM4_IRQHandler(), TIM5_IRQHandler(), Timer_Init(), Timer_Reset(), Timer_Start(), and TimerIntConfig().
TimIrqTab
IRQn_Type TimIrqTab[]
Initial value:
= {
  TIM1_UP_TIM10_IRQn,
  TIM2_IRQn,
  TIM3_IRQn,
  TIM4_IRQn,
  TIM5_IRQn,
}
Definition at line 18 of file timer.c.
Referenced by TimerIntConfig().
TimRccTab
uint32_t TimRccTab[]
Initial value:
= {
  RCC_APB2Periph_TIM1,
  RCC_APB1Periph_TIM2,
  RCC_APB1Periph_TIM3,
  RCC_APB1Periph_TIM4,
  RCC_APB1Periph_TIM5,
  }
Definition at line 10 of file timer.c.
Referenced by Timer_Init().